### ISSUE TITLE
How do you configure email properly?

### ISSUE THREAD

**Issue by chuyskywalker** [haiwen/seahub#10]
I am getting this error:

```
Successfully resetted password to 123456 for user EMAIL_ADDRESS_HERE. But email notification can not be sent, because Email service is not properly configured.
```

I can't find any documentation about how to configure it, and my 15 minutes of bumbling about in the python code didn't do anything to help clarify it for me.

Thanks!

**Comment by rinogo** [comment]
Broken link.  Here's one that should work: https://manual.seafile.com/config/sending_email.html
