### ISSUE TITLE
  Error received: 511 Unknown service (In _start_service)

### ISSUE THREAD

**Issue by haoglehaogle** [haiwen/seahub#1005]
hello,
I can run seahub normally, I get the following error information when I login.

"""
SearpcError at /
Error received: 511 Unknown service (In _start_service)
"""
I found ccnet-server runing at port 10001, but can't find port 8082, 12001 opened.

who could tell me what's error?
thanks!

**Comment by shoeper** [comment]
https://forum.seafile-server.org
