### ISSUE TITLE
[Usability] Group and Organization libraries should appear under "Shared"

### ISSUE THREAD

**Issue by dakira** [haiwen/seahub#1017]
In our organization we have some org-wide libraries shared through the organization and several team-libraries shared through the respective groups.

We did some usability tests with some of our newer users. None of them were able to find the organization- or team-wide libraries on their own.

**Comment by freeplant** [comment]
Thanks for the suggestion. I think in v5.1 the redesigned navigation should solve the problem:

![image](https://cloud.githubusercontent.com/assets/109339/12738480/0ec6c748-c99c-11e5-9099-7e0bfb9b96f6.png)
