### ISSUE TITLE
incompatible css for pdf2htmlEX

### ISSUE THREAD

**Issue by bsavelev** [haiwen/seahub#110]
Hello!
I have installed seafile with sefevents and get some trouble with css for pkdf2htmlEX that built-in in seahub (/media/css/doc_and_pdf.css)
I have pdf2htmlex 0.11-1~git201311150048r2 and html produced with this version is incompat with css from seahub.

I think that uniting base.css and fancy.css into doc_and_pdf.css is not very good idea=)
they could be placed separately for easy replace with valid version from pdf2htmlEX package (for me /usr/share/pdf2htmlEX/*.css)

**Comment by freeplant** [comment]
This issue is obsolete.
