### ISSUE TITLE
bad shared link

### ISSUE THREAD

**Issue by JonnyTischbein** [haiwen/seahub#1109]
Maybe this is just my fault or a bug.
I'm trying to fix the generate share link for files/folders. If I'm right the SERVICE_URL in conf/ccnet.conf is generating the link.
I'm getting a shared Link like this
    
    http://WAN_IP:PORT/....

but my conf file is

    SERVICE_URL = https://domain.tld
    
Is there anything I have to do to flush / update the service_url ? I did restart the services after changing config file. It seams like an old configuration. I did have used the WAN_IP and a PORT for testing before using nginx and a dns.

Seafile Server Version: 5.0.4
Debian: Linux localhost 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64 GNU/Linux
using NGINX

**Comment by shoeper** [comment]
Have you overwritten your SERVICE_URL in the admin panel?

**Comment by JonnyTischbein** [comment]
Thanks! That's it. Couldn't believe a admin panel overwrites a config file.
