### ISSUE TITLE
Sending Email via SMTP not working

### ISSUE THREAD

**Issue by chodid** [haiwen/seahub#1114]
I configured the seahub_settings.py as follows:
```

EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.domain.tld'        # smpt server
EMAIL_HOST_USER = 'name@domain.tld'    # username and domain
EMAIL_HOST_PASSWORD = 'password'    # password
EMAIL_PORT = 465
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
```

When for example resetting a user password I get the error message 

> Successfully reset password to XXXX, but failed to send email to name@domain.tld, please check your email configuration.

In the log-files the following error appears:

`[ERROR] seahub.views.sysadmin:896 user_reset SMTP AUTH extension not supported by server.`

Thanks in advance for any help.

**Comment by shoeper** [comment]
Please ask questions at forum.seafile-server.org.
