### ISSUE TITLE
Error:Seahub failed to start.

### ISSUE THREAD

**Issue by mureev** [haiwen/seahub#1151]
I did notice an interesting behavior of seahub (latest stable) on my Debian 8.4 server.

I got my system up and running. Execute the following:
`seafile-server-latest/seafile.sh start`

Result as expected

> /conf/ccnet.conf
> Starting seafile server, please wait ...
> Seafile server started
> 
> Done.

I want to start seahub on 8989 as usual. Execute the following:
`seafile-server-latest/seahub.sh start 8989`

Ad getting unexpected result

> LC_ALL is not set in ENV, set to en_US.UTF-8
> Starting seahub at port 8989 ...
> Error:Seahub failed to start.
> Please try to run "./seahub.sh start" again

**The most interesting here that I can't find anything in logs for seahub and even by getting this error I can access to seahub from my browser without any issues.**

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.
