### ISSUE TITLE
Fast-CGI not working

### ISSUE THREAD

**Issue by MrksKwsnck** [haiwen/seahub#1197]
Recently I succesfully deployed Seafile 5.1.1 on Raspbian (Jessie). Starting Seahub up with `./seahub.sh start` works properly.

But now I'd like to try out Fast-CGI. So I tried to start Seahub up with `./seahub.sh start-fastcgi`...

```
Starting seahub (fastcgi) at 127.0.0.1:8000 ...

Seahub is started

Done.
```

First it seems all good. But sadly it's not working :-( There are no errors and such in the logs whatsoever. Investigating the host using `nmap` I found out that the port 8000 is not open. But it's supposed to be open just like without fastcgi, right?

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
