### ISSUE TITLE
Share library to user in cloud mode: need to press Enter

### ISSUE THREAD

**Issue by hydrandt** [haiwen/seahub#1248]
When Seafile runs in cloud mode, the system is not suggesting usernames when typing in the dialog for sharing a library to user. It is necessary to type the whole e-mail address (that's correct).

However, one has to press enter after the whole e-mail has been entered; if one only clicks Submit, the field just gets cleared.

I suppose that just typing the e-mail and pressing Submit should add the sharing - not so many people would figure out they actually have to press enter.

**Comment by shoeper** [comment]
I was able to reproduce it.

**Comment by freeplant** [comment]
In the latest version, we provide a walk around for the problem. When user enter a valid email, the email will be shown at the suggestion list, so that the user can choose it.
