### ISSUE TITLE
Feature Request: Burn After Reading for shared files

### ISSUE THREAD

**Issue by madflow** [haiwen/seahub#1250]
Feature request:

+ Additionally to the expiration date, a "Burn After Reading (X Times)" feature would be nice.
+ After X Downloads, the file would be automatically destroyed

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.
