### ISSUE TITLE
Pro: Office documents preview broken on Ubuntu 16.04 server

### ISSUE THREAD

**Issue by hydrandt** [haiwen/seahub#1258]
I just installed Seafile Pro on an Ubuntu 16.04 server. I had to add a PPA for openjdk-7-jre (ppa:openjdk-r/ppa) (btw, would elasticsearch work with openjdk 8 or 9 too?) and everything works fine, besides the office documents preview. Opening a document ends up with "Document convertion failed." and:

<pre>
[WARNING] error when invoking libreoffice: unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named uno

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
</pre>

Then I installed uno and unotools with pip, and now the error is:

<pre>
[2016-06-22 16:42:35,573] [WARNING] error when invoking libreoffice: unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named unohelper
</pre>

If I start python shell and try to import unotools:

<pre>
>>> import unotools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "unotools/__init__.py", line 16
    def __init__(self, name: str):
                           ^
SyntaxError: invalid syntax
</pre>

I'm not python expert, but I guess this is python3 syntax?

I suppose it is problem with python or uno in ubuntu 16.04, could somebody please confirm this, so that I can open a bugreport in an apropriate place?

**Comment by freeplant** [comment]
This has been fixed in the latest release.
