### ISSUE TITLE
Wrong URL in link when path is containing space

### ISSUE THREAD

**Issue by jkronen** [haiwen/seahub#1274]
Every URL that points to a path with space in it is wrong

Original Path: Library/Photos/last pic/123.jpg

Seahub URL: Library/Photos/last%2520pic/123.jpg
Has to be: Library/Photos/last%20pic/123.jpg

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.

**Comment by jkronen** [comment]
How is this not a bug?

**Comment by freeplant** [comment]
This is most likely a config issue with your Apache server.

**Comment by jkronen** [comment]
I am using nginx. I mainly use the config file from the manual

**Comment by jkronen** [comment]
Here is my config

server {
    listen [::]:443;
    server_name cloud.*;
    ssl on;
    ssl_certificate     /etc/letsencrypt/live/cloud.domain/cert.pem;
    ssl_certificate_key /etc/letsencrypt/live/cloud.domain/privkey.pem;
 
 
    proxy_set_header X-Forwarded-For $remote_addr;
  
    location / {
        fastcgi_pass    127.0.0.1:8000;
        fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
        fastcgi_param   PATH_INFO           $fastcgi_script_name;
 
        fastcgi_param   SERVER_PROTOCOL     $server_protocol;
        fastcgi_param   QUERY_STRING        $query_string;
        fastcgi_param   REQUEST_METHOD      $request_method;
        fastcgi_param   CONTENT_TYPE        $content_type;
        fastcgi_param   CONTENT_LENGTH      $content_length;
        fastcgi_param   SERVER_ADDR         $server_addr;
        fastcgi_param   SERVER_PORT         $server_port;
        fastcgi_param   SERVER_NAME         $server_name;
        fastcgi_param   HTTPS               on;
        fastcgi_param   HTTP_SCHEME         https;
 
        access_log      /var/log/nginx/seahub_c.access.log;
        error_log       /var/log/nginx/seahub_c.error.log;
        fastcgi_read_timeout 36000;
    }
 
    location /seafhttp {
        rewrite ^/seafhttp(.*)$ $1 break;
        proxy_pass http://127.0.0.1:8082;
        client_max_body_size 0;
        proxy_connect_timeout  36000s;
        proxy_read_timeout  36000s;
        proxy_send_timeout  36000s;
        send_timeout  36000s;
    }
 
    location /seafdav {
        fastcgi_pass    127.0.0.1:8080;
        fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
        fastcgi_param   PATH_INFO           $fastcgi_script_name;
 
        fastcgi_param   SERVER_PROTOCOL     $server_protocol;
        fastcgi_param   QUERY_STRING        $query_string;
        fastcgi_param   REQUEST_METHOD      $request_method;
        fastcgi_param   CONTENT_TYPE        $content_type;
        fastcgi_param   CONTENT_LENGTH      $content_length;
        fastcgi_param   SERVER_ADDR         $server_addr;
        fastcgi_param   SERVER_PORT         $server_port;
        fastcgi_param   SERVER_NAME         $server_name;
 
        fastcgi_param   HTTPS               on;
 
        client_max_body_size 0;
 
        access_log      /var/log/nginx/seafdav.access.log;
        error_log       /var/log/nginx/seafdav.error.log;
    }
 
    location /media {
        root /home/seafile/data/seafile/seafile-server-latest/seahub;
    }
}

**Comment by jkronen** [comment]
Seems to be fixed in 5.1.4
