### ISSUE TITLE
Pagination/showing many files is broken in Seafile 6.0.2

### ISSUE THREAD

**Issue by jbbr** [haiwen/seahub#1341]
I just upgraded my seafile server from 5.1.6 to 6.0.2. Now folders with many files are limited to about 100 files and it's not possible to show show more.

In 5.1.6 there used to be some sort of "endless scrolling" or more-button to show more files.

I'm still able to see all files in the Seafile Desktop client 5.1.x

**Comment by freeplant** [comment]
Sorry, I can't reproduce the problem with Chrome 52 or Safari or Firefox. Do you see any error with Chrome's debug mode?

**Comment by jbbr** [comment]
I just tested Firefox 48.0.2, IE9, Edge and don't have this issue with them - also Chrome 52 on Windows 10 does not have this problem.

But Chrome 52 and 53 on my Arch Linux system still have this - even after clearing cache, in icognito mode, disabled adblocker...  So doesn't look like a caching/cookie/adblock issue.
There is no JS-console output.

Same Chrome version, also arch linux, synced chrome profile on my laptop: No problems

Really strange. I still have no idea whats happening there but it doesn't looks like a Seafile problem right now. I'm closing this then.

Thanks and sorry for this strange report :)

If I'm able to reproduce this on other systems I will write again.

**Comment by sagarbehere** [comment]
I am on Seafile server 6.1.2 and am facing exactly the same problem. Can not scroll past the first 100 displayed files/folders.

Tried on Ubuntu Xenial 16.04 amd64 with both Firefox 55.0.2 (64-bit) as well as Google Chrome Version 60.0.3112.113 (Official Build) (64-bit). No output in the Console under Developer Options on these browsers.

The issue does not happen with the same browsers on my macbook air ?!
