### ISSUE TITLE
PNG Thumbnail creation broken in 6.0.3 (_getexif failes)

### ISSUE THREAD

**Issue by jbbr** [haiwen/seahub#1347]
Since 6.0.3 thumbnails does not get created for PNG images anymore. Its probably due to the new exif-orientation code (See commit https://github.com/haiwen/seahub/commit/72902451786f260f0ff62d176cd49db3dcedbe77 )

seahub log:
```2016-09-05 01:51:47,580 [ERROR] seahub.thumbnail.utils:125 generate_thumbnail _getexif```

Example image which triggers error:
https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png

**Comment by freeplant** [comment]
It will be fixed in version 6.0.4.
