### ISSUE TITLE
Full IPv6 support

### ISSUE THREAD

**Issue by fstern** [haiwen/seahub#135]
Hi, 

is it possible to make ccnet-server, seaf-server and httpserver listen on IPv6? Currently they only listen on IPv4 and this might break if clients are dual-stacked or only have IPv6 connectivity. 

Thanks, 

Falk

**Comment by focmb** [comment]
I have a dual stack lite internet connection. That means, my provider give me a native ipv6 net and it would be nice if seafile supports ipv6.

**Comment by forouher** [comment]
You can use Seafile with ipv6. I do it and don't experience any issues.

You just have to handle all connections through the webserver, as described here: http://manual.seafile.com/overview/components.html ("Server 4.0").

**Comment by forouher** [comment]
To elaborate a bit: It doesn't really matter anymore that ccnet is ipv4 only. When using HTTPS sync, ccnet et. al. are only used locally on the server. The only communication with clients is via the webserver (e.g. an apache). So you just have to

- make your webserver ipv6-ready
- upgrade to Seafile 4.x
- use a Seafile client 4.1.x

**Comment by freeplant** [comment]
@forouher is right.

**Comment by focmb** [comment]
Oh thanks. Will try to deploy seafile with the apache 2 via ssl.
