### ISSUE TITLE
Can't access user web page in 6.0.4

### ISSUE THREAD

**Issue by amof** [haiwen/seahub#1367]
After an upgrade from Seafile community 5.1.4 to 6.0.4, I'm facing a problem. The user can't go to his webpage. The page is loading indefinitely.
The seafile client is synchronizing correctly and it is possible to see the web page to put the login/password. 

My configuration : 
- NAS RN102 with ARMv7 1.2GHz dual core Marvell ® Armada 370 processor
- 512MB RAM
- Seafile Server is compiled by hand

The only log that show an error is error.log in seafile-server/runtime.
The log is attached.
[error.txt](https://github.com/haiwen/seahub/files/491646/error.txt)

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com
