### ISSUE TITLE
Slow response loading home once logged in

### ISSUE THREAD

**Issue by sjroe** [haiwen/seahub#1371]
v6.0.4

I have been running seafile for a number of years now with little issue.  However lately it has become incredibly unresponsive on loading the home page once logged in.  Here is an excerpt from the log for the given request:

`[pid: 5717|app: 0|req: 86/226] x.x.x.x () {46 vars in 877 bytes} [Mon Oct 10 14:51:35 2016] GET /sf/ => generated 103898 bytes in 15680 msecs (HTTP/1.1 200) 4 headers in 234 bytes (1 switches on core 0)
`

As you can see it is taking >15 seconds to return!  During this 15 second period my server CPU jumps to 100%.

I have noticed that this is also the case when accessing the admin console:

`[pid: 5718|app: 0|req: 173/266] x.x.x.x () {44 vars in 839 bytes} [Mon Oct 10 14:57:25 2016] GET /sf/sysadmin/ => generated 35542 bytes in 15349 msecs (HTTP/1.1 200) 4 headers in 234 bytes (1 switches on core 0)
`

Other end points appear to load without issue.

Note that I have deployed the seafile webclient at a non-root domain (hence GET /sf/ and GET /sf/sysadmin/).

Any assistance would be appreciated.

**Comment by sjroe** [comment]
I added `DEBUG = True` to `seahub_settings.py` in an attempt to further diagnose this issue. However, after restarting the service the response is back to as expected:

`[pid: 15940|app: 0|req: 5/7] x.x.x.x () {44 vars in 823 bytes} [Mon Oct 10 18:01:25 2016] GET /sf/ => generated 103643 bytes in 683 msecs (HTTP/1.1 200) 4 headers in 234 bytes (1 switches on core 0)
`

Removing `DEBUG = True` slows the response down again to ~15 seconds.

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com
Here is a possible cause: The first time you visit the server, the server will combine several js files into one and create a temporary file. Maybe somehow the temporary file not able to save to local disk because permission problem. So every time the temporary file is generated again, which is very slow.
