### ISSUE TITLE
Wrong URL path generate

### ISSUE THREAD

**Issue by brentybh** [haiwen/seahub#1381]
Visit domain root path, expect https://bohan.in/accounts/login/?next=/
but https://bohan.in/accounts/login/accounts/login/?next=/

Recycle bin https://bohan.in/repo/recycle/37731d39-9fd0-4112-bc38-2291b15314e2/repo/37731d39-9fd0-4112-bc38-2291b15314e2/online_gc/

Using fastcgi + nginx

```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    fastcgi_pass 127.0.0.1:8000;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    include fastcgi_params;
```

**Comment by brentybh** [comment]
file fastcgi_params
    fastcgi_param  QUERY_STRING       $query_string;
    fastcgi_param  REQUEST_METHOD     $request_method;
    fastcgi_param  CONTENT_TYPE       $content_type;
    fastcgi_param  CONTENT_LENGTH     $content_length;

    fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
    fastcgi_param  REQUEST_URI        $request_uri;
    fastcgi_param  DOCUMENT_URI       $document_uri;
    fastcgi_param  DOCUMENT_ROOT      $document_root;
    fastcgi_param  SERVER_PROTOCOL    $server_protocol;
    fastcgi_param  REQUEST_SCHEME     $scheme;
    fastcgi_param  HTTPS              $https if_not_empty;

    fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
    fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;

**Comment by freeplant** [comment]
I think this is not a bug of Seafile. Please ask support questions in our forum https://forum.seafile.com

**Comment by brentybh** [comment]
@freeplant Can you give me more information about this? What may cause this?
