### ISSUE TITLE
Apache 500 Internal Server Error when retrieving history for some files

### ISSUE THREAD

**Issue by arnova** [haiwen/seahub#1389]
I'm running a server with Debian 8 (x64), Apache 2.4.10, MySQL 5.5.25 and SeaFile 6.0.5. I've configured Apache to use a proxy (+rewrite rule) without fcgi (don't know if that makes a difference for my issue?) to workaround the dreadful url encoding bug in Debian's Apache 2.4.10. The problem I'm facing is that when accessing the history for some files in the SeaFile webinterface, it takes a very long time before I either get the history or with some files I even get an "Apache 500 Internal Server Error". I've checked the server's load and at least the cpu usage isn't the bottleneck since it's only taking about 15%. Any idea how to fix this issue?

**Comment by freeplant** [comment]
For some frequently modified libraries, retrieving the history of a file requires scan a lot of files on the disk, which is slow. You can extend The timeout setting of Apache to bypass The problem. Or you can find a specific version via the snapshot feature.

**Comment by arnova** [comment]
But does it make sense then that this is also slow for a single file in a library of which there is only a single revision?

**Comment by freeplant** [comment]
For a single file, the history of the library in a week also has to be scanned. But there is some room for improvement.

**Comment by arnova** [comment]
That would be great :-) It's really slow on our "pretty-fast" hardware. I assume replacing Apache with nginx doesn't solve this right? Is this a database issue?

**Comment by freeplant** [comment]
> I assume replacing Apache with nginx doesn't solve this right?

Yes.

> Is this a database issue?

No, Seafile has to read a lot of files from the disk.

**Comment by arnova** [comment]
That's strange since I don't see a high datarate coming from disk while it runs (tested with iostat/iotop on Linux) or it must starve due to a high number of random reads scattered all over the disk.

**Comment by freeplant** [comment]
> it must starve due to a high number of random reads scattered all over the disk

Your are right. To scanning the history, a lot of small files need to be read.

**Comment by arnova** [comment]
One more note: The library in question that is slow, wasn't modified at all the last week (afaik). Does this still make any sense then?

**Comment by freeplant** [comment]
The problem is already fixed.

**Comment by arnova** [comment]
> 
> 
> The problem is already fixed.

Could you please tell me in which version this was fixed?
