### ISSUE TITLE
UnicodeEncodeError when editing a file online (/repo/{repo_id}/file/edit/)

### ISSUE THREAD

**Issue by moschlar** [haiwen/seahub#1411]
Hi everyone,

this Exception occurs, when a user edits a textual file in the browser and when he manually sets the encoding to `gbk` but writes umlauts in the text (e.g. `äöü`).
```
UnicodeEncodeError: 'gbk' codec can't encode character u'\xe4' in position 0: illegal multibyte sequence
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "seahub/views/file.py", line 1141, in file_edit
    return file_edit_submit(request, repo_id)
  File "seahub/views/file.py", line 1086, in file_edit_submit
    content = content.encode(encoding)
```

There should at least be exception handling around that line to present a nicer error message to the user.

While debugging that, I also discovered that the file edit page does allow you to change the encoding to any of `FILE_ENCODING_LIST = ['auto', 'utf-8', 'gbk', 'ISO-8859-1', 'ISO-8859-5']`, but when you select any other than `["gbk", "utf-8"]`, saving fails with *Invalid Arguments*.

Regards,
Moritz

**Comment by freeplant** [comment]
https://github.com/haiwen/seahub/pull/1414
