### ISSUE TITLE
Comment on files

### ISSUE THREAD

**Issue by typingm0nk** [haiwen/seahub#1424]
I noticed the comments on files are bound to the filename. I don't think that is intentional.
Version: 6.0.4 pro

If you create a file foo and leave some comments, they disappear when you rename that file.
But they are not lost. Rename to foo again and they are there.

Further, if you create a new file foo instead, it will have the comments from the old foo file.

**Comment by freeplant** [comment]
Yes, it is by design. The comments are bound to the file path.
