### ISSUE TITLE
Support .tar.gz to download entire folders on the fly, without waiting for zip

### ISSUE THREAD

**Issue by atay** [haiwen/seahub#1431]
I would like to join your community as I'm active user of seafile.

I would like to know what do you think of functionality to download `.tar.gz` of entire folder/selected files. Quite often I have photos and videos that I want to send to my friends, but recently this is much bigger (last time 4GB) and it takes forever to zip it. I was wondering what do you think of another button next to `ZIP` called `TAR.GZ` that will not need to create a file, but will start download instantly with compression on the fly? 

It can be implemented for shared sources as well as in Seafile web explorer. I would like to implement this, but first I would like to know what do you think guys about this idea.

**Comment by shoeper** [comment]
I like the idea but would prefer improving the zip function. It should be possible to generate zip files on the fly as well. Improving the current zip functionality (or replacing it with a better one) would keep the ui clean and everyone would have an advantage (most people don't know what tar.gz ist and afaik it can't be opened on any Windows machines without additional software).

**Comment by freeplant** [comment]
We don't do on compression on the fly because the limitation of third party libraries used (libevhtp).

**Comment by LendLord** [comment]
+1

**Comment by freeplant** [comment]
This feature has been implemented in the golang file server.
