### ISSUE TITLE
Sorting in folder seems only cosmetic

### ISSUE THREAD

**Issue by OmgImAlexis** [haiwen/seahub#1468]
When I sort a directory of images by "last updated" the info changes in the rows as well as the icons changing but when I click on an item it shows the same images in either order. It looks like just the text and icon is changed but not the links to open the items.

Here's a video showing it. 
https://seafile.home.wvvw.me/f/89d9a8fbc7/?raw=1

**Comment by freeplant** [comment]
Fixed in https://github.com/haiwen/seahub/pull/1476
