### ISSUE TITLE
G Suite / SSO / Oauth Integration ?

### ISSUE THREAD

**Issue by npotier** [haiwen/seahub#1500]
Hi,

I've been using Seafile / Seahub for a while in my company. We are very happy of it. 
It would be awesome to have ah SSO Integration compatible with G Suite.

Is there any plan on it ? Oauth feature was in the roadmap in previous versions but disapeared.

I would be happy to contribute to this feature with other interrested people.

**Comment by freeplant** [comment]
We don't have a plan to implement it yet. You are welcome to contribute.
