### ISSUE TITLE
Support two-factor authentication (2FA) for non-Pro version

### ISSUE THREAD

**Issue by thecosmicfrog** [haiwen/seahub#1533]
Hi there,

I really appreciate your work on Seafile/Seahub and, while I understand the requirement to differentiate the Pro version for monetisation reasons, disallowing two-factor authentication (2FA) for the community version is, for me, an odd and potentially dangerous decision.

Two-factor authentication should not be considered a feature. It is a fundamental necessity in the modern cloud era to protect our information from malicious attackers and provides a hugely comforting safety net in a situation where a password is stolen or compromised.

I sincerely hope that you will consider enabling this feature for the community version of Seafile/Seahub, for the sake of your users' safety and security.

Many thanks again for your time and effort.

**Comment by freeplant** [comment]
We don't have such a plan yet. Maybe in the future, we will add it to community edition.

**Comment by 92lleo** [comment]
I'm totally with @thecosmicfrog here. 2FA is not a nice2have feature, but it's security relevant. Merging time/key based 2FA (via google authenticator or similar) should not be a hard task for you, but it would strengthen the "own secure cloud" factor, that seafile already has.
See [this post](https://forum.seafile.com/t/support-two-factor-authentication-2fa-for-non-pro-version/2518).
Thanks,
Leo

**Comment by freeplant** [comment]
It will be added to community edition.

**Comment by OmgImAlexis** [comment]
@freeplant do you have a really rough ETA? 3 months? 6 months?

**Comment by thecosmicfrog** [comment]
Thank you for reconsidering @freeplant! That's great news!

**Comment by lavalampa** [comment]
Any news on this?

**Comment by freeplant** [comment]
It will be included in version 6.2.
