### ISSUE TITLE
nfs / smb share

### ISSUE THREAD

**Issue by thorus90** [haiwen/seahub#157]
Please add the functionality to mount smb and/or nfs shares as a library. I guess it would be enough if it is mounted in some temp directory of seafile with cifs-utils or nfs-client and make it accessible fo user.

On groups.google.com I found that there are already plans:

https://groups.google.com/forum/#!topic/seafile/Gtok8zdajTc

But I wasn't able to find that issue here. Is there a official bug tracker?

**Comment by hitchhiker** [comment]
That's not a valid argument, it could be uploaded to space and back, stored as smoke signals on the moon and still be mountable in some limited way as a fs. See FUSE.

**Comment by ikcalB** [comment]
@freeplant @lins05 

seafile does now allow to mount a library as windows network-drive.
please reopen this bug, or change the status no wont_implement - which i would sadly regret

**Comment by shoeper** [comment]
> OLD:
> seafile does now allow to mount a synced library as windows network-drive.
> edited to stay corrected

Seafile supports WebDAV.

> I cannot see, why that should not be possible: for the webinterface you need an API which is able to

It does not integrate in the datamodel and synchronisation wouldn't work reliable. You can run the client instead to import data to Seafile (For a short time now there is also an option to sync every x minutes).

**Comment by ikcalB** [comment]
@shoeper 
>>I cannot see, why that should not be possible: for the webinterface you need an API which is able to

>It does not integrate in the datamodel and synchronisation wouldn't work reliable. You can run the client instead to import data to Seafile (For a short time now there is also an option to sync every x minutes).

how is displaying files, adding one by one or downloading one by one (web interface) different, than what would be needed to implement a fs driver?

**Comment by shoeper** [comment]
The clients wouldn't be able to sync those.

So of course it isn't technically impossible but I think there are too many drawbacks. (This is not necessarily Seafile Ltd.'s opinion).

**Comment by ikcalB** [comment]
@shoeper I'm not intending to sync against an nfs share!
I'd like to make some file operations, without having to sync (a possibly very large library):
- down- & upload some files by cp'ing in a shell, like on a local fs
- run some scripts to delete or move / rename files
** and most importantly **
- allow easy backing up of "network drives", speak: allow (samba) network access to seafile libraries, without duplicating the data on the file server

**Comment by shoeper** [comment]
One currently possible way is to use WebDAV (SeafDAV). The other one is to use the API or if only read access is needed FUSE can be used (see manual.seafile.com).
