### ISSUE TITLE
Wrong variable name in translation

### ISSUE THREAD

**Issue by dhimler** [haiwen/seahub#1608]
Hi,

I noticed that the first sentence of an invitation mail stayed in English whereas the rest of the email got translated without any problem. After some searching I located the problem. Within the django.po files the variable for the username is wrong and should be changed from "user" to "escaped_nickname". Here is an example for the German translation:

@@ -2350,8 +2350,8 @@
 #: seahub/templates/sysadmin/user_add_email.html:15
 #: seahub/templates/sysadmin/user_batch_add_email.html:12
 #, python-format
-msgid "%(user)s invited you to join %(site_name)s."
-msgstr "%(user)s hat Sie eingeladen, %(site_name)s beizutreten."
+msgid "%(escaped_nickname)s invited you to join %(site_name)s."
-msgstr "%(escaped_nickname)s hat Sie eingeladen, %(site_name)s beizutreten."

Kind regards,
Daniel

**Comment by castilma** [comment]
this was fixed 7 days ago.
