### ISSUE TITLE
File upload on mobile device not working

### ISSUE THREAD

**Issue by xkpd3** [haiwen/seahub#1611]
Hello,

I'm running seafile server 6.0.4 (FreeBSD package) on NGINX.

I have created a public file upload link. This works fine in any browser on a computer. However, on the iPhone with Safari (I didn't test any other phones), the upload does not work.

I can add files, but the upload will not start.

Link to test the upload: https://seafile.srv.hagen.coffee/u/d/18d4faadfd

Best Regards,
Stefan

**Comment by Miller101** [comment]
iOS issue possibly in regards to the Apple WebKit Update.

See:
https://github.com/haiwen/seafile-iOS/issues/156

**Comment by shoeper** [comment]
Same issue with your link on Android.

Uploading to seafile.zfn.uni-bremen.de is no issue, though.

**Comment by xkpd3** [comment]
Interesting - I just tried it on Chrome in Windows 10 and upload does not work. The JS debug consoles shows an error 500.

Checking the logs on the server reveals the following:

```
==> seahub_django_request.log <==
2017-05-29 14:17:03,326 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /ajax/repo/485c7d4c-6ea2-483e-aad3-4a85b64b50d6/get-file-uploaded-bytes/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/www/haiwen/seafile-server/seahub/seahub/views/ajax.py", line 1525, in get_file_uploaded_bytes
    uploadedBytes = seafile_api.get_upload_tmp_file_offset(repo_id, file_path)
AttributeError: 'SeafileAPI' object has no attribute 'get_upload_tmp_file_offset'
```

**Comment by killing** [comment]
Hi @xkpd3 I think you enabled web resumable upload. Can you disable this feature?

**Comment by xkpd3** [comment]
Hi,
I just fixed it. I'm not sure what the issue was, but a pretty dumb "pkg install --force seahub" and "service seahub restart" afterwards fixed it.

**Comment by labor4** [comment]
> Hi @xkpd3 I think you enabled web resumable upload. Can you disable this feature?

yes, "ENABLE_RESUMABLE_FILEUPLOAD = False" did it for me

**Comment by shoeper** [comment]
> yes, "ENABLE_RESUMABLE_FILEUPLOAD = False" did it for me

That'd mean there is a bug in the app.
