### ISSUE TITLE
Allow SeaHub run directly with SSL / HTTPS support (without a proxy)

### ISSUE THREAD

**Issue by tzahari** [haiwen/seahub#163]
Hi There,
SeaHub is a great tool. 
But I found a problem with the HTTP proxy config.
The communication between apache/nginx and SeaHub (standalone or FastCGI) is unencrypted. Therefore a local attacker can read all logins & passwords on the port 8000.
The problem is that unicorn is used in version 0.16.1.
With version 0.17. SSL is supported.
See http://docs.gunicorn.org/en/0.17.0/news.html
Can someone update the unicorn to 0.17.x?
Regards
Thomas

**Comment by tzahari** [comment]
Hi @freeplant, 
Why did you closed my issue? Is it fixed?
BR
Thomas

**Comment by freeplant** [comment]
Not fixed yet. Sorry for the mistake.

**Comment by tzahari** [comment]
Thank you.

**Comment by shoeper** [comment]
I'm not sure if it wouldn't be better to allow socket usage to keep things simple.

Furthermore I don't know but I don't believe that gunicorn TLS is as solid, as tested and as configurable as nginx or apache.
