### ISSUE TITLE
[Feature Request] save thumbnails in sqlite

### ISSUE THREAD

**Issue by BlackLotus** [haiwen/seahub#1637]
Seahub stores thumbnails in the fs and after reading https://www.sqlite.org/fasterthanfs.html it seems like a good Idea to instead use a sqlite database.
This could have additional benefits for many filesystems, because many small files tend to fragement filesystems, get slow read times, add additional overhead and tend to come with some problems.

**Comment by shoeper** [comment]
I'm definitely against this. It does not scale well. It has concurrency issues. It does not have good support for object storage.
