### ISSUE TITLE
gunicorn_django not coming up

### ISSUE THREAD

**Issue by davidgfnet** [haiwen/seahub#169]
Hello,

I have successfully installed seafile in my ARM-based box and now i'm facing some problems.
Everything goes well and all services come up (ccnet, seafile-daemon and seafile http server) _but_ seahub.

Whenever I try to run it manually using:
gunicorn_django -c /home/seafile/cloud/seafile-server/runtime/seahub.conf -b 0.0.0.0:8081
It  does nothing. And I checked but the daemon is not listening. (checked using netstat)
Using debug output it prints _nothing_:
gunicorn_django -c /home/seafile/cloud/seafile-server/runtime/seahub.conf -b 0.0.0.0:8081 --debug --log-level debug

Any ideas on how can I debug this issue? I'd rather listen to the experienced ones than start editing python files.
Thanks!

**Comment by freeplant** [comment]
This issue is obsolete.
