### ISSUE TITLE
Avatars absent on settings page

### ISSUE THREAD

**Issue by khorkin** [haiwen/seahub#1741]
Hi,
since I upgrade to 6.1.4 I don't see my avatar on Settings page:
1.1.1.1 - - [02/Aug/2017:11:22:53 +0300] https "GET `/media/avatars/c/7/8c6e323727a368086f65c24c735813/resized/160/f88cdba6a792a8b6c095d87433ba928e.png HTTP/1.1" 502 368 "https://private.seafileserver.com/profile/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36"`

502 - return code due to I have several servers and nginx configured to try get static files from other servers

for 6.0.13 - everything is OK.
`1.1.1.1 - - [02/Aug/2017:11:25:27 +0300] https "GET /media/avatars/c/7/8c6e323727a368086f65c24c735813/resized/80/f88cdba6a792a8b6c095d87433ba928e.png HTTP/1.1" 200 11566 "https://private.seafileserver.com/profile/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36"`

Does new release expected bigger avatars? It's possible to provide "old sized" avatars if big sized not found?

**Comment by freeplant** [comment]
New release expects 2x avatars to be shown perfectly in high DPI screens.

**Comment by khorkin** [comment]
Does it mean that users MUST reupload avatars after migrating to new release ?

**Comment by freeplant** [comment]
No. I mean the new release generated 80px avatar thumbnails (instead of 40px) from the original avatars. The user don't need to re-upload avatars.

**Comment by khorkin** [comment]
Ok. Thank you for clarification. But if user don't re-upload avatar he can't see it on Settings page.
