### ISSUE TITLE
Seahub forcing 2FA on every login

### ISSUE THREAD

**Issue by 92lleo** [haiwen/seahub#1820]
Community Edition 6.2.0 beta:
First: Thanks for porting two factor auth into community edition!
Currently seahub requires to enter the 2FA key everytime a user logs in. There should be an option to
1.  not ask for 2FA key for known devices (eg. in settings) or 
2. a checkbox at login (like "trust this device"). The data seafile keeps from devices (name and ip) could be used.

**Comment by shoeper** [comment]
I agree, but IP would be a bad thing. At least in Germany for most users the IP changes on daily basis for privacy reasons. Thus it would mean daily logout for almost all German users.

**Comment by 92lleo** [comment]
I agree that the ip isn't a good way to do this, i just wanted to give an example. The usual solution to this would be a save an identifier in a cookie and check that (and doing this only if the user selects to remember this device)

**Comment by 92lleo** [comment]
This is now implemented in [6.2.4](https://forum.seafile.com/t/seafile-server-6-2-4-is-ready-a-few-fixes/5140), thanks
