### ISSUE TITLE
Missing in Documentation: How to pass 2FA-Token for Authentication

### ISSUE THREAD

**Issue by henryford** [haiwen/seahub#1823]
Hey,

how do we pass the 2fa-codes to the API-Authentication?

Currently I receive the following error when giving username/password:
`curl -d "username=test@example.com" -d "password=passWORD" https://seafile.example.com/api2/auth-token/`:

`Two factor auth token is missing.`

**Comment by twei7** [comment]
I figure this out from the source code. https://github.com/haiwen/seahub/blob/master/seahub/api2/serializers.py#L114
Just need to add ``-H "X-SEAFILE-OTP: 123456"`` to the curl request.

**Comment by henryford** [comment]
Thanks! I still think this should be in the documentation, so I'm leaving this open.

**Comment by shoeper** [comment]
It has been documented at https://manual.seafile.com/develop/web_api.html
