### ISSUE TITLE
Seahub won

### ISSUE THREAD

**Issue by gr01d** [haiwen/seahub#1828]
I have a raspbian **stretch** 9.1 installed the **seafile server 6.1.2** from the releases rpi. the installation was success. I have manually created the mariadb [mysql] databasse tables using the tutorial from **https://manual.seafile.com/deploy/using_mysql.html** Upon the ./setup-seafile-mysql.sh I entered the default parameters and select the **[2] Use existing ccnet/seafile/seahub databases**. then I now executed under the normal user **$ ./seafile.start** then **$ ./seahub.start port 8XXX** but then the seahub never started **$ pgrep -f seahub** or **ls ../pids** no seahub pid file however if I execute it using **$ sudo ./seahub.start 8XXX** it works. I am concerned that maybe seahub was not supposed to start in root mode but only in the standard non-root account. 

```
seafile-server-latest $ ./seahub.sh start 8XXX

LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub at port 8XXX ...

Seahub is started

Done.
```

```
$ pgrep -f seahub
[NONE]

user@seafile-server-latest $ sudo ./seahub.sh stop

Seahub is not running
Done.
```

but

```
seafile-server-latest $ sudo ./seahub.sh start 8XXX

LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub at port 8XXX ...

Seahub is started

Done.

$ pgrep -f seahub
11XXX
33XXX
33XX3
44XXX 
```
 runs in root mode. this maybe a security risk right?
after running seahub in root I can no longer run it under non-root account with the same port specified:
```

I used pgrep -f seahub and killed each processes using sudo kill <id>

RUNNING UNDER NONROOT:
```
**seafile-server-latest $ ./seahub.sh start 888X

LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub at port 8888 ...
Error:Seahub failed to start.
Please try to run "./seahub.sh start" again**

```
RUNNING UNDER ROOT:
```
$ sudo ./seahub.sh start 8XXX

LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub at port 8XXX ...

Seahub is started

Done.
```
```

$ pgrep -f seahub
11XX
2XXX
3XXX
4XXX

```
any advice?

**Comment by castilma** [comment]
maybe you want to fix the title to "seahub won't start" and the formatting? it is hard to read what you wrote.

I have no experience, so I can only guess. does your normal uid have access to the db?

whatever the problem is, it looks like the start script is buggy: it reports wrongfully a successfull start.

**Comment by gr01d** [comment]
it works now latest update.
