### ISSUE TITLE
logs/seafile.log: Value of config [history:keep_days] is invalid

### ISSUE THREAD

**Issue by jobenvil** [haiwen/seahub#1841]
- Release: xRpi 6.2.1 

Getting this error in `logs/seafile.log` everytime I click documents to view in Seahub:

`[09/25/17 15:02:46] ../common/config-mgr.c(134): Value of config [history:keep_days] is invalid: [7 ]`

Since having in `conf/seafile.conf ` following history keep days variable:
```
...
[history]
# days of history to keep
keep_days = 7
...
```

In seahub is possible to see all file modifications until 1 month, like as `[history] `would not properly work. `[library_trash] `is not configured

Is the configuration obsolete or how to configure to avoid the error in seafile logfile?

**Comment by cuihaikuo** [comment]
That's due to a bug in 6.2.0, you can manually run `delete from SeafileConf` in seafile database, the config will work fine.

**Comment by jobenvil** [comment]
thanks!

**Comment by cuihaikuo** [comment]
And seems like there is a white space ' '  in the end of your config, we didn't check this part after upgrade, it will be fixed soon.

**Comment by jobenvil** [comment]
I will check, no issues, thanks again.
