### ISSUE TITLE
纯HTTPS配置无效

### ISSUE THREAD

**Issue by athurg** [haiwen/seahub#1873]
按照[文档上](http://manual-cn.seafile.com/deploy/https_with_nginx.html)配置好HTTPS后，是不能正常工作的。具体表现是很多地方返回的地址仍然是HTTP的。

文档上的配置能工作的原因是，虽然启用了HTTPS，但是也同时启用了HTTP监听（所有请求rewarite到HTTPS）。所以看不出问题。

要重现很简单，只需要把文档中的nginx配置里下面这段删掉
```Nginx
server {
    listen       80;
    server_name  seafile.example.com;
    rewrite ^ https://$http_host$request_uri? permanent;    #强制将http重定向到https
    server_tokens off;
}
```

分析原因，可能是因为Django的HttpResponseRedirect对象默认返回给客户端的Redirect头始终是HTTP的。即便request里设置了X-Forwarded-Proto为https也如此。解决办法就是在配置文件里的settings.py里添加一个

```python
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') 
```

[具体分析可以参考这里](https://stackoverflow.com/a/41488430)。

我不是很懂Python以及Django，不知道是不是应该有更好的解决方案？

**Comment by imwhatiam** [comment]
建议使用自动安装脚本 https://github.com/haiwen/seafile-server-installer-cn

**Comment by athurg** [comment]
> 建议使用自动安装脚本 https://github.com/haiwen/seafile-server-installer-cn

建议修改代码
