### ISSUE TITLE
自动重命名文件的弊端

### ISSUE THREAD

**Issue by athurg** [haiwen/seahub#1875]
不知道开发者是怎么样的考虑，在很多API（包括但不限于创建文件、上传文件、重命名文件，直接通过git grep check_filename_with_rename就可以搜出来一大票）上，都有自动重命名的规则。

这种规则在用户层面来讲（也许）算是一个好的体验。因为这样可以很方便的处理命名冲突。但是我觉得这种错误处理方式不应该作为API的特性。

原因很简单，因为API的调用者，通常希望得到的是一个“准确”的结果，不管是“错误”还是“正确”。而类似命名冲突时，自动按规则重命名，是调用API的人应该考虑的（比如WEB界面、客户端），而不是API自身应该考虑的。

所以建议：

1. 所有包含类似特性的API，都增加一个参数用于控制是否启用该特性，当禁用该特性时，API调用遇到重命名的情况时，直接返回错误。
2. （建议）默认禁用将该特性，而不是启用该特性。

**Comment by freeplant** [comment]
There is already an option to always overwrite the existing file if it exists in file upload API.

**Comment by athurg** [comment]
> There is already an option to always overwrite the existing file if it exists in file upload API.

我检查了一下文档，并没有看到这样的选项或者参数呢。 文档地址 https://manual.seafile.com/develop/web_api.html#upload-file

**Comment by freeplant** [comment]
https://github.com/haiwen/seafile-docs/pull/518/files
