### ISSUE TITLE
Invalid CSRF - Set-Cookie with secure flag

### ISSUE THREAD

**Issue by holantomas** [haiwen/seahub#1893]
Hi, after setup secure flag in Set-Cookie on apache proxy pass all forms for "write" operation fail on invalind CSRF token. Below I provide full HTTP request logs with and without secure flag.

**Without flag**
[unsecured.txt](https://github.com/haiwen/seahub/files/1459134/unsecured.txt)

**With flag**
[secured.txt](https://github.com/haiwen/seahub/files/1459137/secured.txt)

**Comment by shoeper** [comment]
Do you still set the httponly flag as you did before?

**Comment by holantomas** [comment]
Yes

**Comment by shoeper** [comment]
it cannot work with it. Don't configure something you don't understand.

**Comment by holantomas** [comment]
Oh sorry, I miss understand what flag doing.

**Comment by shoeper** [comment]
It does prevent script from accessing the cookie, thus it (Seahub js) cannot send the token with the request.

So I think you can close the ticket.
