### ISSUE TITLE
[Security] Openredirect

### ISSUE THREAD

**Issue by Rotzbua** [haiwen/seahub#1920]
### Problem
Seahub do not check the forwarded `host`-header by apache/nginx. The user control the header so he can send any  `host`-header.

### Impact
Low, because request header manipulation can not be done easily by 3party.

### Proof:
```bash
curl https://seacloud.cc  -v -H "Host: google.com"
```
### Solution
* Seahub should check the host variable against the configured host in config.
* apache/nginx should not forward bad requests

### Workaround
Filter malformed `host`-header by apache/nginx.

**Comment by xiez** [comment]
Hi @Rotzbua , just added `ALLOWED_HOSTS = ['.seacloud.cc']` , this issue should be resolved.

Thanks!

**Comment by shoeper** [comment]
Looks like this should then also be documented on the manual.

**Comment by xiez** [comment]
https://github.com/haiwen/seafile-docs/blob/master/config/seahub_settings_py.md#security-settings  
Yes! Added to the manual.
