### ISSUE TITLE
[Question] Is it possible to run seahub and seafile on different servers ?

### ISSUE THREAD

**Issue by Adirelle** [haiwen/seahub#1970]
If I wanted to have ccnet-server and seafile-server running on server A (where the seahub data are stored) and seahub running on server B, what should be shared between the two servers ?

It looks like ccnet-server only listen on a unix socket now. If I remember correctly, it was possible to have it listen on TCP sockets. Is it still possible ?

**Comment by freeplant** [comment]
This is not possible.
