### ISSUE TITLE
Deploy with non-root does NOT work

### ISSUE THREAD

**Issue by Zythyr** [haiwen/seahub#1988]
I want to access Sefile from a non-root URL. Thus I followed this guide: https://manual.seafile.com/deploy/deploy_seahub_at_non-root_domain.html. This guide is NOT working for me. I am using Seafile 6.2.4. 

In my _seahub_settings.py_, I added the following lines followed by clearing cache and restarting seafile/seahub. 

```
SERVE_STATIC = False
MEDIA_URL = '/seafmedia/'
COMPRESS_URL = MEDIA_URL
STATIC_URL = MEDIA_URL + 'assets/'
SITE_ROOT = '/seafile/'
LOGIN_URL = '/seafile/accounts/login/'    # NOTE: since version 5.0.4
```

**Issue:** 
After updating _seahub_settings.py_, I am able to access Seahub interface by going to _http://192.168.1.108:8000/seafile_, however, it seem the interface is broken; there no images, no logos, etc... Everything is plain text. See this screenshot: https://i.imgur.com/dsjta4F.png 

I also tried `MEDIA_URL = '/media/'` and  `MEDIA_URL = '/seafile/media/'`. None of these resolved the issue. 

Note: To keep things simple, I did NOT configure Seahub with Apache. I am directly accessing the Seahub interface at port 8000 by going to _http://192.168.1.108:8000/seafile_ instead of _http://192.168.1.108/seafile_ 

Is this guide outdated? https://manual.seafile.com/deploy/deploy_seahub_at_non-root_domain.html The reason I ask is because in the guide the MEDIA_URL is set to _seafmedia_, which I have no idea where that came from, and the Apache configurations for deploying with non-root is using fast CGI compared to the other guide, https://manual.seafile.com/deploy/deploy_with_apache.html, which does NOT use fast CGI and also includes a ProxyPassReverse directive.

**Comment by eriktews** [comment]
Hi, maybe an idea: did you delete the cache in /tmp/ after you changed the settings? You should run the following command once seafile is stopped:

```
rm -rf /tmp/seahub_cache/
```

**Comment by Zythyr** [comment]
@eriktews  Thanks. I fixed the issue. My Apache vhost config was incorrect. I use your suggestion in the other bug report and fixed it. Here are my corrected vhost settings. https://github.com/haiwen/seafile/issues/1982#issuecomment-360962932. 

Also, I have a question. Correct me if I am wrong, but once I update the seahub_settings.py to include the code below, I will NOT be able to access Seafile directly from port 8000 by going to http://192.168.1.108:8000/seafile/. I have to go to http://192.168.1.108/seafile. Otherwise the media files won't load up. 

```
SERVE_STATIC = False
MEDIA_URL = '/seafmedia/'
COMPRESS_URL = MEDIA_URL
STATIC_URL = MEDIA_URL + 'assets/'
SITE_ROOT = '/seafile/'
LOGIN_URL = '/seafile/accounts/login/'   
```

Also, what is the purpose of SERVICE_URL and FILE_SERVER_ROOT? I didn't update these variable and the Seafile website loads perfectly fine.

**Comment by eriktews** [comment]
Hi, so SERVICE_URL is apparently used to generate the share links for externals. I'm not so sure about FILE_SERVER_ROOT, but I assume it's used by the clients.

Regarding the media files, they are served by Apache in my configuration. I assume that's more efficient for static data, so going to :8000 will not work.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
