### ISSUE TITLE
Prevent access from http://xxx.xxx.xxx.xxx:8000

### ISSUE THREAD

**Issue by kun-zhou** [haiwen/seahub#2007]
Since the recommended setup involves a reverse proxy, we need an option to prevent Seahub from being accessed from hosts other than localhost. Right now, we can always access Seahub from port 8000 of the server. This is also may be a security issue because user can forget to connect with https and thus cause information to be divulged.

**Comment by shoeper** [comment]
The user can hardly use it on port 8000.

First, how should he find it?
Second there are many places where one is being redirected to the service url.

And finally this can easily be solved by activating a firewall.
