### ISSUE TITLE
Using Windows IIS 7.0 URL Rewrite to Proxy SSL Requests to Seafile. Apple iOS App doesn't like Spaces in filenames now. Why!

### ISSUE THREAD

**Issue by Natenezz** [haiwen/seahub#202]
I have successfully created proxy & rewrite rules for IIS 7.0 to use SSL Certs. My web interface in firefox and safari works perfectly. I can upload and download files perfectly. 

After I configured the HTTP_SERVER _ROOT = 'https://my.domain.com/seafhttp/.

My apple iOS app "Seafile Pro" stopped working 100%. 
I can upload all files no issues at all!
I can download files that do not have space characters in the filename.

HOWEVER, I can't download files that have spaces in the filename from the server. 
I receive a 404 file not found error as a result. 

#######################################################################

My research: (something is wrong with the URL ) 

### Viewing URL Rewrite Log in IIS 7.0 ###
#iPhone Sends this request via the API2 URL#
#This request includes spaces in the filename %20#
200, GET, /api2/repos/28e2ae81-3575-4f34-aeb0-f3b603f16f2a/file/, p=/Config%20WS%20IDF%2013.txt,

#Then this request is made in the same millisecond, and returns not found 404#
404, GET, /seafhttp/files/c85594df/Config%20WS%20IDF%2013.txt,

Why does these spaces cause this issue? It doesn’t on the website interface.
Just when using the iOS App and the API2.

I looked in the API2 Python code and couldn’t find the problem. 
I do not know enough about python, but the again it api2 works fine when
you don’t set the http_server_root to https:/…

Please advise. 

Thanks,
Nate

**Comment by hitchhiker** [comment]
Was there ever a fix/solution for this?

**Comment by lins05** [comment]
Hi Frank, you can check this post
https://groups.google.com/forum/#!msg/seafile/LBBe2quCwuk/As9Y0ARN9GQJ

**Comment by hitchhiker** [comment]
Hi Lins05 - you rock!! Thank you, that saved me a LOT of time. Cheers.

**Comment by lins05** [comment]
You're welcome. Actually I got that from seafile.io. (one of my weekend
projects)

http://www.seafile.io/?q=iis%20blank%20space&month=2015-01&source=google%20groups
