### ISSUE TITLE
Seafile API 2.1 Get Library History

### ISSUE THREAD

**Issue by pycycle** [haiwen/seahub#2027]
Hi,
I recently discovered an issue with the API call to retrieve the history of a certain repository. 
If I use the following API call, the server returns an error "error_msg": "Internal Server Error"

**API call:** curl -H 'Authorization: Token [...]' -H 'Accept: application/json; charset=utf-8; indent=4' "https://<mydomain>/api/v2.1/repos/<repo-id>/history/"

In the server logs I identified the following error message:
~~~
cat seahub.log 
2018-03-09 09:01:42,220 [ERROR] seahub.api2.endpoints.repo_history:76 get 'SeafileAPI' object has no attribute 'is_passwd_set'
~~~
Installed Seafile Version: seafile-server-6.2.5

**Comment by imwhatiam** [comment]
yeah, there is a bug here, it will be fixed in the next version.

**Comment by pycycle** [comment]
Great :smile: 

You are welcome
