### ISSUE TITLE
[Feature Request] Invalidate API Tokens

### ISSUE THREAD

**Issue by pycycle** [haiwen/seahub#2028]
Hi,
while playing around with the Seafile-API I didn't find any option how to invalidate API tokens. Would be great if there is a button available in the web application, to invalidate the API token for the currently logged in user.
Because if an API token was compromised the user has no option to invalidate this token, to keep the account secure.

I discovered the only current option to invalidate an API token is to delete this token from the database, which is quite difficult for a "normal" user.

Thx

**Comment by freeplant** [comment]
Currently when resetting password, all tokens will be invalidated.

**Comment by pycycle** [comment]
Ok, that's great. Thank you for the info. Maybe you could add a short message to the password part in the user settings. That updating the password will reset the API tokens too. Would be great.

Thank you very much
