### ISSUE TITLE
thirdpart folder dependency generation.

### ISSUE THREAD

**Issue by omkarnathsingh** [haiwen/seahub#2059]
I am using Seafile community edition by using setup from this page https://www.seafile.com/en/download/#server . Now I feel that I need to do some modifications in Seahub, so I replaced the seahub folder by this repository, but as there are not full thirdpart dependencies, I couldn't run the server. 
Please guide how to generate thirdpart dependencies. 
Thanks in advance.

**Comment by xiez** [comment]
If you install from our binary package, please follow the doc in https://manual.seafile.com/deploy/using_sqlite.html

No thirdpart dependencies need to be installed.
