### ISSUE TITLE
Installing seahub requirements.txt fails

### ISSUE THREAD

**Issue by rmolin88** [haiwen/seahub#2060]
More specifically, the specific commit of `django-constance` doesnt seem to be found. See screenshot:
![18-04-01_16 25 42](https://user-images.githubusercontent.com/5428479/38177110-498289f8-35c9-11e8-8950-e77994212eb1.png)

**Comment by xiez** [comment]
Please use this commit (8508ff29141732190faff51d5c2b5474da297732) from https://github.com/haiwen/django-constance/commits/patch2

**Comment by rmolin88** [comment]
Thanks for the quick response!

**Comment by shoeper** [comment]
Is it documented?
