### ISSUE TITLE
Organisation not working as it is said.

### ISSUE THREAD

**Issue by nOmi7** [haiwen/seahub#2064]
I downloaded seafile pro  and evaluating before buying license with 3 users 6.2.10 version
turned  on MULTI_TENANCY = true in seahub and seafile conf.
I see org tab i am able to create org however these things does not work

1) non admin org user can share the file with other org user it should be restricted within the org.
2) Deletion of org does not work . (deletes user but not org)
3) creating org creates new url as org.domain.tld however it does not resolve as there is not dns mapping (how to get this done)

**Comment by freeplant** [comment]
> creating org creates new url as org.domain.tld however it does not resolve as there is not dns mapping (how to get this done)

The feature is not implemented.

Other two should work.
