### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by huegelc** [haiwen/seahub#208]
Hi,

when navigating through a library you can see the level in the breadcrumb navigation
![seafile](https://cloud.githubusercontent.com/assets/6955465/2994269/ae3e7422-dcc9-11e3-8ce6-9b6fd1d28213.PNG)
But if you would like to go to the overview of the libraries you have to click on "start" to get there.
Wouldn´t be easier to have the that all in the breadcrumb navigation?

**Comment by shoeper** [comment]
It's still not optimal. Viewing a library one owns has e.g. this path:
`Libraries / My Libraries / Library Name`

A Library being shared via path has the following path
`Libraries / Library Name`

Imho you should use the same scheme everywhere. Best would be to add the group name to group shared libraries. So e.g.
`Libraries / My Group / Group shared library name` where Libraries link to the user library overview and my group to the group library overview.
