### ISSUE TITLE
Blue template

### ISSUE THREAD

**Issue by huegelc** [haiwen/seahub#209]
Hi,

I have made a custom blue template and thought I share it with you.
## Installation

Please follow the instructions here: https://github.com/haiwen/seafile/wiki/Seahub-customization#customize-seahub-css
Put this lines in your `custom.css`:

```
.hl   {
      background-color: #E3F2FF;
}

a {
   color: #2895F1;
}

a:hover {

    color: #2895F1;
}

.side-tabnav-tabs .tab-cur a, .side-tabnav-tabs .tab-cur a:hover {
    background-color: #2895F1;
}

.side-tabnav h3.hd, .side-tabnav .hd h3 {
    color:  #2895F1;
}
.side-tabnav-tabs .tab a:hover {
   background-color: #E3F2FF;
}

.tabnav-tab-cur a, .tabnav-tab a:hover, .wiki-nav .cur-item .link, .wiki-nav .link:hover, #right-panel .hd .ui-state-active .a, #right-panel .hd .a:hover {
    border-bottom-color: #2895F1;
    color: #2895F1;
    text-decoration: none;
}
#header .nav .a:hover {
  color: #2895F1;
  text-decoration:underline;
}
.new-narrow-panel .hd {
    background: none repeat scroll 0 0 #2895F1;
    border-bottom: 1px solid #D5D5D5;
    color: #FFFFFF;
    font-size: 16px;
    padding: 5px 20px;
}

#right-panel .hd, .tabnav, .repo-file-list-topbar, .wiki-top {
    background: none repeat scroll 0 0 #E3F2FF;
    border-radius: 2px 2px 2px 2px;
    margin-bottom: 0.5em;
    padding: 9px 10px;
}
```

Blue folder icon:
![folder-icon-24](https://cloud.githubusercontent.com/assets/6955465/2994349/19ae2f44-dccb-11e3-8e6a-1ad3619acbc9.png)

Enjoy.

**Comment by rh-programm** [comment]
hey, this is a very awesome Blue Theme 👍 

But can you design the other Icons
![other icons](https://user-images.githubusercontent.com/28979769/33615704-19e216f4-d9db-11e7-89d1-66a4c7ba551e.PNG)

And change the Dropdown Color
![dropdown](https://user-images.githubusercontent.com/28979769/33615725-2d2ba18a-d9db-11e7-86eb-39a4edb12882.PNG)

And the Buttons and the Marked Text
![bottons and marked text](https://user-images.githubusercontent.com/28979769/33615763-47290910-d9db-11e7-97df-8819ca631888.PNG)

And the Login Screen Button

Then it would be perfect 🥇
