### ISSUE TITLE
Sehub downgrades  HTTPS redirection issues

### ISSUE THREAD

**Issue by tofran** [haiwen/seahub#2093]
Seahub login page redirects to HTTP, this means that disabling the webserver HTTP redirection breaks the login flow.

Here is the network log when visiting the seafile server unauthenticated (over HTTPS):

scheme | name | status | Redirects to | Comment
-- | -- | -- | -- | --
https | seafile.example.com | 302 | http://seafile.example.com/accounts/login?next=/ | Initial request to "/" over HTTPS, seafile redirects to HTTP login page (“/login”)
http | login?next=/ | 301 | https://seafile.example.com/accounts/login?next=/ | Nginx redirects to HTTPS
https | login?next=/ | 301 | http://seafile.example.com/accounts/login/?next=/ | Seafile redirects again to HTTP (this time “/login/”)
http | ?next=/ | 301 | https://seafile.example.com/accounts/login/?next=/ | Nginx redirects again to HTTPS
https | ?next=/ | 200 |   | Finally we have the login page

**Expected behavior**
The connection should never be downgraded to HTTP.

**Solution**
Always redirect on the same schema as the current one. 

Version: **6.2.5** 

Note: Both `SERVICE_URL` and `FILE_SERVER_ROOT` are over HTTPS

**Comment by shoeper** [comment]
Yes, your webserver is misconfigured. It is not telling Seafile (Django) connection is secure. Please use the forum to ask such questions.

**Comment by tofran** [comment]
@shoeper thank you, you are certainly right.

I had not set  `X-Forwarded-Proto`: details in the [documentation](https://manual.seafile.com/deploy/https_with_nginx.html).

Also, for reference:
https://forum.seafile.com/t/help-with-nginx-https-redirect/5006
https://forum.seafile.com/t/wrong-redirect-after-login/5066

**Comment by JocelynDelalande** [comment]
Note that **using nginx+fastcgi** (which is deprecated) lead me to the **same http downgrade issue** (even if using recommended nginx fastcgi setup in linked doc). 

Moving to WSGI setup with the linked nginx conf solved the issue for me.
