### ISSUE TITLE
v6.2.5 - Fail to upload, webpage indicates "Unknown error"

### ISSUE THREAD

**Issue by MattMuffin** [haiwen/seahub#2098]
Hello,

I'm using the 64bit Ubuntu package downloaded fro mthe seafile website. When uploading a file of about 90Mb, by the web interface, it shows "Unknown Error" after the loading bar fills up. The file is not i on the server, and the logs indicate these lines:
seahub.api2.endpoints.repo_file_uploaded_bytes:52 get 'SeafileAPI' object has no attribute 'get_upload_tmp_file_offset'

What can be causing this?

Thanks!

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Please use the [forum](https://forum.seafile.com/) for questions.
