### ISSUE TITLE
Should (alphabetically) sort users returned from LDAP

### ISSUE THREAD

**Issue by antaflos** [haiwen/seahub#210]
When listing all LDAP users in the sysadmin view the users are displayed in the order in which they were returned by the LDAP server. An LDAP server (like AD and OpenLDAP) generally does not return search results in any particular order so it is the LDAP client's task to sort the results.

I think the user list at http://seafile.example.com:8000/sys/useradmin/ldap/ should be sorted alphabetically before being displayed and paginated. This makes managing users a bit easier, especially if there are many hundreds of them.

Additionally or alternatively it may be useful to allow sorting users (both from database and LDAP) by "Email", "create at", "last login", "space used" or other available columns.

Off-topic I'd like to say that I am very impressed by the current state of Seafile. It seems very well-rounded and smooth, even more than when I last tried it a year ago. Also the LDAP integration, while basic, seems to work well (considering the issue in https://github.com/haiwen/seafile/issues/274). Kudos! :)

**Comment by antaflos** [comment]
Bumping again.

**Comment by freeplant** [comment]
The user can be searched. We think alphabetically sort users is not necessary.
