### ISSUE TITLE
org/groupadmin/<group-id>/ showing a blank page

### ISSUE THREAD

**Issue by omkarnathsingh** [haiwen/seahub#2115]
I checked views.py and urls.py file, evrything is fine. Still the page appears blank. Is it a known bug?

**Comment by freeplant** [comment]
It will be fixed in version 6.2.13.

**Comment by omkarnathsingh** [comment]
Its fixed in this https://github.com/haiwen/seahub/releases/tag/v6.2.13-pro ??
