### ISSUE TITLE
Upgrading seafile from 6.2 to 6.3 fails

### ISSUE THREAD

**Issue by Ultima1252** [haiwen/seahub#2116]
root@seafile:/usr/local/www/haiwen/seafile-server/upgrade # ./upgrade_6.2_6.3.sh

-------------------------------------------------------------
This script would upgrade your seafile server from 6.2 to 6.3
Press [ENTER] to contiune
-------------------------------------------------------------

Updating seafile/seahub database ...

[INFO] You are using MySQL
[INFO] updating ccnet database...
[INFO] updating seafile database...
[INFO] updating seahub database...
/usr/local/www/haiwen/seafile-server/upgrade/db_update_helper.py:348: Warning: Storage engine InnoDB of the table `seahub-db`.`auth_group` doesn't have this option
  cursor.execute(sql)
[ERROR] Failed to execute sql: Can't create table `seahub-db`.`auth_group_permissions` (errno: 150 "Foreign key constraint is incorrectly formed")

Failed to upgrade your database

**Comment by shoeper** [comment]
I don't see a 6.3 release. I also don't think it has been finished.

**Comment by Ultima1252** [comment]
There are tags that suggest otherwise. If the tags weren't supposed to suggest a release then another should have been used don't you think? Perhaps if it is a release candidate used 6.3.0-RC1 or something to differentiate a release from that of one being used for testing.

Not everyone uses the prepackaged version of Seafile.

**Comment by shoeper** [comment]
I think the same, but that's what I've seen in the past. You can read the announcement section on the forum. It is available as rss by appending .rss

**Comment by shoeper** [comment]
Closing this issue because is it was created before the actual release and I didn't see similar reports after the release.

**Comment by Ultima1252** [comment]
This is because the release was retagged. This is another practice I disagree with. When a release is released, it should not be altered. Package managers create a hash of the release if it is altered we do not know if the release was maliciously tampered with or changed the commit.

**Comment by shoeper** [comment]
I can only tell you how it is handled in this project.

A release a released once it has been announced at https://forum.seafile.com/c/announcements
