### ISSUE TITLE
codeblock not correctly generated when converting from markdown to html in wiki module

### ISSUE THREAD

**Issue by fengwang** [haiwen/seahub#2131]
Example markdown contents with

    ```language-python
    import numpy as np
    ```

The converted html is 

    <pre><code class="lang-language-python">import numpy as np
    </code></pre>

But 

    <pre><code class="language-python">import numpy as np
    </code></pre>

is expected

**Comment by fengwang** [comment]
It seems this has been fixed from upstream marked.js, see https://github.com/markedjs/marked/blob/master/lib/marked.js#L1532

**Comment by freeplant** [comment]
We have implemented a new markdown editor and viewer.
