### ISSUE TITLE
Mail Logs

### ISSUE THREAD

**Issue by omkarnathsingh** [haiwen/seahub#2151]
Hi Dev,

<url>/sys/log/emailaudit/  is always giving me "None". Its not showing any error logs or successful mails send logs. Am I doing anything wrong?

I have configured mail settings and mails do go when I add a new user or share a file.
Thanks.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
