### ISSUE TITLE
Image preview and thumbnails not working with hyphen in path

### ISSUE THREAD

**Issue by T-X** [haiwen/seahub#2166]
When using a path like MyLibrary/event-log/foo.jpg I do not get thumbnails anymore in Seahub when entering the event-log folder. And clicking on foo.jpg I get a "The image could not be loaded" instead of a preview.

Renaming the folder from "event-log" to "eventlog" in Seahub makes thumbnails and previews work again. Renaming it back from "eventlog" to "event-log" makes the issue reappear.

I'm using Seahub and Seafile v6.2.5 with an nginx (1.10.3-1+deb9u1) proxy on top on a Debian stable/Stretch.

---

Looking at the code I could figure out that when entering the "eventlog" folder in Seahub I do get a call for "thumbnail_get()" in seahub/thumbnail/views.py. But when using "event-log" then I won't get this call.

I'm a little stuck with debugging now as I don't know where "thumbnail_get()" is supposed to be called from.

**Comment by T-X** [comment]
A few more observations: The following variants _work fine_: "event_log", "event+log", "event\log", "eventälog", "event&log". So, so far I could only reproduce the issue with a hyphen.

Also, only the direct parent folder of the images seems affected. A variant with a hyphen in the parent's parent folder like "MyLibrary/foo-bar/eventlog/foo.jpg" works fine, too.

**Comment by freeplant** [comment]
Since no other reported the same issue with the same version, I think it is a specific problem to your environment.
