### ISSUE TITLE
Strange response for beshared-repos/ listing in web API

### ISSUE THREAD

**Issue by bits4beats** [haiwen/seahub#217]
I'm testing the web API for the beshared-repos call and I found a strange response in output.

I'm usually experiencing this type of response:

```
{
    'repo_id': '27dbb493-d7ea-4d80-a7e2-0bea52dd2e86',
    'repo_name': 'test_from_t.user',
    'share_type': 'personal',
    'permission': 'rw',
    'encrypted': False,
    'enc_version': False,
    'last_modified': 1399559952,
    'repo_desc': 'test_from_t.user',
    'is_virtual': False,
    'group_id': 0,
    'user': 't.user@<domain>'
}
```

but today I found a record in the response of this type:

```
{
    'virtual_perm': None,
    'worktree_invalid': False,
    'encrypted': False,
    'origin_repo_name': None,
    'last_modify': 0,
    'no_local_history': False,
    'head_branch': 'master',
    'last_sync_time': 0,
    'id': '843912b4-ef33-4610-bbe3-0d94523112aa',
    'size': 0,
    'share_permission': None,
    'worktree_changed': False,
    'worktree_checktime': 0,
    'origin_path': None,
    'is_virtual': False,
    'origin_repo_id': None,
    'random_key': None,
    'is_original_owner': False,
    'shared_email': None,
    'enc_version': 0,
    'head_cmmt_id': 'd6a2af6d10dee324b09366824984b91bc6db4e1d',
    'desc': 'shared libreria A',
    'index_corrupted': False,
    'magic': '',
    'name': 'shared libreria A',
    'worktree': None,
    'auto_sync': False,
    'relay_id': None
}
```

It's very different for the first one and also from the online documentation: https://github.com/haiwen/seafile/wiki/Seafile-web-API#list-be-shared-libraries

The second one output is for shared libraries of other user to groups, but it seems that lacks important informations about the share (permission, group_id) and also has a complete different set of attributes compared to the first one.

Maybe these are the library listed in the "if not CLOUD_MODE:" if branch? https://github.com/haiwen/seahub/blob/master/seahub/api2/views.py#L1862

**Comment by freeplant** [comment]
This issue is obsolete.
