### ISSUE TITLE
seahub.sh custom port start option doesn't work

### ISSUE THREAD

**Issue by hnz101** [haiwen/seahub#2174]
I have just upgraded from 6.2.5 to 6.3.1 (community edition) and switched from fast-cgi to WSGI mode. I reverse proxy seahub from a different port because 8000 is already in use.

The delivered seahub.sh script states that ` start <port>` is an option and even prints:

> Starting seahub at port 1234 ...

but it doesn't

That option should be fixed or removed and mentioned to set the port in the config file conf/gunicorn.conf from now on.

Also issue #2007 could simply be solved by binding to 127.0.0.1:8000 in gunicorn.conf  instead of 0.0.0.0:8000.
Which every user can do for his own sake if he knows about the new configuration file. :-)

**Comment by shoeper** [comment]
New documentation on how to change the port has been added.

See https://manual.seafile.com/deploy/using_mysql.html#run-seahub-on-another-port
