### ISSUE TITLE
Shared link security

### ISSUE THREAD

**Issue by lavoisier16** [haiwen/seahub#218]
As largely discussed in seafile google group , better security for shared link ( download and upload link )  is really needed :

Could you add these features ( list from Matthias Wagner ) in a next release ( 3.1 , 4.0 ?)
- restrict the number of times a file can be downloaded and the number of uploads 
- restrict the validity of a shared link to a number of days or until a certain date
- let users add a personal message to the notification mail
- restrict access to a share link with password  (upload and download link)

Thanks for this great software

Regards

jcb

**Comment by shoeper** [comment]
except
>  * restrict the number of times a file can be downloaded and the number of uploads

this has been done.

**Comment by shoeper** [comment]
I don't think the number of times a file can be downloaded is ever going to come. It also can easily be quite error prone.

In the meantime the share link security has also been increased by significantly increasing it's length.
