### ISSUE TITLE
Open pdf, epub, djvu, ... files with onlyoffice

### ISSUE THREAD

**Issue by E-Wind** [haiwen/seahub#2203]
Hello!

"OnlyOffice Document Editor handles the most popular file formats", but i can't change seahub behaviour to view/edit them with OnlyOffice.

It would be great, if i could associate each file extension with editor/viewer (seahub internal, onlyoffice or other) on seahub settings page. 

Something like this:
[file extension] - [file icon] - [editor: internal | onlyoffice | ... ] - [open mode: edit | view-only]

Thank you!

https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Document-Editor/HelpfulHints/SupportedFormats.aspx

Seafile CE 6.3.2

**Comment by imwhatiam** [comment]
Hello you can custom file extension in seahub_settings.py

https://manual.seafile.com/deploy/only_office.html

**Comment by VeselaHouba** [comment]
the setting is ignored
```
ONLYOFFICE_FILE_EXTENSION = ('doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'odt', 'fodt', 'odp', 'fodp', 'ods', 'fods', 'pdf')
```
Recreated seafile docker container -> still opens in the seafile's own preview.
