### ISSUE TITLE
v6.3.2: "seafile-admin setup" error !!!

### ISSUE THREAD

**Issue by hubo-bob** [haiwen/seahub#2238]
# seafile-admin setup
…
This is your configuration
ccnet config: use existing config in /data/haiwen/ccnet
seafile: use existing config in /data/haiwen/seafile-data
Press ENTER if the config is right, or anything else to re-config
Now initializing seahub database, please wait…
Operations to perform:
Synchronize unmigrated apps: help, compressor, staticfiles, webpack_loader, messages, wopi, thumbnail, statici18n, captcha, password_session, constance, gunicorn
Apply all migrations: wiki, termsandconditions, trusted_ip, api2, share, registration, post_office, group, contacts, tags, contenttypes, profile, sessions, auth, invitations, notifications, base, revision_tag, admin_log, two_factor, database, institutions, avatar, role_permissions, options
Synchronizing apps without migrations:
Creating tables…
Running deferred SQL…
Installing custom SQL…
Running migrations:
No migrations to apply.
Your models have changes that are not yet reflected in a migration, and so won’t be applied.
Run ‘manage.py makemigrations’ to make new migrations, and then re-run ‘manage.py migrate’ to apply them.
Traceback (most recent call last):
File “manage.py”, line 10, in 
......
File “/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py”, line 1386, in names_to_path
**“Choices are: %s” % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword ‘name’ into field. Choices are: app_label, id, model, permission**

**Comment by jiangchaochao** [comment]
这个怎么被关闭了啊，怎么解决呢
