### ISSUE TITLE
Wrong version in settings.py

### ISSUE THREAD

**Issue by screendriver** [haiwen/seahub#234]
The SEAFILE_VERSION variable in [settings.py](https://github.com/haiwen/seahub/blob/master/seahub/settings.py#L387) still indicates '3.0.0'

**Comment by Almin17** [comment]
Hey guys, what happened with that bug?
I updated to the current version and when I saw 3.0.0 I became so confused I set up my seafile server from scratch, as I didn't realize it's a bug. I just realized it after finally having it set up again and still having version 3.0.0 showing. It would be great if that bug would be fixed.

**Comment by shoeper** [comment]
Don't think that arch package is official. Ask the maintainer to fix it. Official Seafile tars work well and show the right version.
