### ISSUE TITLE
Anti-CSRF tokens set without using the SameSite flag

### ISSUE THREAD

**Issue by aelisya** [haiwen/seahub#2367]
Hello i implement different services, but when i would like test seafile with observatory, i have this error

Cookies |   | -20 | Anti-CSRF tokens set without using the SameSite flag

There is a way to fix it (i don't use the web version of seafile only software), (if the fix break the http version is not important to me

Thanks in advance

**Comment by omkarnathsingh** [comment]
Hi, you can put following in your nginx configuration for location '/' : 
**proxy_cookie_path / "/; secure; SameSite=strict";**

I had used the results of that website and fixed all issues for me.
