### ISSUE TITLE
[Feature] allow collaborative edition on web interface

### ISSUE THREAD

**Issue by cjeanneret** [haiwen/seahub#24]
Hello,

It may be really useful and great to do something like Etherpad on the web interface. Etherpad allows multiple persons to edit the same file through the web interface.
It also saves revisions on the fly, meaning:
- never lose modification (as it's saved in real-time)
- possibility to go back and forth in time, live

I'm pretty sure this won't be done in the next release - but, please, keep this feature in mind for the future :).

Thank you!

**Comment by freeplant** [comment]
This issue is obsolete.
