### ISSUE TITLE
Email registration domain whitelist

### ISSUE THREAD

**Issue by QwertyJack** [haiwen/seahub#2420]
I would suggest to add a filter for email domain of registration.

**Comment by freeplant** [comment]
We don't have plan to add this feature.

**Comment by QwertyJack** [comment]
I think this very useful when I want to build a semi-public seafile server. 
The circumstance is:
* i have a public server and want to build a seafile for my team;
* the seafile server is not public, because I do not want everyone on internet sharing my storage;
* there are many users in my team, so it takes me lots of time to add each user's email by hand.
If there is a domain whitelist, such requirements would be easily satisfied.
