### ISSUE TITLE
Performance issue with large number of groups

### ISSUE THREAD

**Issue by odontomachus** [haiwen/seahub#2463]
When there are thousands of groups, group creation in the API slows down significantly.

## Group creation
The API gets all groups using ccnet to look for name conflicts, then adds the group if there is no conflict.
Using `ccnet_api.search_groups(new_group_name, -1, -1)` fixes the performance issue.

![group_add](https://user-images.githubusercontent.com/1121343/47212983-f8a7be80-d399-11e8-9761-35a11da02f88.png)

## Group listing
The takes ~30 seconds to list a user's groups when they have 14000 groups.

**Comment by odontomachus** [comment]
Also, this can probably be merged into master too, but I wasn't able to get master to run at that time.

**Comment by shoeper** [comment]
I think @imwhatiam could have missed that it would be merged in 6.3 instead of master.

**Comment by imwhatiam** [comment]
Will be fixed in the next release
