### ISSUE TITLE
Public share link page name ordering

### ISSUE THREAD

**Issue by TakeMeNL** [haiwen/seahub#2483]
Atm moment if you have photos which are in sequence from 1 to 100 the ordering is not humanly logic.
![image](https://user-images.githubusercontent.com/980978/47672465-5b773200-dbb2-11e8-93d3-1988736f5624.png)

This is only on the shared link page because logged in it normal
![image](https://user-images.githubusercontent.com/980978/47672564-a6914500-dbb2-11e8-86d8-e6a73e38df56.png)

**Comment by shoeper** [comment]
https://github.com/haiwen/seafile/issues/1694

**Comment by TakeMeNL** [comment]
Ah well explains why i didn't find anything in this project related to this issue. Thanks for linking.  
Hope it will be changed because 3000 photos in this order is only chaos/
