### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by omkarnathsingh** [haiwen/seahub#2498]
What is difference between a vxxx-pro and vxxx-server in the release section of this project? Whichis to be used for stability? Thanks.

**Comment by shoeper** [comment]
Tags are just for the versions released. So v6.3.6-pro is the state that is included in the pro release 6.3.6 and -server releases are from community edition releases.

Also the title of your query is quite bad as it doesn't say anything about what you want.

**Comment by omkarnathsingh** [comment]
Thanks for reply. 🤗
