### ISSUE TITLE
user cannot set avatar

### ISSUE THREAD

**Issue by allefeld** [haiwen/seahub#2499]
When trying to set the avatar image from a user's settings page, an error message appears:

> Page unavailable
> Sorry, but the requested page is unavailable due to a server hiccup.
> 
> Our engineers have been notified, so check back later.

The server is running and reachable, and all other functionality shows no problems.

Server Version: 6.2.5 (Community Edition)

**Comment by freeplant** [comment]
This is caused by the python image library can't handle jpeg format. You can install the correct library via `pip install Pillow==4.3.0`

**Comment by allefeld** [comment]
It also happens with a png image...
