### ISSUE TITLE
Configure seahub to use mail command instead of SMTP

### ISSUE THREAD

**Issue by pkbarbiedoll** [haiwen/seahub#262]
Is there a way to configure seahub to use the server `mail` command as opposed to using a personal email account for sending system messages via SMTP?   I'm not comfortable storing my email password on the server for one, and two - it changes monthly.   

Apologies if this is covered in https://github.com/haiwen/seahub/issues/261 (email documentation returns 404 not found).

**Comment by freeplant** [comment]
We don't want to support this feature.
