### ISSUE TITLE
[Feature] suggestion to add option to limit to create 'group' by a normal user

### ISSUE THREAD

**Issue by darkcircle** [haiwen/seahub#263]
sometimes, admin wants to control whole system to prevent to create some group by a normal user in disorder.

maybe, adding a this feature is so simple, I think, as just check who is a normal user or an admin and 'hide' "new group" button and block to access 'group creation' window.

Thank you for considering trivial feature in advance.

**Comment by freeplant** [comment]
This feature has been implemented in the 6.0 pro edition.
