### ISSUE TITLE
[Feature] ZIP Packing Info

### ISSUE THREAD

**Issue by iBigQ** [haiwen/seahub#267]
Hey,

I often use directory links to share files via seahub. As the directory size raises, preparing the zip archive for download takse some seconds. Currently the webpage does not give any feedback to the user while the dir is zipped.
I suggest to add a simple overlay box when starting a download informing the user that the archive will be provided as soon as created. It would be nice to include an animation (e.g. a circle) to "signaling" the user that the server is working on the request.

**Comment by iBigQ** [comment]
+1 In many scenarios (like a new document version to share) a certain zip is requested frequently. Caching is an awesome performance boost here

**Comment by shoeper** [comment]
Recently someone pointed out somewhere the ability to generate zip files without compression on the fly. I think that would be the best solution because there wouldn't be any waiting time at all.

**Comment by lins05** [comment]
To serve the zip request in a streaming manner, we need to investigate whether libarchive (the library we use to generate zip archives) supports this style of usage, and use http `transfer-encoding: chunked` feature to send the streaming response.

**Comment by freeplant** [comment]
This feature is implemented in the latest version.
