### ISSUE TITLE
DEBUG=True: CE 6.3.4 hangs when opening a library / loggin in

### ISSUE THREAD

**Issue by jh23453** [haiwen/seahub#2706]
We have two things where DEBUG=True isn't working for people.
https://forum.seafile.com/t/memcache-issue-with-debug-true/7211
and
https://forum.seafile.com/t/seafile-server-6-3-3-is-ready-the-new-wiki-feature-is-ready/7105/9

I've tracked the second one down to /seahub/seahub/templates/libraries.html.
At the end we have two vastly different main.js files.  The following patch fixes it for me:
```
--- seahub/templates/libraries.html.orig        2018-12-24 06:04:16.461908440 +0100
+++ seahub/templates/libraries.html     2018-12-24 06:04:45.113623934 +0100
@@ -313,9 +313,5 @@
     freezeItemHightlight: false
 };
 </script>
-{% if debug %}
-<script data-main="{% static "scripts/main.js" %}" src="{% static "scripts/lib/require.js" %}"></script>
-{% else %}
 <script data-main="{% static "scripts/dist/main.js" %}" src="{% static "scripts/lib/require.js" %}"></script>
-{% endif %}
 {% endblock %}
```
I'm unsure what to do, because the files are so different. What's the reason for this?
I'll try and dig in the history.

I think it broke with this commit:
https://github.com/haiwen/seahub/commit/f1662718278f4c6cfca2414955ca151672763707

**Comment by xiez** [comment]
Hi, this issue is fixed in https://github.com/haiwen/seahub/commit/2ffb69b6317b52b9e23aeaecf00a43eda6711e35 which will be included in next version.

In addition, you can also add `COMPRESS_ENABLED = True` to seahub_settings.py which is same as your patch.

**Comment by shivno** [comment]
thanks for the fix! maybe put this into release notes, sadly i didnt found this bug timely and spend 3 hours, trying multiple releases and debugging react, did the migration over and over

**Comment by shivno** [comment]
release notes of 6.3.3 and 6.3.4 in the wiki or changelog
