### ISSUE TITLE
Minor UI improvement: When Updating a file, the Drag & Drop notice label should be shown as well

### ISSUE THREAD

**Issue by yeah** [haiwen/seahub#274]
see difference between these screenshots:

upload:

![iso_images - private seafile 2014-09-02 17-16-51 2014-09-02 17-16-52](https://cloud.githubusercontent.com/assets/2181/4120693/4770b98a-32b4-11e4-9b14-5efd2eb2e74f.png)

update:

![iso_images - private seafile 2014-09-02 17-16-31 2014-09-02 17-16-32](https://cloud.githubusercontent.com/assets/2181/4120692/461f125c-32b4-11e4-8de2-ac1c12bf97ff.png)

(The notice "1. Drag & Drop is supported for Chrome, Safari..." is missing, but would make sense here.)

**Comment by freeplant** [comment]
This issue is obsolete.
