### ISSUE TITLE
Web API: Library rename does not work

### ISSUE THREAD

**Issue by alecpl** [haiwen/seahub#286]
The request returns "success", but the new name is not updated.

POST: https://seacloud.cc/api2/repos/ad027f0e-de78-485a-8c2a-4b766d216833/, POST: {"op":"rename", "repo_name":"newname","repo_desc":"test"}
Response [200]: "success"

Is this a bug or am I doing something wrong?

**Comment by freeplant** [comment]
This issue has been fixed in the latest version.
