### ISSUE TITLE
[UI] Simplify share sections under "Files" / merge "shared for me" and "shared with groups"?

### ISSUE THREAD

**Issue by r4dh4l** [haiwen/seahub#2923]
Hi,

I can imagine the purpose of separating "shared with me" and "shared with groups" but some of my users reported that this separation is not very helpful finding a share because after a while and with a lot of shares you don't remember if a share was created by you or not.

What about the following separation of section "Files":

- My Libraries
- Shares (overview listing _everyhing_ that is shared by or for me/groups)
-- Shared by me (listing shares owned by me)
--- Shared with user(s)
--- Shared with groups
-- Shared with me (listing shares not owned by me)
--- As user share
--- As group share

**Comment by freeplant** [comment]
We don't have a plan to change it as many users already familiar with the old way.
