### ISSUE TITLE
CSRF token missing or incorrect. Apache reverse proxy.

### ISSUE THREAD

**Issue by wayofka** [haiwen/seahub#2924]
Get error  `CSRF Failed: CSRF token missing or incorrect`   in web access (seahub) for deleting (and some other actions).

Enviroment :
Seafile 6.3.4 CE, settings by documentation
Apache 2.4 as reserve proxy (https), settings by documentation
Linux centos 7.6
Android client works fine (upload, download, delete). 

Web access (seahub) works partially, tested with Firefox and Chromium with same result
Login, upload, download etc works fine.
Delete, Share, Empty Trash fail with browser error CSRF Failed: CSRF token missing or incorrect.  
Log seahub.log with warning ` django.security.csrf:160 _reject Forbidden (CSRF token missing or incorrect.)`
Apache log with  403 forbidden  `"DELETE /api/v2.1/repos/xxxxxxxxx/file/?p= HTTP/1.1" 403`
probably related to issue [https://github.com/haiwen/seahub/issues/1781](https://github.com/haiwen/seahub/issues/1781)  and this [https://forum.seafile.com/t/solved-403-forbidden-after-upgrade-to-6-3-1/6525/7](https://forum.seafile.com/t/solved-403-forbidden-after-upgrade-to-6-3-1/6525/7)

Inspecting headers show that cookies was correctly set, sfcsrftoken and sessionid, try many different apache settings with same result. According to [https://github.com/haiwen/seahub/issues/1781](https://github.com/haiwen/seahub/issues/1781) i try workaround to set manualy X-CSRFToken in header to same value as cookie sfcsrftoken, which works.
My workaround is to add these lines to Apache configuration (it sets header X-CSRFToken to same value as cookie sfcsrftoken)

    SetEnvIf Cookie "(^|;\ *)sfcsrftoken=([^;\ ]+)" MyCookieValue=$2                                                                                                                      
    RequestHeader set  X-CSRFToken "%{MyCookieValue}e"   

Maybe the problem is in my apache setup and I spent several's hours to find this workaround, posting just for case if someone other have this problem.

**Comment by Jvheaney** [comment]
Worked great!

**Comment by jurwol** [comment]
Great workaround, you made my day!

**Comment by ulyssejdv** [comment]
my day too
