### ISSUE TITLE
Virtual disk, user , deleted files

### ISSUE THREAD

**Issue by echwell** [haiwen/seahub#293]
Hi, I have three questions:
1) when installing the windows client , you could create the library's virtual disk and that's ok, but when you create or delete  a library the disks are not updated. It's not possible to make the process automatic, like when you create a new library a new disk is created or when you delete an old library the disk is deleted?
2) when the administrator of a group receives a request from a user must add him or her with the mail and not directly from the popup. There isn't any page with all the request of users that would like to be added?
3)How could I delete the files inside the trash? 
I really appreciate any help you can provide.

**Comment by freeplant** [comment]
This issue is obsolete.
