### ISSUE TITLE
Bug with ForceSave and OnlyOffice

### ISSUE THREAD

**Issue by salleman33** [haiwen/seahub#2957]
Hi, 

I have a problem with the "forceSave" functionnality of OnlyOffice.
my test is : 
- User A open a file in OnlyOffice, makes some change and use the forceSave functionnality
- User B open the same document
result :  UserB is not on the same instance of OnlyOffice document that User A

I think the problem comes from the "doc_key" id. OnlyOffice API documentation says  : 

> Defines the unique document identifier used for document recognition by the service. In case the known key is sent the document will be taken from the cache. Every time the document is edited and saved, the key must be generated anew. The document url can be used as the key but without the special characters and the length is limited to 20 symbols.

I suppose that user B is on a new instance because doc_key changes. In the onlyoffice callback, the key_doc id have to not  change when the status is 6 (forceSave), but only if status is 2 (really save when all users leave onlyoffice document)

Regards

**Comment by freeplant** [comment]
This is a known problem. It is a restriction of OnlyOffice. I suggest you to not use 
forceSave option.

**Comment by odontomachus** [comment]
Sorry to comment on a closed issue. How about using a fixed doc key while there is a collaborative editing session?

https://github.com/odontomachus/seahub/tree/feature_onlyoffice_sessions
