### ISSUE TITLE
OAuth redirect after login

### ISSUE THREAD

**Issue by ak0ska** [haiwen/seahub#2977]
Hello,

The current OAuth implementation has some limitations: it ignores the link the user used to arrive on Seahub.

If someone shares a link to a file in Seahub, and the user visiting the link is not yet authenticated, then after the OAuth2 authentication the user is [directed back to the Seahub main page](https://github.com/haiwen/seahub/blob/master/seahub/oauth/views.py#L236) instead of keeping track of the link the user arrived with and redirecting him/her to the appropriate file. As a result the user has to copy the link in the address bar a second time.

Kind regards,
Akos

**Comment by freeplant** [comment]
Fixed in https://github.com/haiwen/seahub/pull/3296
