### ISSUE TITLE
Problems using Seahub on non-root domain

### ISSUE THREAD

**Issue by ns130291** [haiwen/seahub#300]
I have some problems using seahub 3.1.5 with a non-root domain.

If I set the `SITE_ROOT = '/seafile/'` and then go to `mydomain.com/seafile` the error message `Sorry, but the requested page could not be found.` appears. If I then manually add another `/seafile` at the end of the URL it tries to redirect to `mydomain.com/seafile/accounts/login` which also fails, as there is also missing the additional `/seafile`. So by changing the URL to `mydomain.com/seafile/seafile/accounts/login` it finally loads the login page. After logging in it redirects again to the wrong URL without the addtional `/seafile`. Adding again the `/seafile` fixes it again and you finally get to `mydomain.com/seafile/seafile/home/my/`. On that page most of the links are right, but there are some exceptions: the seafile logo, `My Home` and `Help`.
On the admin page most links are wrong.

Is this behaviour fixed in a later version?

**Comment by rdsqc22** [comment]
This seems to work fine for me.

Initially I had a problem just like the one you described, but then I saw this issue, and saw your seahub_settings .py. Mine has only contained this:

    FILE_SERVER_ROOT = 'https://www.mydomain.com/seafile'

I modified to contain:

    FILE_SERVER_ROOT = 'https://www.mydomain.com/seafile'
    
    SERVER_STATIC = False
    MEDIA_URL = '/media/'
    SITE_ROOT = '/seafile/'

And now it works as expected.
