### ISSUE TITLE
在资料库内打开md文件, 无法显示资料库内图片的bug及解决方案.

### ISSUE THREAD

**Issue by genrwoody** [haiwen/seahub#3072]
在seahub/views/file.py文件的convert_md_link函数中,
```python
return '<img class="wiki-image" src="%s" alt="%s" />' % (gen_file_get_url(token, filename), filename)
```
这一句代码, 由于前端js把md转为html时用正则校验了无效标签, 校验图片的正则表达式顺序校验了src, alt, class, 但是在这里class在第一个, 所以导致无法通过校验, 认为这是无效标签, 所以这一句应修改为:
```python
return '<img src="%s" alt="%s" class="wiki-image" />' % (gen_file_get_url(token, filename), filename)
```
另外, 不建议修改js文件, 因为wiki中也有类似代码, 如修改js需连同wiki的utils.py一同修改.

**Comment by freeplant** [comment]
7.0 版本会使用新的 Markdown 查看器。不会有这类的问题。
