### ISSUE TITLE
Wrong paths, for non-default SITE_ROOT and MEDIA_URL

### ISSUE THREAD

**Issue by allo-** [haiwen/seahub#313]
I deployed seafile with `MEDIA_URL=/seahub-media/`, but the default avatar still uses `/media/avatars/default.png`.

While searching for the source of the other /media/ path, i found

`<img src="https://cloud.seafile.com/media/img/seafile_logo.png" alt="" />` with hardcoded path in `seahub/seahub/templates/file_edit.html`

`window.location.href.replace(/\/repo\/[-a-z0-9]{36}\/.*/, '/media/cors/result.html?%s')` in `seahub/seahub/templates/repo.html`

**Comment by freeplant** [comment]
This issue is obsolete.
