### ISSUE TITLE
Hyperlinks in PDF files are not working

### ISSUE THREAD

**Issue by rabb1t** [haiwen/seahub#3248]
Hi, I've noticed that all hyperlinks in PDF documents are not working (not clickable at all) in seahub (**v6.3.13-pro**, **v7.0.0-pro beta** releases).

You can open PDF file attached below to ensure that hyperlinks are working properly with default pdf.js library:
https://mozilla.github.io/pdf.js/web/viewer.html

To ensure that this document has a legal URIs you can browse its contents here:
https://brendandahl.github.io/pdf.js.utils/browser/

I've also attached the screenshots and PDF file which are used in this example:

- PDF file:
[IBM_3650_m2_XSD03036RURU.PDF](https://github.com/haiwen/seahub/files/3069340/IBM_3650_m2_XSD03036RURU.PDF)

- PDF contents:
![pdf_obj_browser](https://user-images.githubusercontent.com/3540843/55968951-a62ec700-5c85-11e9-8db4-9e064a982702.png)

- Mozilla's pdf.js rendering:
![out](https://user-images.githubusercontent.com/3540843/55968856-7b447300-5c85-11e9-95e9-dffbd9c957fb.png)

- Seahub's pdf.js rendering:
![seahub](https://user-images.githubusercontent.com/3540843/55969715-f5c1c280-5c86-11e9-9a77-e74416bef8db.png)

Can you fix this problem?
Thank you.

**Comment by freeplant** [comment]
Fixed in https://github.com/haiwen/seahub/pull/3257
