### ISSUE TITLE
The shared_link_email not full translated - seafile version 4.0.2

### ISSUE THREAD

**Issue by lavoisier16** [haiwen/seahub#328]
hi
In the message sent when a user share a file or a directory,   the variable  %(file_shared_type)s is not translated and the words file, directory .. stay in english 

example 1
Bonjour,

xxx@gmail.com a partagé un file aaaaaaaaaaaaaa.odt sur BOX-Seafile:
https://192.168.1.10/f/0eecb590c3/

Merci d'utiliser notre site !

L'équipe de BOX-Seafile.

example 2

Bonjour,

xxxx@gmail.com a partagé un directory eeeeeeeeeeeeeeeeee sur Seafile:
https://192.168.1.10/d/a82e9e0e1a/

Merci d'utiliser notre site !

L'équipe de Seafile.

**Comment by lavoisier16** [comment]
same issue with version 4.0.5

**Comment by freeplant** [comment]
This issue is obsolete.
