### ISSUE TITLE
seafile-server-4.0.2 seahub/views/file.py

### ISSUE THREAD

**Issue by lavoisier16** [haiwen/seahub#329]
hi
The error message  " this type of file cannot be viewed online" in file .py (line 304) is not translated and stays in english 
![screenshot - 29122014](https://cloud.githubusercontent.com/assets/7565826/5569132/2078938e-8f6b-11e4-9760-bf4e65d6bcc6.png)

**Comment by lavoisier16** [comment]
same minor issue with seahub version 4.0.5

**Comment by shoeper** [comment]
afaik you can fix translation issues via transifex

**Comment by freeplant** [comment]
OK. It may be not marked as for translation.

**Comment by freeplant** [comment]
This issue has been fixed in the latest version.
