### ISSUE TITLE
Shared folders displayed as shared libraries ( seafile 4.0.3 i386 )

### ISSUE THREAD

**Issue by lavoisier16** [haiwen/seahub#330]
hello,
Using seafile server 4.03 i386 installed from scratch. 
Folders shared by user A to user B are displayed in "Share admin" -> Libraries instead of "Share Admin" -> "Folders" 

Eveything ok with seafile-server-4.0.3 x64

**Comment by lavoisier16** [comment]
same issue with seafile-server-4.0.5 i386

**Comment by freeplant** [comment]
The problem is reported by some users. But we are unable to reproduce the problem.

**Comment by freeplant** [comment]
This issue is obsolete.
