### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by iBigQ** [haiwen/seahub#332]
The german translation for "Download" doesnt make sense. Currently in 4.0.3 it is translated to "Öffentlich teilen". Please rollback to the old translation: "Herunterladen"

**Comment by HenriWahl** [comment]
Or just name it 'Download' - meanwhile this term should be known worldwide.

**Comment by SiljaJ** [comment]
You're right. I messed that up while trying to improve the translations. We're going to go back to the old version.

**Comment by shoeper** [comment]
"Herunterladen" would imho be the best translation

**Comment by dervomsee** [comment]
You can take my PR:
https://github.com/haiwen/seahub/pull/334

**Comment by Tischi86** [comment]
Or my PR without a typo ;) https://github.com/haiwen/seahub/pull/341

**Comment by SiljaJ** [comment]
We handle translation through Transifex. We fixed that issue there and the corrected translation will be in the next release. Thanks for you PRs, though (with and without typos ;-)) and sorry for all the confusion...
