### ISSUE TITLE
change user email

### ISSUE THREAD

**Issue by jc06700** [haiwen/seahub#340]
Transfered from seafile issue (https://github.com/haiwen/seafile/issues/1011)

A new idea/feature ? 
The possibility to change user email 
(either from the user interface or from the admin user settings)

**Comment by voloder** [comment]
That would be great and useful.

**Comment by mcfly** [comment]
i understand this is a open request to do so? Are there any ways to actually change a user's email?

**Comment by jc06700** [comment]
You must change/replace manually all references in your databases

- ccnet-db
EmailUser
UserRole       

- seafile-db
RepoOwner
RepoUserToken 

- seahub-db
api2_tokenv2 
avatar_avatar 
base_clientlogintoken
base_userlastlogin 
notifications_usernotification 
options_useroptions 
profile_detailedprofile 
profile_profile 1

Regards

**Comment by vmario89** [comment]
it's a shame that changing email address for users is not available yet by using GUI.

**Comment by vmario89** [comment]
i am using SQlite and changed by hand many files with absolutely zero effect:

- config.db
- groupmgr.db
- seafile.db
- seahub.db
- usermgr.db

i changed all email addresses of the user to the new mail but account login still only worked with old email. restarting seafile/seahub did not change it. restarting whole system with same less effect.

**Comment by freeplant** [comment]
In version 6.2, you can change a user's reference ID. You can set a user's reference ID to a new email address. And user can use this new email to login.

**Comment by vmario89** [comment]
hello,
i installed 6.2.3 and there's no edit button for email address:
![grafik](https://user-images.githubusercontent.com/5631071/35195841-960be67a-fec9-11e7-8b5c-e96c3d3c5dad.png)

**Comment by jc06700** [comment]
> From version 6.2, you can change a user's reference ID ...

Just updated to seafile-server-6.2.4
It Works perfectly
Indeed, admin can set an ID for users. So that user can login with the ID, instead of email.

I also do like a new feature : the 2 authentication factor.
Very great job. Congrats to Seafile Team.
The tool is better every release !

**Comment by vipera7** [comment]
Still no way to update user email ?

**Comment by jc06700** [comment]
As freeplant said 
--
From version 6.2, you can change a user's reference ID. You can set a user's reference ID to a new email address. And user can use this new email to login. The admin can set a user's reference ID in the web UI.
--
So users can login with their new email

**Comment by gtmadev** [comment]
> ## As freeplant said
> ## From version 6.2, you can change a user's reference ID. You can set a user's reference ID to a new email address. And user can use this new email to login. The admin can set a user's reference ID in the web UI.
> So users can login with their new email

That's fine... but what happens if a user who owns that email address tries to request a password reset with the email address? Will they be able to reset the password if they receive the email? I think that is what is concerning people with this inability to change that email address.
