### ISSUE TITLE
Shares needs to be sent on the behalf of the sharer !

### ISSUE THREAD

**Issue by NNois** [haiwen/seahub#342]
Hi,
Wen a user share a file, this is sent on the behalve of the admin email account, so 3 possible problems here.
- The client don't ever know the sender (system set admin email account) so it's spam filtered or similary just not read
- The client respond to this email and this goes in a black hole (as it's the system set admin account ...)
- Simply the sender don't whant to send a file on the name of another person

**Comment by freeplant** [comment]
You can change the behavior by adding the following to seahub_settings.py:

```
# Replace default from email with user's email or not, defaults to ``False``
REPLACE_FROM_EMAIL = True

# Set reply-to header to user's email or not, defaults to ``False``. For details,
# please refer to http://www.w3.org/Protocols/rfc822/
ADD_REPLY_TO_HEADER = True
```

**Comment by NNois** [comment]
Hi,
In fact it's working for the "reply-to" but not for the sender who is always displayed as the $EMAIL_HOST_USER.

If you look at gmail/yahoo first collum, for us it's always "admin"(for admin@myseafile.com) and not the "real" sender, it's a real problem...

What is the correct settings to solve this ?

**Comment by shoeper** [comment]
Many mail servers do not allow to sent from any sender. Reply-to header or an own mail server set up to allow sending in anyones name is the only solution.
