### ISSUE TITLE
feature request: plugins

### ISSUE THREAD

**Issue by shoeper** [haiwen/seahub#345]
It would be very nice if one could easily write plugins for seahub. I think there are many people out able to write plugins and this would allow the use of seafile for many more use cases.
For example people using it for their family could use a gallery plugin. A company could easily add a plugin for management purposes or one wanting to make a public cloud could integrate his homepage in seahub and so on.

**Comment by miurahr** [comment]
:+1: 
One possibility to support more file type for preview.

**Comment by shoeper** [comment]
Ok I close this and we move discussion to #92
