### ISSUE TITLE
Wrong version in webinterface

### ISSUE THREAD

**Issue by MichiDoe** [haiwen/seahub#347]
I use the binaries from github for my seafile installation running on Arch LInux. In the ./seahub/settings.py the variable "SEAFILE_VERSION" contains the value '3.0.0'.
So the Webinterface is showing the wrong version.
Could you use the tag instead?

**Comment by xiez** [comment]
Thanks @MichiDoe , it's fixed in https://github.com/haiwen/seahub/commit/e495ff60de03840d24c3adb9b94f3219a702a189.

**Comment by ScreenDriver** [comment]
See also here #234
