### ISSUE TITLE
Regression: no grid view for shared links

### ISSUE THREAD

**Issue by sebastianlipponer** [haiwen/seahub#3665]
I upgraded from 6.3.4 to 7.0.2 recently. Unfortunately, with 7.0.2 the grid view option for shared links is gone.

**Comment by freeplant** [comment]
It will be fixed in the next release.

**Comment by jobenvil** [comment]
Hi @freeplant , when do you expect approximately to release the new release? :-)

**Comment by freeplant** [comment]
A new version will be released before July 5th.
