### ISSUE TITLE
Allow disabling public (all) shares independently of cloud_mode

### ISSUE THREAD

**Issue by vangual** [haiwen/seahub#368]
Please add an option to seahub_settings.py to disable sharing to "all" even when not using cloud_mode.

We use seafile in corporation mode and the functions of cloud_mode wouldn't fit. However we regularly have people that for whatever nonsense reason share libraries to "all", raising questions amongst the other users in the entire corporation.

**Comment by freeplant** [comment]
Do you want to prevent all users from sharing to "all"?

**Comment by vangual** [comment]
Yes that's what I had in mind. Just disabling the "all" functionality for all users with a switch, like cloud_mode does (just without all the other cloud_mode behavior changes).

**Comment by freeplant** [comment]
There is an option to prevent normal users to share libraries to all now.
