### ISSUE TITLE
Feature request: Offer to revoke a device and delete its data

### ISSUE THREAD

**Issue by mathieu-mp** [haiwen/seahub#373]
We currently have a device browser and the ability to "unlink" a device (it just stops syncing).

Feature: In case of a stolen notebook, could you offer the ability to "revoke" a device, the hard way, deleting all device data in synced libraries if this device ever tries to connect back.
Bonus 1: offer the ability to name a device in the current Device browser
Bonus 2: keep track of IPs for each connection attempt of a revoked device & offer to send mails when device attempts to connect
Bonus 3: give the administrators the right to disable the revoke feature (if people feel bad about it)

Would be great, thanks.

**Comment by shoeper** [comment]
Problem with this would be that the data isn't away on delete (people wanting to get it will easily get the data). Better would be just enabling Bitlocker (or some other encryption tool).
So in my optionion it would be enough to just revoke access to seafile for that device (for browser and client). And an option to name devices would of course be helpful therefor.

**Comment by mathieu-mp** [comment]
I get you, it cannot be considered as a complete protection. 
But it might do the job for a newbie thief, connecting to his wifi before even trying to duplicate data, it would just hide data from "innocent" eyes.

**Comment by freeplant** [comment]
Added in version 6.0.
