### ISSUE TITLE
Client_version field in the  api2_tokenv2 table in the seahub-db doesnt get updated when client gets upgraded

### ISSUE THREAD

**Issue by acavas1** [haiwen/seahub#377]
Hi,

server version: windows seafile server 4.0.6

client_version filed in the api2_tokenv2 table in seahub-db doesnt get updated when client gets updated. 
Client version is important so we could know what version of the client is used to access the server, so we could keep the client on the latest or the most stable version or alert users if they are using an untested version of the client.

It would be great if the client could trigger client version field update on a first connection to the server after client upgrade. Then the server would not have to check for the client version on every client connection.

Please add this feature the the new version of the Seafile server.

Best regards

**Comment by freeplant** [comment]
It should have been fixed in latest releses.
