### ISSUE TITLE
Drag and Drop in IE with 7.0.5 doesnt't work

### ISSUE THREAD

**Issue by Vurgus** [haiwen/seahub#3815]
In the version 7.0.2 and 7.0.3 I have problems with the drag and drop feature in Internet Explorer.
There are errors in JavaScript console and the result is, that the upload stucks on 0%. The version of IE is 11.0.100.

Error in JavaScript console:
![grafik](https://user-images.githubusercontent.com/4215563/60773164-ba0d8c00-a101-11e9-9ace-e32e49a54511.png)

Error in JavaScript Code:
![grafik](https://user-images.githubusercontent.com/4215563/60773169-d7daf100-a101-11e9-9e73-90ddc30eafb1.png)

Upload which stucks on 0%:
![grafik](https://user-images.githubusercontent.com/4215563/60773171-e88b6700-a101-11e9-9edc-c7eb9be6deb5.png)

Has somebody the same problem?
I checked some other seafile server instances with the version 7.0.2 and 7.0.3 and there are the same behavior.

**Comment by Michael18811380328** [comment]
Oh, it is a tough problem that codes can't work well in different browsers, such as IE and other browser. Seafile can work well in Chrome/FireFox/Safari(You can try other browser now). Recently these problems will be fixed.

**Comment by huegelc** [comment]
Same issue with FF 68.0.1 on Mac. Safari no probs

**Comment by Michael18811380328** [comment]
Thanks again. We will check and fix it soon(IE and FF).

**Comment by Vurgus** [comment]
Today I updated to version 7.0.5
In Firefox it is fine, but in IE is still the upload problem:
![grafik](https://user-images.githubusercontent.com/4215563/65673389-073b3300-e04b-11e9-8558-e983f1b24d84.png)
![grafik](https://user-images.githubusercontent.com/4215563/65673524-3782d180-e04b-11e9-99d6-4c78845bc9c9.png)
If you need more informations, feel free to contact me.

**Comment by freeplant** [comment]
It should have been fixed in the latest release.
