### ISSUE TITLE
Clients overview does not display synchronized libraries if connecting via HTTP

### ISSUE THREAD

**Issue by HenriWahl** [haiwen/seahub#390]
Hi,
aside noticing that your new HTTP sync works great I found that at the clients overview page in seahub the synchronized libraries are not shown as they are for old-style connected clients. This would be a minur problem, but does this mean that one cannot disconnect clients?
Best regards
Henri

**Comment by freeplant** [comment]
We are working on fix the problem.

**Comment by HenriWahl** [comment]
Thanks!

**Comment by freeplant** [comment]
In the latest version, Seafile doesn't display the list of synced libraries. Because we think this information is useless.
