### ISSUE TITLE
Seafile Web API "Copy file" returns 500 when "p" (parent directory) does not exist

### ISSUE THREAD

**Issue by warrenseine** [haiwen/seahub#391]
Hi,

500 is supposedly a server error, something the user can't do much about. When the destination directory doesn't exist, the user could act upon the error by creating it for instance.

I suggest this API returns a 403 and forwards the RPC error message sent by Seafile ("SearpcError: Path does not exists" — there's a typo in the error message by the way) to the client.

At the very least, it should be mentioned the error code 500 in the API documentation (currently referred as 502 which sounds completely invalid).

Regards,
Warren.

**Comment by freeplant** [comment]
@imwhatiam

**Comment by warrenseine** [comment]
Same problem with the upload API if the parent directory does not exist.
