### ISSUE TITLE
Download a library

### ISSUE THREAD

**Issue by jeremejevs** [haiwen/seahub#392]
In my case, I want to be able to download a shared directory. Right now it's treated as a library, so there's no download button in the interface, but if I just append the ID to `/seafile/repo/download_dir/`, then I'm able to download even raw libraries.

My current workaround is to add the following to repo buttons in `my_owned_repos.html`:

``` html
<a href="{% url 'repo_download_dir' repo.props.id %}" class="repo-download-btn op-icon vh" title="{% trans "Download" %}">
  <img src="{{MEDIA_URL}}img/download.png" alt="" />
</a>
```

And then a slightly different version to repo buttons in `my_shared_repos.html` and `my_group_repos.html`:

``` html
<a href="{% url 'repo_download_dir' repo.repo_id %}" class="repo-download-btn op-icon vh" title="{% trans "Download" %}">
  <img src="{{MEDIA_URL}}img/download.png" alt="" />
</a>
```

It would also be nice to have a big download button inside directories, like this one, added to top bar buttons in `repo_dir_data.html`:

``` html
<button onclick="location.href='{% url 'repo_download_dir' repo.id %}?p={{ path|urlencode }}'" class="op-btn">
  <span class="icon-download"></span>
  {% trans "Download"%}
</button>
```

**Comment by freeplant** [comment]
We don't have a plan to implement such feature.
