### ISSUE TITLE
Shibboleth authentication always resets admin flag

### ISSUE THREAD

**Issue by neffs** [haiwen/seahub#394]
Bug: If I enable Shibboleth, admin users instantly lose their permissions (is_staff) when accessing Seahub.
I tried setting up Shibboleth with LDAP as a backend. Some Admin Accounts are also in MySQL. 

There is some dead code in here:
https://github.com/haiwen/seahub/blob/master/thirdpart/shibboleth/backends.py
Essentially create is always called, overriding the is_staff flag.

**Comment by lins05** [comment]
For each user that logs in through shibboleth, we create a special password-less user in the database (so that the user can not login in a normal way).  So are you suggesting we should check if there is a database user already, before create a special user? It makes sense to me. @freeplant @xiez

**Comment by neffs** [comment]
Yes. This would also allow to assign the admin flag to shibboleth users. The password gets deleted here, so the behavior would still be the same (at least with SQL users): 
https://github.com/haiwen/seahub/blob/master/thirdpart/shibboleth/middleware.py

**Comment by freeplant** [comment]
In version 4.1, we have redesigned the way to login via shibboleth. Can you give it a try? Document is here: http://manual.seafile.com/deploy/shibboleth_config.html

In the new way, only the login page need to be configured using shibboleth.

**Comment by neffs** [comment]
Now it works great. Thank you very much!
