### ISSUE TITLE
Usermenu on the wrong side in System Admin

### ISSUE THREAD

**Issue by huegelc** [haiwen/seahub#3943]
seafile-server-7.0.4

In System Admin the Usermenu is on the left side leading to an unreadable dropdown menu

<img width="485" alt="grafik" src="https://user-images.githubusercontent.com/6955465/62390863-97855c00-b563-11e9-8e8d-1fd9216a8ce7.png">

**Comment by Michael18811380328** [comment]
Oh, it is a problem. Could you tell us which device and browser do you use?

**Comment by huegelc** [comment]
Hi,
Safari Version 12.1.1 (14607.2.6.1.1)
FF 68.0.1 (64-bit

Thanks

**Comment by freeplant** [comment]
It is likely a browser cache or customized css issue.
