### ISSUE TITLE
Free space not calculated

### ISSUE THREAD

**Issue by huegelc** [haiwen/seahub#3945]
seafile-server-7.0.4

The free space indicator is not calculated in the user dropdown menu

<img width="284" alt="grafik" src="https://user-images.githubusercontent.com/6955465/62408356-45c2ed00-b5c8-11e9-978d-51cec6d6ef68.png">

**Comment by changsijay** [comment]
I tried on my seafile.
this value will show if you set `Quota` for this user.
looks work fine.
