### ISSUE TITLE
Force password change don't affect internal accounts

### ISSUE THREAD

**Issue by cvantum** [haiwen/seahub#3978]
Hello,

i hope i am in the correct repository with my problem. We have two seafile/seahub-Server running, deployed with 7.0.7 (PE) and 7.0.4(CE). On both systems users log in regulary with SSO ( SAML2  ). For additional users we creating internal-accounts.

* Debian Stretch
* Apache 2 / MariaDB
* SeaFile 7.0.7 PE; SeaFile 7.0.4 CE
* SAML2-Login via libapache-modauth-shib2

Usually we want to make a force-password-change on first-login and activated this via Web-Browser. But this function didn't affect new users on both servers.

Is it possible to have this feature activated with SSO-Login? Or is it just available if all users are internal and not SSO-Accounts?

If you need any more informations feel free to ask. Thanks in advance for your help.

Kind regards,
cvantum

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com
