### ISSUE TITLE
Seahub runs on port 8000 since upgrade to 7.0

### ISSUE THREAD

**Issue by sinni800** [haiwen/seahub#3996]
I just upgraded my running instance of Seafile from 6.3.4 to 7.0. Now it will only try to listen to port 8000 no matter what I do.

Port is set in seafile.conf 

    [seahub]
    port = 12004

Also in my Systemd unit:

    ExecStart=/home/seafile/seafile-server-latest/seahub.sh start 12004

I think this is a bug because it stopped listening on the port I specified, which it did before the upgrade.

**Comment by freeplant** [comment]
You can modify the config in gunicorn.conf in conf directory.

**Comment by sinni800** [comment]
This needs to be documented as the old way of configuring it has silently disappeared now. Changing the place to configure something without any kind of need to, sure, but at least document it.

**Comment by 98h398hrpohpoai** [comment]
Is this still broken? There doesn't appear to be a way to change this outside of hardcoding seahub.sh

**Comment by sinni800** [comment]
Inside a docker container i would argue there is not much reason to need to change it, but for a bare install this is horror. I still use the changed gunicorn  i havent upgraded for a while admittedly. is it completely unconfigurable now?

**Comment by 98h398hrpohpoai** [comment]
I forget why I was trying to change it in the container initially. 
I feel like it had something to do with trying to bypass the containerized nginx to avoid a double-proxy or some nonsense I was running into.

I wasn't able to find a way to modify the port it within the configs; however, it can still be changed via the commandline with "./seahub.sh start xxxx: [with xxxx being the port].
On bare metal it's fairly easy to manage with a systemd script, though still less than idea for sure.
