### ISSUE TITLE
Django 1.5.9 security release (current version is actually 1.5.12)

### ISSUE THREAD

**Issue by Strayer** [haiwen/seahub#404]
Hi,

the requirements.txt mentions an outdated Django version (1.5.8), the next version is actually a security fix - the following releases are bugfix releases for problems introduced in the security fix.

Since a lot of Seafile instances probably handle very sensitive data, shouldn't the Django version be more up to date? The docs even show a warning message for the most recent 1.5 release:
https://docs.djangoproject.com/en/1.5/
"This document is for an insecure version of Django that is no longer supported. Please upgrade to a newer release!"

At the very least, the most recent 1.5 version should be used due to the security fixes.

**Comment by Strayer** [comment]
I just realized that even though the 4.0.6 tag mentions Django 1.5.8 in its requirements.txt, the actual release tar on seafile.com uses Django 1.5.1

https://github.com/haiwen/seahub/blob/v4.0.6-server/requirements.txt
https://bitbucket.org/haiwen/seafile/downloads/seafile-server_4.0.6_x86-64.tar.gz

![](https://dl.dropboxusercontent.com/u/256059/random%20pictures/seafile-server_4_0_6_x86-64_tar.jpg)

**Comment by xiez** [comment]
Thanks @Strayer , we are now using Django 1.5.12 in our latest release(4.1.2), and the requirements file is also updated (https://github.com/haiwen/seahub/commit/f580ffb5e2623b27b308ba94d5076d065476db8a). Thanks for reporting!
