### ISSUE TITLE
Security: Upload link password not enforced

### ISSUE THREAD

**Issue by jbbr** [haiwen/seahub#407]
Steps to reproduce:

* Create upload link for directory
* Enable password protection
* Open Link from a different browser session (Incognito)
* Upload is working *without* any password!

Same steps for a download link result in a passwort prompt as expected.

**Comment by lins05** [comment]
Thanks for reporting! However, I can't reproduce this following your steps.

What's the version of your seafile server? Can you reproduce it yourself on
seacloud.cc?

**Comment by jbbr** [comment]
I tried to reproduce the behavior on seacloud.cc and it appears that the buggy behavior is a bit different than assumed yesterday.

It seems as if anyone, who successfully authenticated with *any* password protected link can access any other password protected link (upload & download) _without any password_ and even across libraries.

I was able to reproduce the behavior on seacloud.cc:

* Create download/upload link for directory with password protection
* Open link from a clean browser environment (incognito) and authenticate (files should be visible now/upload allowed)
* Create a second download/upload link with password protection (can be a different password)
* Open second link in the same clean browser environment

=> The second link works without any password prompt!
=> Same behavior also for shared links owned by different users!!

It seems as if the link password protection behaves like "once authenticated to the server => grant access to all protected shared links..."

One last thing: I'm also wondering how the server decides which user is allowed to access a protected folder. Is it somehow IP+user_agent based? Because removing cookies and using a clean/incognito browser environment does not result in a "logout". Every folder is still accessible.

**Comment by lins05** [comment]
Yes, I can reproduce it. Thanks for digging into this! We'll located the
problem and would fix it asap.

**Comment by egroeper** [comment]
@lins05 @freeplant What's the state of this one? Is it already fixed?

**Comment by egroeper** [comment]
Seems to be fixed. Can't reproduce it on 5.0.5.

**Comment by xiez** [comment]
hi @egroeper , this issue is resolved in latest server version 5, so im going to close this.
thank you all!
