### ISSUE TITLE
上传文件超过总容量的界面显示不友好

### ISSUE THREAD

**Issue by JIMhackKING** [haiwen/seahub#4188]
### 上传文件超过总容量

1. 上传文件时如果网盘容量不够，则仍然会上传，之后在上传完成时显示错误信息，如果时大文件这样会导致浪费了用户时间、以及占用网络请求。可以通过获取文件大小来在用户开始上传文件时禁止上传并且提示用户。
2. 上传文件超过总容量会显示的信息时`{"error": "Internal Error"}`这样的显示信息不友好，应该更改为有效的提示信息提示用户文件超出容量
3. 空间已超时上传文件会显示一个大的框里面写着Django的403错误信息，应该跟上面的做相同处理

![image](https://user-images.githubusercontent.com/23214854/67508493-b3605000-f6c3-11e9-8ccc-a29f37390a34.png)
![image](https://user-images.githubusercontent.com/23214854/67508546-c7a44d00-f6c3-11e9-97c0-1ce4b2c41601.png)

**Comment by freeplant** [comment]
Fixed in 7.1 version.
