### ISSUE TITLE
Support Open Graph header tags for public share links

### ISSUE THREAD

**Issue by moschlar** [haiwen/seahub#4275]
From what I could gather, the Open Graph HTML header tags is used by various Social Media/Instant Messaging tools to provide rich preview information for shared links like the page title and preview image.

The specs are here: https://ogp.me/

It would be great if Seahub implemented these for public share links.

**Comment by freeplant** [comment]
It is already implemented in version 7.0.

**Comment by moschlar** [comment]
Yay! :raised_hands:
