### ISSUE TITLE
[Security] [Bug] Possible Open Redirect in Template

### ISSUE THREAD

**Issue by bananaSec** [haiwen/seahub#4313]
Hello,

The issue is with https://github.com/haiwen/seahub/blob/master/seahub/templates/snippets/go_back_js.html#L3 snippet. 

Line # 3 should be,
`    var str = location.protocol + '//' + location.host + '/';`

instead of 
`    var str = location.protocol + '//' + location.host;`

Say the hosted URL is http://myserver.orgname.com/
If the `go_back_js.html` snippet is used in any of the page, then an attacker can make users to redirect to external domain with http://myserver.orgname.com.ATTACKERSWEBSITE.COM/ as the referer. 

Because, the snippet is only checking if the `location.protocol` and `location.host` is at the start. An attacker can change the actual domain by injecting `.something.com` to the actual hosted URL.

**Comment by freeplant** [comment]
It is no longer used in version 7.1.
