### ISSUE TITLE
[ERROR] seahub.utils.repo:317 add_encrypted_repo_secret_key_to_database 'SeafileAPI' object has no attribute 'get_secret_key'

### ISSUE THREAD

**Issue by zhengmz** [haiwen/seahub#4361]
## 环境

部署方式：docker

使用版本: 7.0.5-mc

## 重现条件

1. 创建一个新的加密资料库
2. 在logs/seafile/seahub.log 就会出现

```
[ERROR] seahub.utils.repo:317 add_encrypted_repo_secret_key_to_database 'SeafileAPI' object has no attribute 'get_secret_key'
```

## 初步分析 - 没看出问题

看了源代码base/models.py，也没感觉定义的类有什么问题

但为什么这个类RepoSecretKey下的objects是RepoSecretKeyManager，怎么报了SeafileAPI这个错误？

**Comment by freeplant** [comment]
Fix in 7.1 version
