### ISSUE TITLE
[BUG] The OnlyOffice viewer support the csv file, but it doesn't work after adding the settings

### ISSUE THREAD

**Issue by JIMhackKING** [haiwen/seahub#4368]
As the title, I set the ONLYOFFICE_FILE_EXTENSION in seahub_settings.py like this: `('doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx',       'odt', 'fodt', 'odp', 'fodp', 'ods', 'fods', 'csv')`, the csv file is support in onlyoffice ( I can view this file type in seahub 6.2 with the settings above), but in this version, the csv file view as text file by default, then I delete the csv file type in settings, like this: 
![image](https://user-images.githubusercontent.com/23214854/71103713-888f0580-21f5-11ea-8e26-9c7ad4ce504b.png)
But it displays a page saying that the file type cannot be viewed online.
It can work in seahub 6.2, so I feel that it can custom the file type which file can view in OnlyOffice by user.

**Comment by freeplant** [comment]
Currently we only supported files that supported by all the three solutions MS Office Online Server, OnlyOffice and Collabora Online. This is for reducing code complexity and test cost.
