### ISSUE TITLE
Right mouse button in MD editor

### ISSUE THREAD

**Issue by de-es** [haiwen/seahub#4433]
The right mouse button context menu is not available while in markdown editor, so copy & paste is not available. Bug or feature?

I know I can use keyboard shortcuts but less experienced users are missing the context menu.

Testd in 7.0.5 & 7.1.1

**Comment by freeplant** [comment]
The right mouse button is used in table editing. So the browser default context menu is hidden.

**Comment by de-es** [comment]
I have seen that this changed with 8.0.0 to tables only. Otherwise working as intended.
