### ISSUE TITLE
Change in upload link handling.

### ISSUE THREAD

**Issue by yuyichao** [haiwen/seahub#4441]
This is a change in the upload API that happens somewhere between 6.3 and 7.1. I was able to use `repos/<repo-id>/upload-link/` to get an upload URL and then use the `parent_dir=<...>` to specify the directoy I want to upload the file into.

Now in 7.1.1, if I don't give the `p=` parameter for thhe upload-link request, I get `{"error": "Permission denied."}` as return value (with status code 200 btw). If I only use `p=` in thte first request but not the `parent_dir=` in the second request, I get `{"error": "Invalid URL.
"}` (with a new line before the closing quote, which might be invalid JSON, also 200 status code). I had to provide he directory in both requests. This is fine to work with but is a bit strange. The error return is also a bit strange and give no useful information.....

**Comment by yuyichao** [comment]
I have a strong suspicion that this is caused by https://github.com/haiwen/seafile-server/commit/9f0083f93b3bf272ee503feb8a9a5b3306be82fd#diff-92229f8110a875425cedcc84d4d8ba65R504 .

**Comment by yuyichao** [comment]
Actually, it's probably https://github.com/haiwen/seafile-server/pull/286 instead

**Comment by imwhatiam** [comment]
Hello.

> Now in 7.1.1, if I don't give the `p=` parameter for thhe upload-link request, I get `{"error": "Permission denied."}` as return value (with status code 200 btw).

I just tested this situation, it returned a url which is supposed to, not `{"error": "Permission denied."}`.

Can you generate a test account for us to test in your Seafile service ?

**Comment by imwhatiam** [comment]
> If I only use `p=` in thte first request but not the `parent_dir=` in the second request, I get `{"error": "Invalid URL. "}`

We will update the parameter check logic for the first request (repos/<repo-id>/upload-link/).

If only use `p=`, Seafile will return an error.

**Comment by yuyichao** [comment]
> Can you generate a test account for us to test in your Seafile service ?

Not really since I've patched this up locally......... Using the problem mentioned above.......

**Comment by yuyichao** [comment]
> > Now in 7.1.1, if I don't give the p= parameter for thhe upload-link request, I get {"error": "Permission denied."} as return value (with status code 200 btw).

> I just tested this situation, it returned a url which is supposed to, not {"error": "Permission denied."}.

BTW, what I meant by the "upload-link" request is the request to the URL I get back from the first request (upload-link) that is used to actually upload the file.

**Comment by freeplant** [comment]
Fixed in https://github.com/haiwen/seahub/pull/4528

**Comment by yuyichao** [comment]
AFAICT that doesn't fix the problem I'm reporting.

**Comment by freeplant** [comment]
In version 7.1, the parent_dir parameter has to be set both in getting the link and actually uploading file to the link. This is for security reason.

**Comment by freeplant** [comment]
In version 7.1, the parent_dir parameter has to be set both in getting the link and actually uploading file to the link. This is for security reason.

**Comment by yuyichao** [comment]
Right, and that is exactly what I argued as not making sense.
