### ISSUE TITLE
role must be in [...]

### ISSUE THREAD

**Issue by cvantum** [haiwen/seahub#4624]
Hello,

since a update to 7.1.5 Pro we encountered an issue with managing roles of users. We created a list of indivual roles in `seahub_settingy.py` which was fine in previous updates.

In 'seafie.log' there isn't any evidence for this issue. 

Kind regards

**Comment by cvantum** [comment]
Since this config-file was working in the past we assume that there is no issue with parsing the `seahub_settings.py`. We also tried to rename some listed roles to find out if this is an issue with similar named institutional groups. But it didn't helped

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com or send email to support@seafile.com if you are a paid customer with a license for 9+ users.
