### ISSUE TITLE
OnlyOffice: JWT broken for public shared links / PR for fix available

### ISSUE THREAD

**Issue by julian-w** [haiwen/seahub#4635]
Hello,

if you configure Seafile with OnlyOffice and use JWT, public shared links do not work. The reason for that is that Seahub does not include the JWT token in the link. A fix is available: #4558 

Can you please merge this Pull Request in order to fix this bug.

Thank you!

Best regards,
Julian

**Comment by imwhatiam** [comment]
@julian-w   Hello, thanks for reporting.

As there are some other pages that will use OnlyOffice, so I pushed another pull request to fix this bug.
