### ISSUE TITLE
MP3 Playback from WebUI fails

### ISSUE THREAD

**Issue by samboman** [haiwen/seahub#464]
I have posted some info here:
https://github.com/haiwen/seafile/issues/1102

In additional it seems to also be affecting desktop in 4.1.2. (Chrome tested).
Chrome and iOS fails:
![image](https://cloud.githubusercontent.com/assets/1038277/6996929/f8b92250-dba5-11e4-8ba5-9da1ef637e60.png)

Internet Explorer and Firefox works:
![image](https://cloud.githubusercontent.com/assets/1038277/6996928/f35c0f98-dba5-11e4-92c4-c61369b02e4b.png)

Update:
I can confirm the problem exists when running Seafile without web-server (Nginx / Apache).

**Comment by samboman** [comment]
It's maybe something you know about, @vIiRuS
Thanks allot for your support!
I can provide more of my configuration if it's needed.

//Sam

**Comment by shoeper** [comment]
I think it's due to not supported range requests.
But they've been implemented, don't think it'll take much time until next version with byte range requests gets published.

**Comment by samboman** [comment]
@shoeper I got info from @freeplant that it will be fixed in v4.2.
I didn't know if I posted in right seahub / seafile... Maybe one can be closed as duplicate?
https://github.com/haiwen/seafile/issues/1102

**Comment by shoeper** [comment]
In my opinion you can close this.

**Comment by samboman** [comment]
This seems to be fixed a long time ago... I can confirm it works great in 5.1.3.
