### ISSUE TITLE
Can't reset user quota to default in system administration

### ISSUE THREAD

**Issue by de-es** [haiwen/seahub#4693]
Seafile 7.1.5 CE

I can't reset a user's quota to the default value in the system administration settings in Seahub. Setting the value to "0" does nothing, it stays at the previous value after submitting. Changing the value to anything greater than 0 is working correctly.

**Comment by JeanLouPtflbx** [comment]
Hello,
I've got the same behaviour with Seaflie CE 8.0.4.

**Comment by de-es** [comment]
Right, it's still not working in CE 8.0.4. No error in the logs, API response is fine (200).

**Comment by de-es** [comment]
Fixed in CE 9.x
