### ISSUE TITLE
[Bug] guest invitation is broken for seafile versions >= 7.1

### ISSUE THREAD

**Issue by weimens** [haiwen/seahub#4794]
After a few invitations are sent successfully no new invitation can be sent until seahub is restarted.
The error is only logged in the seahub_db.post_office_log table.
```
SMTPSenderRefused      | (421, b'4.4.2 <servername> Error: timeout exceeded',
SMTPServerDisconnected | please run connect() first
```
apparently this problem was fixed once with [Fix post office connection and handle invitation error ](https://github.com/haiwen/seahub/commit/a306737700741838cc33184b64d690d21a065685) though the problem recured. The fix in https://github.com/haiwen/django-post_office/commit/2312cf240363721f737b5ac8eb86ab8cb255938f was never added to the upstream repository and with https://github.com/haiwen/seahub/commit/99a9ece04e31fb2c1d8bfc578e2b0d80a4d4ce16 seahub switched back to the upstream repository for django-post-office.

With https://github.com/ui/django-post_office/pull/352 this bug is fixed in  django-post-office, therefore when seafile updates django-post-office to an newer version than https://github.com/ui/django-post_office/commit/cc6fcac45a2eecbc741ffbfbcd21042b7b5c79a3 this issues will fixed in seafile as well.

**Comment by freeplant** [comment]
Actually we don't use the features in Django post_office (i.e., recording emails in database and send them asynchronously). We will remove the use of Django post_office in version 7.1.12 to fix the problem.

**Comment by weimens** [comment]
post_office is still in use here https://github.com/haiwen/seahub/blob/a79d9327cb6c8c6290cd4390b7c82ec4f333c23f/seahub/utils/mail.py#L4 witch gets used by https://github.com/haiwen/seahub/blob/a79d9327cb6c8c6290cd4390b7c82ec4f333c23f/seahub/invitations/models.py#L86, though replacing post_office will fix the problem as well. The exact Version were this problem occurs is seafile pro server 7.1.8 for CentOS.

**Comment by weimens** [comment]
It has nothing to do with "recording emails in database and send them asynchronously" it only affects synchronously sending emails with post_office which takes place when priority=MAIL_PRIORITY.now is set, though post_office logs errors only to database.
