### ISSUE TITLE
Users found twice in system admin 

### ISSUE THREAD

**Issue by reitberger** [haiwen/seahub#4811]
Hello!

I’m using version 8.0.3 of Seafile server and found the following behaviour:

When searching for users in “system admin” panel a user is always found twice when the search term is part of his name and his email address, which is often the case. I think this is irritating. Every user should be found only once.

Sincerely Reitberger

**Comment by JeanLouPtflbx** [comment]
Hello,
I have the same problem with 8.0.4, some users appears twice in system admin.
In database users are present only one time.

**Comment by freeplant** [comment]
It has been fixed in the latest release.
