### ISSUE TITLE
Expire date is not updated for new guest invitation

### ISSUE THREAD

**Issue by weimens** [haiwen/seahub#4874]
How to reproduce:

- user: invites guest, via the Share menu
- guest gets an email 
- invitation expires
- user: invites guest again, via the Share menu.
- guest gets an email, with the same invitation token, that is expired.

Current behaviour:
- guest gets an email, with the same invitation token, that is expired.

Expected behaviour:
- the expire date get reset, when the user invites the guest again via the Share menu.

**Comment by imwhatiam** [comment]
@weimens

**Comment by imwhatiam** [comment]
@weimens Hello, which version of Seafile are you using?

For this step:

user: invites guest again, via the Share menu.

If the guest user has been invited, you can not invite his/her again.

Seafile will throw an error: xxx is already invited.

**Comment by weimens** [comment]
originally it was 7.1.9-pro, but  the problem still occurs with 7.1.21-pro
I only get the "xxx is already invited." message when I use "Invite Guest"-Menu [/api/v2.1/invitations/batch/](https://github.com/haiwen/seahub/blob/v7.1.21-pro/seahub/api2/endpoints/invitations.py#L81) from the side panel. Share -> Invite Guest [/api/v2.1/repos/<repo_id>/shared/invitations/batch/](https://github.com/haiwen/seahub/blob/v7.1.21-pro/seahub/api2/endpoints/repo_share_invitations.py#L83) behaves different, here it it is possible invite the Guest again.

**Comment by imwhatiam** [comment]
@weimens Thank you for describing the steps to reproduce the problem. We will fix it on the latest Seafile 8.0.x version.

**Comment by weimens** [comment]
Thanks, I will update to 8.0.8 next week.
