### ISSUE TITLE
Disable regular auth, when OAuth is enabled

### ISSUE THREAD

**Issue by NicolaiSchmid** [haiwen/seahub#4879]
Is there an option, with which I can disable the regular login via email and password when I have OAuth configured?

If there isn't I'd be happy to implement it, though I would need some pointers, on how to do that.

**Comment by sphakka** [comment]
This is marked as completed with no reference to commits, documentation, etc. I configured Authelia OIDC and would like to _skip_ the standard login page upon successful authentication. This should be a common option for any SSO/CAS-based login mechanism. Cf. [Roundcube Oauth2 `oauth_login_redirect`option](https://github.com/roundcube/roundcubemail/wiki/Configuration:-OAuth2#disabling-the-roundcube-login-form).
