### ISSUE TITLE
Logout link not including site root, causing incorrect logout URL for non-root domain deployments

### ISSUE THREAD

**Issue by davidbereza** [haiwen/seahub#4898]
Hello,

It seems that for the user drop down menu, the `Logout` link does not include the site root information, causing logouts to direct to the wrong URL for non-root domain deployments.

**Example:** Seahub deployed to `https://example.com/seahub/` redirects to `https://example.com/accounts/logout/` rather than the expected `https://example.com/seahub/accounts/logout/`, causing a 404 page to be displayed.

I believe the line below is the root cause:

https://github.com/haiwen/seahub/blob/ba4d1d95e5e8aa063b2d5d52d58e3a7f3f197789/frontend/src/components/common/account.js#L167

This does seem to not be a problem for other links, such as for the `Settings` link which prepend the `siteRoot` constant:

https://github.com/haiwen/seahub/blob/ba4d1d95e5e8aa063b2d5d52d58e3a7f3f197789/frontend/src/components/common/account.js#L165

**Comment by freeplant** [comment]
The fix will be included in the next 8.0 version.
