### ISSUE TITLE
regarding the usage of seadrive-daemon

### ISSUE THREAD

**Issue by Scottpedia** [haiwen/seahub#4938]
Hello

The instructions for using seadrive without the gui running on your documentation site say that I have to run the daemon in foreground. But as a daemon itself, it must be able somehow to be run in the background. Can you tell me how I can make it run in the background?

Please refer to the following article: https://help.seafile.com/drive_client/drive_client_for_linux/#running-seadrive-without-gui

**Comment by freeplant** [comment]
Just type the command as in the document.

**Comment by Scottpedia** [comment]
@freeplant 

> Note that you must give -f option in the command line, to make sure seadrive runs in foregound, instead of forking as a daemon. 

I tried running the command without -f, and it went into the background yes. But when running in the background, the mounted destination directory does not work.

Please take a look at:
https://forum.seafile.com/t/how-to-run-seadrive-as-a-daemon/14852

I hope you can answer my question.

**Comment by Scottpedia** [comment]
@freeplant 

For some reason, the seafile team has refused to answer all similar questions like this one on both github and the community forum... Can you at least give me an idea of the design objective of this feature(aka no background mode)?

I mean it's not difficult for me to just slightly modify the source code and rebuild my own binary to have it run in the background.
