### ISSUE TITLE
Port in URL settings is sometimes ignored

### ISSUE THREAD

**Issue by TheRisenPhoenix** [haiwen/seahub#4969]
I have my seafile installation running with docker under port `8000` instead of `80`. 
I mapped this port to docker via the docker-compose file, and also set the port in both URLs in the admin panel.
However, the system seems to ignore the port selection from time to time:

1) When you set `FILE_SERVER_ROOT` to `http://127.0.0.1:8000/seafhttp` , downloading files from the browser won't work anymore. Previewing the file works fine, but once you click *download*, you are redirected to `127.0.0.1:80`
However, you can enter your external IP adress here, then downloading will work again and the port is not ignored.

2) The (default) avatar-image won't load. It tries to get it again from `127.0.0.1:80` instead of port `8000`. I didn't find a way to change this.

I also tried changing the port in seahub_settings.py, but the error is still the same. Any advice on that?

**Comment by freeplant** [comment]
I'm afraid you should use port 80 or 443 for docker version of Seafile.
