### ISSUE TITLE
OAuth 2 MUST utilize https

### ISSUE THREAD

**Issue by z3ky** [haiwen/seahub#5083]
According to this topic https://forum.seafile.com/t/oauth-fails-with-must-utilize-https-but-everything-is-https/10401

OAuth fails with

> [ERROR] seahub.oauth.views:150 oauth_callback (insecure_transport) OAuth 2 MUST utilize https.

https://github.com/haiwen/seahub/blob/e92fcd44e3e46260597d8faa9347cb8222b8b10d/seahub/oauth/views.py#L133
request.get_full_path() just containes /seafile/oauth/… and not the full URL.

**Comment by mrwangjianhui** [comment]
Adding the following option to seahub_settings.py will solve your issue without having to modify seahub's code:
`OAUTH_ENABLE_INSECURE_TRANSPORT = True`

After reading the following code, you should fully understand:
https://github.com/oauthlib/oauthlib/blob/master/oauthlib/oauth2/rfc6749/utils.py#L79-L83
https://github.com/haiwen/seahub/blob/master/seahub/oauth/views.py#L37-L38
