### ISSUE TITLE
timestamp mtime of files/directories changed on upload with seahub

### ISSUE THREAD

**Issue by birdynm** [haiwen/seahub#5092]
Dear All,

files/directories which are uploaded to seafile via seahub do get the timestamp/mtime of the upload time instead of keeping the original timestamp. 

Files uploaded via the client do keep the original timestamp. (Desktop Syncing Client 8.0.5)

Even so I admit that I can be sometimes also interesting when a file was uploaded.

Version: seafile-server-9.0.2

**Comment by mrwangjianhui** [comment]
Hi, you can ask this issue in the forum: [forum.seafile.com](https://forum.seafile.com/)
