### ISSUE TITLE
Clarify/Update documentation – clean_database.

### ISSUE THREAD

**Issue by weimens** [haiwen/seahub#5106]
The [clean_database documentation](https://manual.seafile.com/maintain/clean_database/) is missing the `clean_db_records` command that was [apparently introduced with seafile 8.0](https://github.com/haiwen/seahub/pull/4845) 

A way to set an custom range instead the hard coded 90 days would be maybe preferable. See [pull request](https://github.com/haiwen/seahub/pull/5105) and  [pull request admin docs](https://github.com/haiwen/seafile-admin-docs/pull/83).

Maybe a minor thing, but the title ‘Clean Database’ is some what misleading. To me it sound like the indention is to delete information that is maybe necessary for accessing data that is stored on seafile. But for the clean_db_records part the tables that are cleared are all involved in audit and access logging and are not necessary to accessing data that is stored on seafile.

Some information where to find the table content in the web interface might also be help full.
| url | table |
| ------------- | ------------- |
| \<seafile-server\>/dashboard/ | Event,Activity |
| \<seafile-server\>/sys/logs/login/ | sysadmin_extra_userloginlog |
| \<seafile-server\>/sys/logs/file-access/ | FileAudit |
| \<seafile-server\>/sys/logs/share-permission/ | FileUpdate |
| \<seafile-server\>/sys/logs/file-update/ | PermAudit |
| ? | FileHistory|

**Comment by mrwangjianhui** [comment]
Documentation has been updated: https://manual.seafile.com/maintain/clean_database/#command-clean_db_records.
FileHistory records the modification history of files: <seafile-server>/repo/file_revisions/<repo_id>/?p=</file/to/path>
