### ISSUE TITLE
Broken page on `/invite/token/*/`: “User matching query does not exits.”

### ISSUE THREAD

**Issue by devidw** [haiwen/seahub#5113]
When clicking an invite link, the page shows normally, after entering a password the following error page appears:

```plain
Page unavailable
Sorry, but the requested page is unavailable due to a server hiccup.
Our engineers have been notified, so check back later.
```

After stopping Seahub, clearing the cache in `/tmp/seahub_cache` and starting the service again, there is no difference (https://github.com/haiwen/seafile/issues/985).

From the logs, I extracted the following error message:

```plain
Traceback (most recent call last):
  File "/home/seafile/seafile-pro-server-7.1.17/seahub/seahub/invitations/views.py", line 49, in token_view
    user = User.objects.get(email=i.accepter)
  File "/home/seafile/seafile-pro-server-7.1.17/seahub/seahub/base/accounts.py", line 99, in get
    raise User.DoesNotExist('User matching query does not exits.')
seahub.base.accounts.User.DoesNotExist: User matching query does not exits.
```

As you can see, the used Seafile server version is `7.1.17`.

**Comment by mrwangjianhui** [comment]
You can upgrade Seafile server to the latest 9.0.5, I did not have this problem with this version.
