### ISSUE TITLE
Markdown lists get escaped 

### ISSUE THREAD

**Issue by wjdenny** [haiwen/seahub#5151]
I am syncing a logseq directory with Seafile, and many of these files have Markdown bullet lists. When I open a file in the Seafile web front-end and save it, any bullet lists made with `-` are escaped and made to be `\-`.

This behavior is unexpected and interferes with the use of these files.

**Comment by mrwangjianhui** [comment]
Sorry, I didn't reproduce the issue, everything works fine for me. You can upgrade Seafile to the latest 9.0.x version and see if this issue still occurs.
