### ISSUE TITLE
update cffi to 1.15

### ISSUE THREAD

**Issue by blshkv** [haiwen/seahub#5166]
https://forum.seafile.com/t/seafile-community-edition-9-0-4-is-ready/15988/8
```I’m sorry changing python-cffi to 1.15.0 will cause some problems in Ubuntu system as we have tested before.```

I'm not an Ubuntu user and have no idea what could be a problem.
But you will have to migrate to 1.15 soon or later.

Please link an Ubuntu bug report here (if there is one). 

Hardcoding a specific version is a bad idea. For example, I have 1.14.6 in my system and have to patch apy.py file to match that version

**Comment by mrwangjianhui** [comment]
https://forum.seafile.com/t/seafile-community-edition-9-0-2-is-ready/15569/15

**Comment by mrwangjianhui** [comment]
https://forum.seafile.com/t/seafile-community-edition-9-0-2-is-ready/15569/15

**Comment by blshkv** [comment]
quick and dirty workaround is to patch this file:
```sed -e "s|1.14.0|1.15.0|" -i seahub/thirdpart/cffi/__init__.py```
I didn't encourage any issues with cffi 1.15

**Comment by mrwangjianhui** [comment]
So do I. By the way, Seafile recommends using docker deployment since 8.0, which can avoid many system environment issue: https://manual.seafile.com/deploy/#deploying-seafile

**Comment by blshkv** [comment]
docker is a quick shortcut, but not a good solution to "solve" dependencies. It won't be many issues if the application is written properly. First of all, dependencies follow major-minor version compatibility usually, so it is safe to upgrade 1.x.x as the API *should not* change. Second, you should rely on OS updates and *NOT* keep outdated packages, as some of them may be vulnerable to various attacks.

**Comment by freeplant** [comment]
Many users already deployed Seafile 9.0 with cffi 1.14 (cffi 1.14 is installed globally). 

If we upgrade the bundled cffi to 1.15, there will be versions of cffi. The included one is 1.15, while the system one is 1.14. And Seafile will not work.

We can only upgrade cffi to 1.15 in version 10.x, where people can upgrade the cffi in their system by following the upgrade document for Seafile 10.x.

**Comment by blshkv** [comment]
can you update your scripts to look at "thirdpart" directly first, and load it from system location if it's not available?
In this way, I could just delete outdated packages from that bundled directory
