### ISSUE TITLE
Office FIle Preview Max Size 2MB

### ISSUE THREAD

**Issue by jonas-w** [haiwen/seahub#5178]
When using the office online preview in the professional version, i only can open files under 2MB is there any way to change this limit? 
I understand that there is a limit but 2MB seems very low!

![image](https://user-images.githubusercontent.com/32615971/167308797-d0a780dc-52eb-42bc-8172-28bc9ba4a60c.png)

**Comment by mrwangjianhui** [comment]
Using the built-in office preview function of Seafile, you can only preview office files under 2MB. If you want to preview over 2MB office files, please use OfficeOnlineServer or OnlyOffice: https://manual.seafile.com/deploy/only_office/; https://manual.seafile.com/deploy_pro/office_web_app/
