### ISSUE TITLE
[seafile 9.0.5, onlyoffice 7.1] authentication, forms

### ISSUE THREAD

**Issue by sacesare** [haiwen/seahub#5182]
Hi, onlyoffice 7.1 has problems with jwt authentication (validation issue) and supported document types.

1. jwt authentication
[editorConfig.mode](/haiwen/seahub/blob/v9.0.5-server/seahub/onlyoffice/utils.py#L171)
must be string, so something like ` 'edit' if can_edit else 'view' ` will work in new onlyoffice.
Reason [validateAuthToken](/ONLYOFFICE/server/blob/master/DocService/sources/DocsCoServer.js#L2096) , see also [mode](https://api.onlyoffice.com/editors/config/editor#mode)

2. document types
[DOCUMENT extensions](/haiwen/seahub/blob/v9.0.5-server/seahub/utils/__init__.py#L122)
need to add new 'oform' and 'docxf' extensions, hint [ONLYOFFICE forms: new OFORM & DOCXF formats explained](https://www.onlyoffice.com/blog/2022/03/onlyoffice-forms-new-oform-docxf-formats-explained/)

**Comment by freeplant** [comment]
The first problem has been fixed now. The second feature will be added soon.
