### ISSUE TITLE
OAuth access token request missing HTTPS context

### ISSUE THREAD

**Issue by Leyvur** [haiwen/seahub#5216]
Hi,

I'm trying to enable OAuth for my Seafile 9.0.6 installation. Unfortunately it does not work due to HTTPS errors.
I came across the same issue as in this forum post: **[OAuth fails with “Must utilize https”, but everything is https](https://forum.seafile.com/t/oauth-fails-with-must-utilize-https-but-everything-is-https/10401)**

This is the problematic function mentioned in the post:

https://github.com/haiwen/seahub/blob/ad8da251338577e9adc349fc68ea84780acfcdc8/seahub/oauth/views.py#L133

The `authorization_response` should be extended so that the token contains the full HTTP/HTTPS URL. Currently there is only the path, without domain or protocol.

Here is a working example from [Authlib](https://docs.authlib.org/en/latest/client/oauth2.html):

>  authorization_response = 'https://example.com/github?code=42..e9&state=d..t'

**Comment by Leyvur** [comment]
Maybe issue #2094 is also related to this?

**Comment by imwhatiam** [comment]
>

**Comment by imwhatiam** [comment]
> Hi,
> 
> I'm trying to enable OAuth for my Seafile 9.0.6 installation. Unfortunately it does not work due to HTTPS errors. I came across the same issue as in this forum post: **[OAuth fails with “Must utilize https”, but everything is https](https://forum.seafile.com/t/oauth-fails-with-must-utilize-https-but-everything-is-https/10401)**
> 
> This is the problematic function mentioned in the post:
> 
> https://github.com/haiwen/seahub/blob/ad8da251338577e9adc349fc68ea84780acfcdc8/seahub/oauth/views.py#L133
> 
> The `authorization_response` should be extended so that the token contains the full HTTP/HTTPS URL. Currently there is only the path, without domain or protocol.
> 
> Here is a working example from [Authlib](https://docs.authlib.org/en/latest/client/oauth2.html):
> 
> > authorization_response = 'https://example.com/github?code=42..e9&state=d..t'



```
ENABLE_OAUTH = True
OAUTH_ENABLE_INSECURE_TRANSPORT = True

OAUTH_CLIENT_ID = "..."
OAUTH_CLIENT_SECRET = "..."
OAUTH_REDIRECT_URL = 'https://demo.seafile.com/oauth/callback/'

# The following shoud NOT be changed if you are using Google as OAuth provider.
OAUTH_PROVIDER_DOMAIN = 'google.com'
OAUTH_AUTHORIZATION_URL = 'https://accounts.google.com/o/oauth2/v2/auth'
OAUTH_TOKEN_URL = 'https://www.googleapis.com/oauth2/v4/token'
OAUTH_USER_INFO_URL = 'https://www.googleapis.com/oauth2/v1/userinfo'
OAUTH_SCOPE = [
    "https://www.googleapis.com/auth/userinfo.email",
    "openid",
]
OAUTH_ATTRIBUTE_MAP = {
    "id": (True, "email"),
    "name": (False, "name"),
    "email": (False, "contact_email"),
}
```

**Comment by imwhatiam** [comment]
> OAuth fails with “Must utilize https”, but everything is https

Have you deployed Seafile at Non-root domain?

**Comment by imwhatiam** [comment]
> OAuth fails with “Must utilize https”, but everything is https

Have you deployed Seafile at Non-root domain?

**Comment by Leyvur** [comment]
Hello,
Thank you for providing your configuration, I have taken some time to check my setup. But the problem still persists.

My Seafile 9.0.6 is deployed at https://seafile.[my-domain].de/.
HTTPS is configured correctly, the SSL Labs report shows "A+". I set up [Authelia](https://www.authelia.com/integration/openid-connect/seafile/) as my OAuth provider and successfully use OAuth to log into my Gitea instance.

> For the problem you encountered, how can I reproduce it?

Please try it with `OAUTH_ENABLE_INSECURE_TRANSPORT = False`.

This will cause the login to fail with "OAuth 2 MUST utilize https".
However, if you extend the `authorization_response` field as suggested above, it will work again.

According to the [OAuthLib docs](https://oauthlib.readthedocs.io/en/latest/oauth2/security.html), `OAUTHLIB_INSECURE_TRANSPORT` should never be enabled in a production setup.
So it would be nice if the Seahub OAuth implementation could be improved to fully support HTTPS transport and fix this potential security problem. I'm not sure whether the access token is the only thing that needs to be changed to achieve that. But at least in my tests, this seems to be the only issue.

**Comment by imwhatiam** [comment]
```
Please try it with OAUTH_ENABLE_INSECURE_TRANSPORT = False.
```

Thanks for the info, we can reproduce this problem now.

**Comment by Leyvur** [comment]
Your patch https://github.com/haiwen/seahub/commit/fc04a91eea995391c0a45b6f1089950512f289c6 in Seafile 9.0.7 fixed the problem for me. Thank you!
