### ISSUE TITLE
如何对源码进行打包操作，并用于docker安装

### ISSUE THREAD

**Issue by anarchical** [haiwen/seahub#5317]
### 背景
您好，我在seahub和seafile-server的源码基础上进行了一些自定义的修改，在开发环境中一切都运行正常，现在需要对源码进行打包操作
### 问题
现在看起来 seahub/scripts/build/build-server.py 看起来是用来打包的脚本，我参考 https://manual.seafile.com/build_seafile/rpi/#run-the-packaging-script 执行了相关的命令，但是发现需要一些不相关的基础服务，如 seafdav，seafobj，这些服务并没有出现在开发环境配置中
### 预期
现在我想把 seahub和seafile-server的源码进行打包操作，用于docker镜像的安装，预期结果如同 https://seafile-downloads.oss-cn-shanghai.aliyuncs.com/seafile-server_9.0.9_x86-64.tar.gz

**Comment by freeplant** [comment]
Docker 打包的代码是公开的，https://github.com/haiwen/seafile-docker ， 你可以参考下。
