### ISSUE TITLE
Redirect to login does not prepend SCRIPT_NAME

### ISSUE THREAD

**Issue by pbrenna** [haiwen/seahub#5361]
The @login_required decorator does not prepend SCRIPT_NAME to the url. 

this is due to a version of user_passes_test at https://github.com/haiwen/seahub/blob/ff9a0e92f9a8283f7f2c9f65ce2afcd7eabe1da2/seahub/auth/decorators.py#L13 which is different from the original function in `django.contrib.auth.decorators` at https://github.com/django/django/blob/4c85beca9d8bf24573d741e26ea36295c69af5b2/django/contrib/auth/decorators.py#L10.

This prevents deployments in subpahts (eg. mysite.com/seafile/) from working.

**Comment by imwhatiam** [comment]
@pbrenna Hello.

We have a test Seafile site deployed with subpath, it works fine.

What do you mean "This prevents deployments in subpahts (eg. mysite.com/seafile/) from working."

Can you show us the steps to reproduce the problem？Is there any error message in logs/seahub.log on your side?

**Comment by pbrenna** [comment]
Hi @imwhatiam, sorry for the delay. For that particular deployment we ended up using a custom port; however i can confirm that following the linked manual, everything works, so i'm gonna close this issue.

So i guess my only criticism is the discoverability of that page: 
- i suggest that it should be linked from https://manual.seafile.com/docker/deploy_seafile_with_docker/
- i was not familiar with the term "non-root domain" for this concept: i suggest that the terms subpath/subfolder/script_name should be used in a FAQ entry linking to that page.

Thank you!
