### ISSUE TITLE
Upload does not work on mobile devices

### ISSUE THREAD

**Issue by runout-at** [haiwen/seahub#5386]
If an upload link is used on a mobile device, its not possible to use it (easily).

Drag'n'drop is almost not usable on a mobile device.

And the dropdown 'Upload > File/Folder' sends me to the last used app instead of showing some dialog for choosing a file/folder.

Tested on Android and LineageOS. Seafile Server 9.0.9

**Comment by freeplant** [comment]
From my test, the upload works find in the latest version.
