### ISSUE TITLE
pycharm工具中怎么运行该项目

### ISSUE THREAD

**Issue by chunqiudameng01** [haiwen/seahub#5476]
pycharm工具中怎么运行该项目,启动seahub项目 from seaserv import seafile_api 这个模块无法导入;怎么才能运行该项目

**Comment by rwyydxy** [comment]
同问，哥们被这卡主了，这个包明显在其他项目里，但是在Windos环境下要怎么运行起来整个项目，这手册是一点没写呀

**Comment by Michael18811380328** [comment]
可以参考这里：https://manual.seafile.com/build_seafile/server/ @rwyydxy @chunqiudameng01

**Comment by Michael18811380328** [comment]
@rwyydxy Windows 系统参考这里，https://manual.seafile.com/build_seafile/windows/
