### ISSUE TITLE
seafile/sdoc-editor 没有对应的 前端包

### ISSUE THREAD

**Issue by gongyuansong** [haiwen/seahub#5516]
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code E404
npm ERR! 404 Not Found - GET http://mirrors.cloud.tencent.com/npm/@seafile/sdoc-editor/-/sdoc-editor-0.1.53.tgz - no such package available
npm ERR! 404
npm ERR! 404  '@seafile/sdoc-editor@http://mirrors.cloud.tencent.com/npm/@seafile/sdoc-editor/-/sdoc-editor-0.1.53.tgz' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ZZ037N672\AppData\Local\npm-cache\_logs\2023-06-20T07_00_18_119Z-debug-0.log       
PS C:\gysgong\dev\source-code\seahub\frontend> 

是不是 对应的包换了新地址 ， 麻烦哪位仁兄提供一下

**Comment by Michael18811380328** [comment]
你这个 npm 源是腾讯的源 http://mirrors.cloud.tencent.com/ ，切换成 npm 官方的源试一下，

**Comment by lovehunter9** [comment]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@seafile/sdoc-editor/-/sdoc-editor-0.1.56.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@seafile/sdoc-editor@https://registry.npmjs.org/@seafile/sdoc-editor/-/sdoc-editor-0.1.56.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

我用的应该是npm官方的源吧？同样的问题……

**Comment by freeplant** [comment]
你现在可以基于 10.0 分支构建。10.0 分支不依赖于 sdoc-editor。 master 分支后续会修复下。

**Comment by lovehunter9** [comment]
> 你现在可以基于 10.0 分支构建。10.0 分支不依赖于 sdoc-editor。 master 分支后续会修复下。

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@seafile/sdoc-editor/-/sdoc-editor-0.1.50.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@seafile/sdoc-editor@https://registry.npmjs.org/@seafile/sdoc-editor/-/sdoc-editor-0.1.50.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/wangrongxiang/.npm/_logs/2023-06-28T07_29_17_624Z-debug-0.log

git status
On branch 10.0
Your branch is up to date with 'origin/10.0'.

同样。。。

**Comment by freeplant** [comment]
最新的版本已修复。
