### ISSUE TITLE
最新版本的seahub前端npm install时报以下错（macOS），如何解决？

### ISSUE THREAD

**Issue by lovehunter9** [haiwen/seahub#5528]
npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.14.5
npm WARN Found: @babel/core@7.12.3
npm WARN node_modules/@babel/core
npm WARN   dev @babel/core@"7.12.3" from the root project
npm WARN   160 more (@babel/helper-compilation-targets, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.14.5
npm WARN node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm WARN   @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.14.5" from @babel/preset-env@7.14.5
npm WARN   node_modules/@babel/preset-env
npm WARN 
npm WARN Conflicting peer dependency: @babel/core@7.22.5
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.14.5
npm WARN   node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm WARN     @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.14.5" from @babel/preset-env@7.14.5
npm WARN     node_modules/@babel/preset-env
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-native@0.70.6
npm WARN Found: react@17.0.0
npm WARN node_modules/react
npm WARN   react@"17.0.0" from the root project
npm WARN   27 more (@gatsbyjs/reach-router, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"18.1.0" from react-native@0.70.6
npm WARN node_modules/react-qr-code/node_modules/react-native
npm WARN   peer react-native@"*" from @react-native-community/art@1.2.0
npm WARN   node_modules/react-qr-code/node_modules/@react-native-community/art
npm WARN 
npm WARN Conflicting peer dependency: react@18.1.0
npm WARN node_modules/react
npm WARN   peer react@"18.1.0" from react-native@0.70.6
npm WARN   node_modules/react-qr-code/node_modules/react-native
npm WARN     peer react-native@"*" from @react-native-community/art@1.2.0
npm WARN     node_modules/react-qr-code/node_modules/@react-native-community/art

up to date, audited 2741 packages in 24s

229 packages are looking for funding
  run `npm fund` for details

137 vulnerabilities (1 low, 100 moderate, 35 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

**Comment by Michael18811380328** [comment]
试一下使用 `npm install --force` 临时忽略第三方包的 overriding peer dependency 问题
