### ISSUE TITLE
TOTP validation does not prevent token replay

### ISSUE THREAD

**Issue by suspectpart** [haiwen/seahub#5706]
[RFC 6238](https://datatracker.ietf.org/doc/rfc6238/) specifies the TOTP algorithm used as the main 2FA method in Seahub. It states:

>    Note that a prover may send the same OTP inside a given time-step
   window multiple times to a verifier.  The verifier **MUST NOT** accept
   the second attempt of the OTP after the successful validation has
   been issued for the first OTP, which ensures one-time only use of an
   OTP.

After successful TOTP validation, the implementation in Seahub updates a value of `last_t` on the user's device, but never evaluates it during token validation because the [corresponding line](https://github.com/haiwen/seahub/blame/aa8b74ffffafa03367afc113c62d5fa4033663ab/seahub/two_factor/models/totp.py#L104) has been commented out:

```python
def verify_token(self, token):     
     ...
     for offset in range(-self.tolerance, self.tolerance + 1):
         totp.drift = self.drift + offset
         # print('user input = %s, token = %s, self.last_t = %s, totp.t() = %s' % (token, totp.token(), totp.t(), self.last_t))
         # if (totp.t() > self.last_t) and (totp.token() == token):   # <---- commented out!
         if totp.token() == token:
             self.last_t = totp.t()
             if (offset != 0) and OTP_TOTP_SYNC:
                 self.drift += offset
              self.save()

              verified = True
                    
```
 
It seems like it has been commented out since the code was migrated six years ago in d0975c7, consistent across all versions of Seahub.

`last_t`  is also documented with its intended use but the value is never read anywhere in the code base:

>    *BigIntegerField*: The time step of the last verified token. To avoid
        verifying the same token twice, this will be updated on each successful
        verification. Only tokens at a higher time step will be verified
        subsequently. (Default: -1)

Should the commented out evaluation of `last_t`  be included again to be compliant with RFC 6238 (as it is a `MUST`-constraint), or am I missing something? Maybe there is another means to ensure that a token can never be used twice?

**Comment by suspectpart** [comment]
I see that this ticket should be fixed with the merge of https://github.com/haiwen/seahub/commit/cbba3d918194e582342072a7931f93c86082a55d. Do you think it makes sense to also log cases where the token itself is valid, but is behind `last_t` (so it seems like a token replay) for security audit logging? Or is that a separate feature request?

**Comment by freeplant** [comment]
Adding a log make a sense. Thanks for the suggestion. We will add it soon.

**Comment by suspectpart** [comment]
Thanks for the lightning fast reaction of including the log in https://github.com/haiwen/seahub/commit/87f7a293790e48bdb6c2986e4eb9c02b70c550e1 :-).

What is logged now is generally unsuccessful token authentication (i.e. user presents an invalid token, for whatever reason). Because TOTP is generally a little tricky to use because of the time constraint, we could expect this to happen quite frequently.

Because this issue introduced a check against **token replay**, i.e. a user presenting a token that in itself is valid, **but** with a timestamp `t <= self.last_t`, in those cases we must suspect an adversary trying to replay phished tokens. So my suggestion to log *those* cases would be a little more specific with a logged warning like "suspected token replay".

So from a code perspective:

`if (totp.t() > self.last_t) and (totp.token() == token): ...`

=> if the right side of this check (`(totp.token() == token`)`) is `True`, but the left side (that has been introduced due to this ticket) is `False` (`(totp.t() > self.last_t)`), then this would be a case of a suspected token replay. Does it make sense to specifically log that case, as that may hint that someone may be trying to phish users?

**Comment by freeplant** [comment]
Thanks for the suggestion.

The log has been improved in: https://github.com/haiwen/seahub/pull/5773

**Comment by suspectpart** [comment]
Looks all good now to me, many thanks for the fix and the log improvements!
