### ISSUE TITLE
Library API Token usage very limited

### ISSUE THREAD

**Issue by creativeprojects** [haiwen/seahub#5717]
Hi, I've been using the API for some time with the auth token.

I'd like to use the newer library API token:
https://download.seafile.com/published/web-api/v2.1/library-api-tokens.md#user-content-Access%20library%20with%20API%20token

Is there any reason why there's a very limited API we can use with the library API Token?

Is it possible to allow all the endpoints to use the `RepoAPITokenAuthentication` so we would have feature parity between the original auth token and library API Token?

Ref https://github.com/rclone/rclone/issues/6126

**Comment by freeplant** [comment]
The API has been improved in this commit: https://github.com/haiwen/seahub/pull/5987  . It will be included in the next release.

The document has been improved at: https://seafile-api.readme.io/reference/get_api-v2-1-repos-repo-id-repo-api-tokens
