### ISSUE TITLE
LDAP users can't connect sync client 9.0.4 to server 11.0.1 

### ISSUE THREAD

**Issue by HenriWahl** [haiwen/seahub#5730]
Because I do not know if this is a client or server problem I crosspost https://github.com/haiwen/seafile-client/issues/1494 here:

Hi there,

we noticed that LDAP users can't connect their sync client 9.0.4 to a server 11.0.1. Using a non-LDAP user works, as does connecting to a server 10.0.1.

The server throws:
```
2023-11-03 10:43:21,973 [WARNING] django.request:241 log_response Bad Request: /api2/auth-token/
```

Any idea?

**Comment by HenriWahl** [comment]
I can reproduce it:

Works:
```
curl -X POST -F 'username=non-ldap-user@domain.com' -F 'password=secret' https://seafile.domain.com/api2/auth-token/
{"token":"8e29471fdd10bad0f998b8138a74a80f70e44e8b"}
```
Doesn't:
```
curl -X POST -F 'username=ldap-user@domain.com' -F 'password=secrettoo' https://seafile2.domain.com/api2/auth-token/
{"non_field_errors":["Unable to login with provided credentials."]}
```

**Comment by HenriWahl** [comment]
The error message `Unable to login with provided credentials.` seems to be created in https://github.com/haiwen/seahub/blob/master/seahub/api2/serializers.py#L88. 
Some lines ago in https://github.com/haiwen/seahub/blob/master/seahub/api2/serializers.py#L82 the `ccnet_api.get_primary_id(username)` is called, apparently to get the primary ID.

Isn't a big change in Seafile 11 the use of Python instead of C code for LDAP access? Might the problem derive from here? At least it matches with the observation, that only LDAP accounts have this issue - even if login via web interface works.

**Comment by freeplant** [comment]
Thanks for reporting the issue. We can reproduce the problem. It should be fixed soon.

**Comment by HenriWahl** [comment]
Looks like https://github.com/haiwen/seahub/commit/d4f93eb129e7b7532dde4ad74347136a9316fd80 is a fix? This was was fast! What do you think when it will be included in a released version?

**Comment by freeplant** [comment]
We will include it in the next release in about two weeks.
