### ISSUE TITLE
Unable to close notification pop-up

### ISSUE THREAD

**Issue by RenautMestdagh** [haiwen/seahub#5845]
I’m unable to close the notification pop-up (red square) when being inside a library and clicking inside the green square. I’m also unable to close the pop-up by clicking the notification bell again. Seahub v11.0.3

![7e9629341c798b1927191d0e484ebda3136d3c2b](https://github.com/haiwen/seahub/assets/82072978/e39c5fb9-adf4-466d-a8c0-986824d966b8)

**Comment by freeplant** [comment]
Thanks for reporting the issue. It is fixed in https://github.com/haiwen/seahub/pull/5854
