### ISSUE TITLE
"close" and "more" icon invisible

### ISSUE THREAD

**Issue by RenautMestdagh** [haiwen/seahub#5847]
The notification close icon won’t show. When pressing "view all notifications", the "close" and "more" icon won't show

![Screenshot 2023-12-19 200400](https://github.com/haiwen/seahub/assets/82072978/0033a3d7-e800-46a1-9af2-3e1a109a511e)
![Screenshot 2023-12-19 203831](https://github.com/haiwen/seahub/assets/82072978/25a13e51-f3b7-4d7b-acc2-5d4007ce8b3e)

**Comment by freeplant** [comment]
Thanks for reporting the issue. But I cannot reproduce the problem.

**Comment by RenautMestdagh** [comment]
This was indeed temporary. Don't know why.
They are back now.
