### ISSUE TITLE
Responsive layout (Optimize for mobile browsers)

### ISSUE THREAD

**Issue by jbbr** [haiwen/seahub#59]
When sharing files per link it's relatively likely that someone opens it on a smartphone or other mobile device. Currently the Seahub template is displayed in full width even on these devices. That's uncomfortable to use.
It would be great to have a fluid template which automatically resizes depending on screen size.

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/responsive-layout-optimize-for-mobile-browsers/4346
