### ISSUE TITLE
Pillow vulnerable

### ISSUE THREAD

**Issue by shoeper** [haiwen/seahub#5922]
According to docs pillow==10.0.* should be installed which is vulnerable to https://github.com/advisories/GHSA-3f63-hfp8-52jq

**Comment by freeplant** [comment]
Thanks for reporting the issue. The latest version uses pillow==10.0.*.

**Comment by shoeper** [comment]
Yes, and 10.0.* is vulnerable.

**Comment by freeplant** [comment]
It has been fixed now both in master and 10.0 branch.

**Comment by freeplant** [comment]
It has been fixed now both in master and 10.0 branch.
