### ISSUE TITLE
Downscaled Images for the new gallery view

### ISSUE THREAD

**Issue by dhoffend** [haiwen/seahub#594]
While I really like the new gallery view to walk through images, I dislike it the same way. It's using the original image which can several MB in size. Walking through 10-20 images can already take 100MB since the usual pictures taken from modern cameras are between 4-13 MB per picture.

A good way could be to provide reduced/compressed images with 2048px of the larges side. Maybe we could use the PREVIEW_DEFAULT_SIZE parameter for this provide within the dirent list additionally to the thumbnail_src a preview_src that points to the big preview images (which should be used the the modal image viewer which can be smaller in size (300-600kb instead of 6mb).

The only concern I would have would be security about the thumbnail urls (are they persistent urls?).

Btw. for the gallery feature of 5.1 (or whenever) it might be useful to have 3 sizes anyway: thumbnail (32x32), grid (256x256), preview (2048x2048) but that's a different story.

**Comment by dhoffend** [comment]
We could use the ajax content function of the magnificPopup plugin to generate the downscaled images on demand.

btw. the preview box for shared folders should be replaced by this popup also

**Comment by dhoffend** [comment]
I'm working on it. Got something working using the elementParse callback of the magnificPopup Plugin.

Works great so far, i'll send a pull request once i'm done with cleaing up the python code. I also had to tweak the thumbnail_create.

**Comment by dhoffend** [comment]
Addition stuff for the future: remote PREVIEW images from the shared directory view and replace them with the lightbox

**Comment by dhoffend** [comment]
Oh and the image file preview as well. IMHO/Maybe the fullsize image should only be served for a download request.

**Comment by dhoffend** [comment]
One question to the original authors: is there a garbage collection implimented to get rid of outdated thumbnails or is the best way to enable atime (accesstime) stats on the filesystems and remove those that have not been used for time X?

**Comment by xiez** [comment]
there is no GC for thumbnail yet, we can provide a django management command or just a shell script to clean thumbnails have not been used for time X.

**Comment by dhoffend** [comment]
But this would require the atime attribute set on the filesystem right? I guess the same applies for images that have been deleted on seafile or modified? But I guess modified means new object_id which results in a new image i guess
