### ISSUE TITLE
German translation missing for a couple of strings

### ISSUE THREAD

**Issue by freeplant** [haiwen/seahub#5950]
The German translation is missing for a couple of strings in version 10.0

**Comment by freeplant** [comment]
Fixed in PR: https://github.com/haiwen/seahub/pull/5948

**Comment by marco-websource** [comment]
I recently added a bunch missing German translations for the latest version 11.0.5 to our server instance.
I would like to submit them trough Tansifex as described here: https://manual.seafile.com/develop/translation/
However, my request to join the project seahub for language German was rejected. How can I submit my translations?

**Comment by freeplant** [comment]
Please join the existing de language instead of a new de_DE language.

**Comment by marco-websource** [comment]
> Please join the existing de language instead of a new de_DE language.

Thanks! I must have misunderstood and selected the wrong thing on the transifex website. It worked now. Thanks!
