### ISSUE TITLE
Users from an OAuth IDP with OAUTH_PROVIDER_DOMAIN longer than 32 characters are created as new users in Seafile at each login

### ISSUE THREAD

**Issue by salvisbh** [haiwen/seahub#5974]
The 'provider' field in the 'social_auth_usersocialauth' table is declared as varchar(32). With a configured 'OAUTH_PROVIDER_DOMAIN' with more than 32 characters, the entry for a new Seafile user is not created in this table, but the main transaction is successfully completed. This means that a new user exists in SeaFile, but a login is not possible due to the missing entry in 'social_auth_usersocialauth'. As a result, the user is not found during a subsequent login via OAuth and is repeatedly created as a new Seafile user. 

Troubleshooting:
- Increase field length in migration script
- Catch incorrect saving in 'social_auth_usersocialauth' table through clean error handling

Sources:
- [mysql.sql](https://github.com/haiwen/seahub/blob/master/sql/mysql.sql#L1024)
- [Creation of new SocialAuthUser](https://github.com/haiwen/seahub/blob/master/seahub/oauth/views.py#L209)

**Comment by freeplant** [comment]
Regarding OAUTH_PROVIDER_DOMAIN, it is now changed to `OAUTH_PROVIDER` https://github.com/haiwen/seahub/pull/5999/files 

The document has been changed too: https://github.com/haiwen/seafile-admin-docs/pull/267/files

You don't need to use a full domain in OAUTH_PROVIDER, any easy-to-remember string less than 32 characters will work.
