### ISSUE TITLE
Documentation of the OAUTH_ATTRIBUTE_MAP configuration in the SeafileAdmin manual not helpful and misleading

### ISSUE THREAD

**Issue by salvisbh** [haiwen/seahub#5975]
The documentation for the [OAUTH_ATTRIBUTE_MAP](https://manual.seafile.com/deploy/oauth/#configuration) variable shows examples of standard IDPs without even beginning to describe possible values and effects of the configuration. An OAuth configuration of other IDPs is practically only possible after code and database analysis. 

In a [forum answer from 2018](https://forum.seafile.com/t/oauth-question-error-with-sso/5481), a Seafile specialist tries to describe the internal logic of Seahub during the OAuth callback, which unfortunately only helps to a limited extent and should actually be included in the documentation.

The following documentation may be helpful for a successful configuration of the OAuth interface:

- A functional description of the variable, for example "The variable 'OAUTH_ATTRIBUTE_MAP' describes which claims from the response of the user info endpoint are to be filled into which attributes of the new Seafile user. The key corresponds to the OAuth claim, while the boolean from the value tuple represents the required property of the target attribute in Seafile" 
- For each possible target attribute:
   - Name
   - mandatory (True/False)
   - Usage

For the attribute `contact_email` this would look like this:
contact_email,false,eMail for notifications

**Comment by freeplant** [comment]
The document has been updated: https://github.com/haiwen/seafile-admin-docs/pull/267/files
