### ISSUE TITLE
[UX improvement] User are unsure about upload success

### ISSUE THREAD

**Issue by weimens** [haiwen/seahub#5979]
**Step to reproduce:**
- create an upload link
- upload a file

**Actual result:**
"All files uploaded" popup is shown for a short moment. Some users miss that popup. And apparently the don't realise that, the file is listed blow the upload button with status "Completed". Our User are unsure an ask our support for help. That should be avoidable.

![upload_0](https://github.com/haiwen/seahub/assets/4752766/d5a77494-83cb-4abf-9e4f-53d64b8ae5d8)

**Expected result:**
A clear visual indication that a file is uploaded.

An example idea for am more clear visual indication would, removing the popups and make the success status for the file more visible. Like the mock up images below.

![upload_1](https://github.com/haiwen/seahub/assets/4752766/c5ddaaad-9338-4d32-961c-082bb947d784)
![upload_2](https://github.com/haiwen/seahub/assets/4752766/d1c29b00-ea74-463e-b427-6ba247982a16)

**Comment by freeplant** [comment]
Thanks for reporting the issue. We will improve it in the next release.

**Comment by freeplant** [comment]
The improvement is included in version 11.0.7
