### ISSUE TITLE
AJAX calls use default CSRF cookie name

### ISSUE THREAD

**Issue by mheppner** [haiwen/seahub#605]
When changing CSRF_COOKIE_NAME in seahub_settings.py, all AJAX POST requests fail. The prepareCSRFToken() function is working as expected, but when it is called, a hard-coded value of "csrftoken" is passed in.

https://github.com/haiwen/seahub/blob/master/static/scripts/common.js#L220
https://github.com/haiwen/seahub/blob/4.1/media/js/base.js#L498

Could CSRF_COOKIE_NAME be passed down from the view to the template where ever common.js is included?

**Comment by freeplant** [comment]
This issue is obsolete.
