### ISSUE TITLE
ios video-playback

### ISSUE THREAD

**Issue by suminus** [haiwen/seahub#622]
hi, i'm using version 4.2.1 with nginx on centos and mariadb.

videoplayback on iOS-devices runs only if you manually import the self-signed-https-certificate.

accepting/trusting it when loading the web-gui is not enough. it does not depend on the used

browser.

any suggestions?

thx in advance.

**Comment by shoeper** [comment]
And what's the problem of Seafile here?
Get a trusted certificate if you want to to use iOS devices.

**Comment by suminus** [comment]
ah, ok. then i might have a problem. the server runs under dynamic dns.
or is there a way to get a trusted certificate with dyndns?

**Comment by shoeper** [comment]
You could get your own domain. Some Domains are very cheap (~USD 6 a year)

**Comment by shoeper** [comment]
But it should also work with a self signed one. Just do some research. But this is definetly no Seafile issue and this is a Bug tracker and not a support forum.

**Comment by suminus** [comment]
ok. thx.
