### ISSUE TITLE
Shared download links do not work on mobile devices

### ISSUE THREAD

**Issue by huegelc** [haiwen/seahub#630]
Hi,

I'm using the latest seafile server (4.2.2) and I have noticed that download links to shared files do not work on mobile devices (Android with Chrome) although this works on desktop clients.
I receive a unknown error and download fails.

**Comment by suminus** [comment]
probably an issue with untrusted self-signed ssl certificates.
iOS devices react the same way. you can manually import them
to solve that or get a trusted one.

**Comment by huegelc** [comment]
The certificate is issued by startssl.. There's nothing wrong with it

**Comment by ERamseth** [comment]
if the file path has an ampersand it may not function out of the box. I created a PR to fix this here: https://github.com/haiwen/seahub/pull/975

**Comment by shoeper** [comment]
I never had any issue with this and with this little information it also will not be possible to find the cause.
