### ISSUE TITLE
cached css file disturbs to use customized css file.

### ISSUE THREAD

**Issue by darkcircle** [haiwen/seahub#651]
I found that little bit weird line from the main seahub page source.

```
 <link rel="stylesheet" href="/media/CACHE/css/999e7b4d6bb4.css" type="text/css" />
```

I don't know where it comes from and it bothers me to apply newer customized css file.
how should i do to permanently change stylesheet for entire seahub page?

**Comment by freeplant** [comment]
This is auto-generated css file which combines several original css files for performance.
