### ISSUE TITLE
Sorting by File attributes (size, last change, name) in Browser App only sorts displayed items

### ISSUE THREAD

**Issue by moritzschaefer** [haiwen/seahub#652]
Having many items in a folder, Seafile Webapp only shows a few and loads more after scrolling to the bottom of the page.

Reproduce:
Load such a folder.
Sort by one of the attributes (e.g. name).

What you get:
The exact same set of files is shown in a sorted fashion.

What you expected:
The sort applies on all items in the folder (also the ones, that are not shown).

Workaround:
Scroll to the bottom until now more items get loaded. Now apply sort args

**Comment by moritzschaefer** [comment]
The feature would be really simple to implement by adding a simple 'sort' to the end of 'list_lib_dir' (dependent if the request holds a sort-field).
In templates/snippets/repo_dirents.html the table headers could simple be added a link to, to get files via ajax (as it is done by clicking on items in the list) instead of sorting the already shown files (as it is done now by some JS)

**Comment by jbbr** [comment]
+1

I have some folders with lots of files and this issue is really annoying. For example it makes it impossible to view pictures uploaded with the camera upload feature by capture time.

**Comment by moritzschaefer** [comment]
That's exactly why I came up with this. 
I talked to a friend (@Stinktier) who might want to implement this.

**Comment by jbbr** [comment]
Whoa, just checked this in latest Seafile 6.0.2: This seems to be fixed!
Thanks!
