### ISSUE TITLE
Web API "copy" fails if p is not specified in both url request and post data

### ISSUE THREAD

**Issue by SBRK** [haiwen/seahub#653]
We updated to Seafile 4.2.2 and calls to the copy operation (http://manual.seafile.com/develop/web_api.html#copy-file) started failing. After somme fiddling, it appears the parameter p has to be passed both in the url and in the post data. If the url one is ommited, we get a "400 missing argument" status code, and if the post data one is ommited, we get a "502 failed to copy file"

**Comment by CCosmo** [comment]
Same Problem. 

For me not very important but maybe mark in API Doc.
