### ISSUE TITLE
Problems viewing link-shared PDF files

### ISSUE THREAD

**Issue by ssd63** [haiwen/seahub#656]
If I create a download link for a PDF file and a user that is not logged in clicks the button "full screen", he is getting a 404 Error. Expected behaviour: He sould see the PDF file inside the browser.

Can anybody confirm this bug? Maybe I just misconfigured seafile/apache.

**Comment by shoeper** [comment]
Hi,

I wanted to verify this, unfortunately, I cannot find the fullscreen button. Where is it located on your machine? I only can increase and decrease the viewing size, and I can download the file. I'm using Pro Edition 4.2.0.

**Comment by xiez** [comment]
yes, it is a bug, will fix that in next version.

**Comment by freeplant** [comment]
This issue is obsolete.
