### ISSUE TITLE
mail notifications not working

### ISSUE THREAD

**Issue by shoeper** [haiwen/seahub#660]
I've tried to setup mail delivery as described here: http://manual.seafile.com/config/sending_email.html but wasn't succesfull. Neither with gmail (and app password) no via my own mailserver.

Is there any option to get debug info? I couldn't find anything in the logs. I've only found out that some mails have been send to my local mailbox (on the server, not the mailserver).

**Comment by ssd63** [comment]
I'm using these Settings successfully: 

> EMAIL_USE_TLS = True
> EMAIL_HOST = 'localhost'        # smpt server
> EMAIL_HOST_USER = 'user@domain.tld'    # username and domain
> EMAIL_HOST_PASSWORD = ''    # password
> EMAIL_PORT = '25'
> DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
> SERVER_EMAIL = EMAIL_HOST_USER

**Comment by shoeper** [comment]
When trying to send a share link to my mailaddress (`me@gmail.com`) I get
`Interner Serverfehler. Oder überprüfen Sie die eingegebene/n E-Mail-Adresse/n` 
in english: `Internal server error, or check given mail address`

I've got the following lines in my config:
```
# Mail settings
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'me@gmail.com'
EMAIL_PASSWORD = 'mynewapppassword'
EMAIL_PORT = '587'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# Replace default from email with user's email or not, defaults to ``False``
REPLACE_FROM_EMAIL = False

# Set reply-to header to user's email or not, defaults to ``False``. For details,
# please refer to http://www.w3.org/Protocols/rfc822/
ADD_REPLY_TO_HEADER = True

# Set this to seahub website's URL. This URL is contained in email notifications.
SITE_BASE = 'https://mysite/'

# Set this to your website's name. This is contained in email notifications.
SITE_NAME = 'mysite'

# Whether to send email when a system admin adding a new member. Default is `True`.
# NOTE: since version 1.4.
SEND_EMAIL_ON_ADDING_SYSTEM_MEMBER = True

# Whether to send email when a system admin resetting a user's password. Default is `True`.
# NOTE: since version 1.4.
SEND_EMAIL_ON_RESETTING_USER_PASSWD = True
```

**Comment by shoeper** [comment]
Now have these settings:

```
# Mail settings
EMAIL_USE_TLS = True
EMAIL_HOST = 'host'
EMAIL_HOST_USER = 'mail'
EMAIL_PASSWORD = 'password'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'mail'
SERVER_EMAIL = 'mail'
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
#SERVER_EMAIL = EMAIL_HOST_USER
REPLACE_FROM_EMAIL = False
ADD_REPLY_TO_HEADER = True
```

Using thunderbird I can send mail using exactly those settings. 

Also did the debugging described here https://forum.seafile-server.org/t/solved-email-not-working-on-new-seafile-4-0-6-but-works-on-2-1-4-help/540/2?u=shoeper
I get this:
```
2015-07-19 02:58:44,928 [ERROR] seahub.auth.views:288 password_reset {u'sven@hoeper.me': (554, '5.7.1 <myhostname[myip]>: Client host rejected: Access denied')}
Traceback (most recent call last):
  File "/seafile/seafile-pro-server-4.2.4/seahub/seahub/auth/views.py", line 285, in password_reset
    form.save(**opts)
  File "/seafile/seafile-pro-server-4.2.4/seahub/seahub/auth/forms.py", line 115, in save
    email_template_name, c, None, [user.username])
  File "/seafile/seafile-pro-server-4.2.4/seahub/seahub/utils/__init__.py", line 751, in send_html_email
    msg.send()
  File "/seafile/seafile-pro-server-4.2.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/mail/message.py", line 255, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/seafile/seafile-pro-server-4.2.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/mail/backends/smtp.py", line 95, in send_messages
    sent = self._send(message)
  File "/seafile/seafile-pro-server-4.2.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/mail/backends/smtp.py", line 113, in _send
    force_bytes(message.as_string(), charset))
  File "/usr/lib/python2.7/smtplib.py", line 733, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {u'sven@hoeper.me': (554, '5.7.1 <myhostname[myip]>: Client host rejected: Access denied')}
```
Can send with the settings above using the same recipent without any issues using thunderbird.

**Comment by Lesterpig** [comment]
Similar problem here for a local ssl-only smtp server (on port 465). When trying to send a mail, the page loads without any feedback and ends in a gateway_timeout error.

No log found in logs/seahub.log

One line found in syslog : 
```
postfix/smtps/smtpd[18667]: connect from localhost.localdomain[127.0.0.1]
```

**Comment by AuspeXeu** [comment]
Using the gmail settings as stated in the config I get this log output
```
2015-09-05 19:12:00,039 [ERROR] seahub.auth.views:289 password_reset (534, '5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbtzZ\n5.7.14 DdZtQQZxPD9oUlsJ3uELPRcfgAOuGUlTtBTrVM5V3C02griH-yI89ySNivk89Z66dHDAaQ\n5.7.14 kEMXR69nQOfYR1XGhSlMgLwOXrdkc9RtMSTFzju5kH4GDY8QAOWFa_eJ4M2wUiMOOkxoHa\n5.7.14 1YGlxROHYoh7zuhcMASu18c4366Cm-wBpUOw_ye_ZFoO9QZ7LxTyJNhhF4974LkUh1KIV5\n5.7.14 X-7uJaB0GSW4lxQ1maNGGrSJQ2y8> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 ry1sm7986564wjb.24 - gsmtp')
2015-09-05 19:13:23,022 [ERROR] seahub.auth.views:289 password_reset (534, '5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbsDS\n5.7.14 xItT_TW29bJnU8fXg7blZzhPPmmJ3lVmNnTdQBLD9mQBFk2_ISh3EbeCmdtK3COJ46bHfi\n5.7.14 pBnPV-E7zl2kfMTc7WdxFpIjVr6RaQVkDLP_YjEYJliXC015LgADOKF-XgxGQFNpVgX_M_\n5.7.14 lVZKN_e1pmBfz00WhQ5F6PdrOIROjiZUDJNjds7dB_lhfgiJbLR8MH-Lg0tntuP61c48uH\n5.7.14 8U3EvVcmhjm8aqbdJp6qwjRKaZA0> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 wx9sm9390136wjb.6 - gsmtp')
```

**Comment by shoeper** [comment]
That's unrelated to this issues and you haven't read the google links provided in the log message. In other words: you haven't done anything to fix this so far and you've wasted my time.

**Comment by AuspeXeu** [comment]
Thanks for that very helpful comment @shoeper a less moronic behaviour would be much appreciated next time. In case people encounter a similar problem. You need to allow less secure apps to connect to your google account. https://support.google.com/accounts/answer/6010255

**Comment by xiez** [comment]
thanks guys! looks like i can close this issue now.

**Comment by mlarcher** [comment]
Thanks @AuspeXeu for posting the answer I was looking for. Too bad the app is not up to Google's standards on smtp security criterias. @shoeper any chance this gets fixed some day ?

**Comment by shoeper** [comment]
@mlarcher according to my understanding the message from google is more than a little missleading. It is no insecure app, the "problem" is just that it is not using oauth but password login instead. So this is very unlike to change anytime in the feature. It would be more like a gmail specific solution. The standard way to login on smtp servers is username + password. E.g. using thunderbird with GMail also requires an app password because it's an "insecure app" (which it is definitely not).

**Comment by mlarcher** [comment]
@shoeper I see. Thanks for the quick feedback :)

**Comment by gsnable** [comment]
> Similar problem here for a local ssl-only smtp server (on port 465). When trying to send a mail, the page loads without any feedback and ends in a gateway_timeout error.
> 
> Trace in seahub.log :
> 
> ```
> 2015-08-05 15:09:00,306 [ERROR] seahub.auth.views:293 password_reset Connection unexpectedly closed
> Traceback (most recent call last):
>   File "/srv/seafile/lestercloud/seafile-server-4.2.1/seahub/seahub/auth/views.py", line 291, in password_reset
>     form.save(**opts)
>   File "/srv/seafile/lestercloud/seafile-server-4.2.1/seahub/seahub/auth/forms.py", line 115, in save
>     email_template_name, c, None, [user.username])
>   File "/srv/seafile/lestercloud/seafile-server-4.2.1/seahub/seahub/utils/__init__.py", line 751, in send_html_email
>     msg.send()
>   File "/srv/seafile/lestercloud/seafile-server-4.2.1/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/mail/message.py", line 255, in send
>     return self.get_connection(fail_silently).send_messages([self])
>   File "/srv/seafile/lestercloud/seafile-server-4.2.1/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/mail/backends/smtp.py", line 88, in send_messages
>     new_conn_created = self.open()
>   File "/srv/seafile/lestercloud/seafile-server-4.2.1/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/mail/backends/smtp.py", line 49, in open
>     local_hostname=DNS_NAME.get_fqdn())
>   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/usr/lib/python2.7/smtplib.py", line 317, in connect
>     (code, msg) = self.getreply()
>   File "/usr/lib/python2.7/smtplib.py", line 368, in getreply
>     raise SMTPServerDisconnected("Connection unexpectedly closed")
> SMTPServerDisconnected: Connection unexpectedly closed
> ```
> 
> Several lines found in syslog :
> 
> ```
> postfix/smtps/smtpd[18667]: connect from localhost.localdomain[127.0.0.1]
> postfix/smtps/smtpd[18029]: SSL_accept error from localhost.localdomain[127.0.0.1]: Connection timed out
> postfix/smtps/smtpd[18029]: lost connection after CONNECT from localhost.localdomain[127.0.0.1]
> postfix/smtps/smtpd[18029]: disconnect from localhost.localdomain[127.0.0.1]
> ```

If using port 465, an SSL connection needs to be established, so it needs to be replaced with EMAIL_ USE_ SSL=True.
