### ISSUE TITLE
Online Office integration : "view" only action is failing when the discovery allows editing actions

### ISSUE THREAD

**Issue by Gregory-Widmer** [haiwen/seahub#6712]
Hi,

I've been struggling with integrating Collabora Online Dev Edition (CODE) to edit files from the SeaFile web interface. I'm running SeaFile CE 11.0.5 version and CoolWsd 24.04.6.1 (https://github.com/CollaboraOnline/online/commits/8ec5fda).

When connected as a user, everything is smooth and the integration is working correctly. However, when sharing a link, I get an error message : 'Error when prepare Office Online file preview page.' 

I debugged the issue and saw that SeaHub returns that error when it is not able to :
- Fetch the WOPI Discovery actions
- Find the wanted action

Here, we fall in the second issue. Your code for finding the action within the XML is this loop :
https://github.com/haiwen/seahub/blob/a13dc827990f41eff2a6551cf2549f013971b3af/seahub/wopi/utils.py#L125-L141

To understand the issue, let's take my example. I shared a link, a **read-only** link to an XLSX spreadsheet. Seahub tried to find within its Django cache an action for **viewing** XSLX files.

It also wants an action for **viewing** XSLX files from the WOPI /hosting/discovery XML file.
However, let's take a look at what my CODE instance returns regarding spreadsheets :

```XML
<!--  OOXML spreadsheet  -->
<action default="true" ext="xltx" name="view" urlsrc="https://<REDACTED>/browser/8ec5fda/cool.html?"/>
<action default="true" ext="xltm" name="view" urlsrc="https://<REDACTED>/browser/8ec5fda/cool.html?"/>
<action default="true" ext="xlsx" name="edit" urlsrc="https://<REDACTED>/browser/8ec5fda/cool.html?"/>
<action default="true" ext="xlsb" name="edit" urlsrc="https://<REDACTED>/browser/8ec5fda/cool.html?"/>
<action default="true" ext="xlsm" name="edit" urlsrc="https://<REDACTED>/browser/8ec5fda/cool.html?"/>
```

For XLSX files, the action is "edit". They do not provide a "view" action, and I found the explaination on why here : https://github.com/CollaboraOnline/online/issues/4690

If the instance returns an "edit" action, it also means you can request a "view" action from it.
However, because we always expect a "wopi_edit_xlsx" cache key on line 138, we are never able to preview the file.

After finding that, I implemented a little workaround on my Seahub instance : 
```Python
        for action in root.iter('action'):
            attr = action.attrib
            ext = attr.get('ext')
            name = attr.get('name')
            urlsrc = attr.get('urlsrc')
            if ext and name and urlsrc:

                tmp_action_url = re.sub(r'<.*>', '', urlsrc)
                tmp_wopi_key = generate_discovery_cache_key(name, ext)
                cache.set(tmp_wopi_key, tmp_action_url,
                        OFFICE_WEB_APP_DISCOVERY_EXPIRATION)
                if wopi_key == tmp_wopi_key:
                    action_url = tmp_action_url
                elif action_name == 'view' and name == 'edit' and wopi_key == generate_discovery_cache_key('view', ext):
                    action_url = tmp_action_url
            else:
                continue
```
I'm checking if the requested action is "view", the provided XML action is "edit" and try to compare the WOPI key for a view action instead of an edit.

I could open a PR for that with this workaround, but I do not know how is the WOPI action cache implemented exactly, so I do not want to interfere here. I guess we should try somewhere else to check for a view action on an edit link, because with my workaround, we have to fetch every time the Discovery XML to find the wanted key as we do not check earlier for this key.

With that workaround, previewing a file works, even with shared links.

Regards,

**Comment by freeplant** [comment]
I think we have fixed the issue in the latest version. Can you re-test with version 11.0.12?

**Comment by Gregory-Widmer** [comment]
Indeed, it has been fixed. I'm closing the issue :)
