### ISSUE TITLE
Generate download link and byte-range requests : only one request

### ISSUE THREAD

**Issue by Chocobozzz** [haiwen/seahub#677]
When we generate a download link with the api (http://manual.seafile.com/develop/web_api.html#download-file) if I understand well the link is deleted after the first access.

But with the awesome byte-range request feature from Seafile 4.2 we maybe need to make many requests on the same file with different byte ranges (to get the tags of a music without completely downloading the file for example).

Thus, deleting the download link after the first access causes some issues and limits the interest of the byte-range request implementation.

Thanks in advance.

**Comment by shoeper** [comment]
I've also pointed this out somewhere. I'm interested in the answer.

**Comment by Chocobozzz** [comment]
Any news on this ?

**Comment by freeplant** [comment]
We will add support for this when other tasks done.

**Comment by freeplant** [comment]
Or you can add it yourself and make a pull request. Just check how sharing link is generated to support byte-range requests.

**Comment by Chocobozzz** [comment]
No problems, just wanted to have some news.

Unfortunately I don"t have time to make a PR. I appreciate your work, good luck!

**Comment by xiez** [comment]
hi, we add `reuse` argument in download file api in 4.4.1 server, can u take a test ? simply add `reuse=1`.

**Comment by Chocobozzz** [comment]
Great! Seems to work well. Thanks a lot guys :)
