### ISSUE TITLE
uploading screen shows chinese (incomplete to localize)

### ISSUE THREAD

**Issue by darkcircle** [haiwen/seahub#699]
my friend/customer tests newer version on the google chrome,
and reports to me that uploading box and preview screen on the web page (pro edition)  

shows chinese message, so it seems to not be translated properly.

or

some code makes to show localized message doesn't work properly.

attached captured page is showing within the chrome window.

![weird_localization](https://cloud.githubusercontent.com/assets/1160498/8546337/e7de31f6-24f1-11e5-91d3-89c09cbea5d3.png)

**Comment by darkcircle** [comment]
and it also shows from Firefox/Linux.

**Comment by freeplant** [comment]
This is a bug in pro edition. We have fixed it in version pro v4.2.3.

**Comment by darkcircle** [comment]
Thank you so much :D
