### ISSUE TITLE
Last update field displays "Fetch failed" for any file

### ISSUE THREAD

**Issue by mathieu-mp** [haiwen/seahub#700]
Last update field displays "Fetch failed" for any file (for a very long time), on admin user (which is the first user I created). In admin panel, user creation time also displays 1970-01-01 08:00:00.
![last-update-fetch-failed](https://cloud.githubusercontent.com/assets/8644213/8546274/a6f32ace-24b6-11e5-858f-714878b5a94a.JPG)

Update time are displayed correctly in library list (as opposed to file list)
All update time are OK for files in libraries owned by anyone alse than the first user created.
User creation time are OK for any other user.

Server is 4.2.3 and user and libraries were created many versions ago (probably v2.x.x)

**Comment by novaflash** [comment]
I have exactly the same problem. Updated to 4.2.3 from 2.1.5 (and with the upgrade scripts inbetween run). New libraries have the proper dates shown. Existing libraries are fucked. Even with new files in existing libraries.

**Comment by shoeper** [comment]
All libraries created before 3.x do have an old library format and don't support dates. One user on the seafile forum tries to write an upgrade script. You can have a look at that or live with it or create a new library and move your files (of course, history is lost)

**Comment by novaflash** [comment]
Thank you shoeper, this is useful information. The logic of the situation eludes me but that is probably just lack of knowledge on this particular matter.

Can you point me in the direction of the forum entry to convert this information? I would rather not have to ask all my users to reconfigure everything, and I do want the error gone.

**Comment by shoeper** [comment]
https://forum.seafile-server.org/t/migration-of-old-library-format-to-the-new-library-format/2094/3

It has NOT been finished so far.

**Comment by novaflash** [comment]
Don't worry, I won't risk running this on my production systems until it is finished and I've done tests on it with a full snapshot of the current situation. Don't want this system to blow up.

Thank you for the link and the information shoeper. If you were a pretty lady I'd kiss you.

**Comment by mathieu-mp** [comment]
So the upgrade scripts did not achieve the job.
Is there any chance for an upgrade script to be released by the official dev team?

**Comment by shoeper** [comment]
No.
