### ISSUE TITLE
前端 npm install 为啥@seafile/sf-metadata-ui-component 库

### ISSUE THREAD

**Issue by gongxihai22** [haiwen/seahub#7050]
![Uploading aaaa.png…]()

**Comment by gongxihai22** [comment]
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@seafile%2fsf-metadata-ui-component - Not found
npm ERR! 404 
npm ERR! 404  '@seafile/sf-metadata-ui-component@^0.0.53' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'frontend'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by YangGuoXuan-0503** [comment]
亲，你可以再重新npm install 一下

**Comment by gongxihai22** [comment]
可以了
