### ISSUE TITLE
mod_proxy_fcgi support

### ISSUE THREAD

**Issue by warrenseine** [haiwen/seahub#708]
Apache now recommends to use `mod_proxy_fcgi` instead of `mod_fastcgi` (suggested in the [documentation](http://manual.seafile.com/deploy/deploy_with_apache.html)).

Do you have some experience running Seafile with this Apache module? Any documentation?

By the way, the link to download the

**Comment by xiez** [comment]
not yet,  can u use mod_proxy instead of fastcgi, this would be much easier for apache ?

**Comment by warrenseine** [comment]
I've made it work. Here's my Apache configuration if that helps someone.

```
<Directory "/opt/seafile/seafile-server-latest/seahub/media">
    Require         all granted
    Options         Indexes FollowSymLinks
    AllowOverride   all
</Directory>

SetEnvIf        Authorization "(.*)" HTTP_AUTHORIZATION=$1
SetEnvIf        Request_URI . proxy-fcgi-pathinfo=1

RewriteRule     ^/media/(.*)  /opt/seafile/seafile-server-latest/seahub/media/$1
RewriteCond     %{REQUEST_FILENAME} -f
RewriteRule     ^ - [L]

RewriteRule         ^/seafhttp/(.*) http://127.0.0.1:8082/$1 [P,L]
ProxyPassReverse    /seafhttp/ http://127.0.0.1:8082/
ProxyPassMatch      ^/(.*) fcgi://127.0.0.1:8000
```
