### ISSUE TITLE
Thumbnail generator forks too many workers and eat all memory

### ISSUE THREAD

**Issue by SyuTingSong** [haiwen/seahub#713]
When I visit a folder contains a large number of pictures from seahub web UI via http2 + fastcgi, the thumbnail http request break the 6 concurrency connection per domain limitation. Seahub forks a lot of sub processes to generate thumbnail, then the entire memory would be taken in a few seconds. Would you please limit the number of thumbnail generator processes or check the memory usage before forking?

**Comment by freeplant** [comment]
This can't be done at the Python part, because the Django framework don't have to limit the number of tasks.
