### ISSUE TITLE
expired share links aren't removed from UI.

### ISSUE THREAD

**Issue by shoeper** [haiwen/seahub#726]
share links are still shown under /share/links/ after expiary (but they aren't accessible anymore).

**Comment by shoeper** [comment]
Currently the list is also sorted like this:

 * links being valid forever are at the top
 * other links are listed from expirering first (including those that akready expired) to the one which expires latest.

When this list is getting long expired links are at the top and new links at the bottom. This is not very handy.

**Comment by freeplant** [comment]
Adding sorting function is a solution.

**Comment by shoeper** [comment]
Yeah would be one. It seems currently be sorted by the server. Would be helpful if those links with expiary date would be sorted just the other way around.

**Comment by shoeper** [comment]
I'm okay with the current behavior.
