### ISSUE TITLE
Error when trying to share library via API

### ISSUE THREAD

**Issue by makkus** [haiwen/seahub#734]
When trying to call the '/shared-repos/[repo-id]/' endpoint (using PUT, as specified in the documentation), I'm getting this error:

{"error_msg": "Permission need to be rw or r."}

I've looked into the code:

https://github.com/haiwen/seahub/blob/master/seahub/api2/views.py#L3016

and it seems the request.GET method is used to retrieve the 'permission' parameter. Inserting debug statements confirms that all those variables are empty (share_type, group_id, permission). I don't have much experience with Django, but after some google-fu it seems request.GET won't work for PUT requests, and the parameters need to be extracted in a different way (for example: http://www.leemckinnon.com/solving-wsgirequest-object-has-no-attribute-put/ -- haven't tested this, might not work with this particular version of Django either). Anyway, might be worth checking all other PUT (and possibly DELETE) methods for the API, to make sure this is not the only place where parameter extraction fails...

**Comment by imwhatiam** [comment]
@makkus as written in http://manual.seafile.com/develop/web_api.html#share-a-library

**Comment by makkus** [comment]
Ups, sorry, didn't see that. Thanks!
