### ISSUE TITLE
not all download are counted towards quota

### ISSUE THREAD

**Issue by shoeper** [haiwen/seahub#742]
Following case: One shares a file via link.

When this link is being visited via browser the visitor counter goes one up. When one downloads the file it is counted to the quota/traffic. So far so good. When the files is getting download with ?dl=1 via Browser it is counted as well. But when I download the file via wget with dl=1 this is not getting counted towards the quota/traffic.

Edit: btw Seafile only counts on start according to what I've seen. So in case the user wasn't able to finish the download the whole filesize is still counted towards quota.

**Comment by shoeper** [comment]
This is still there in pro 4.3.3

**Comment by freeplant** [comment]
This is a small issue. We will fix the problem when we have time.

**Comment by xiez** [comment]
Fixed in https://github.com/haiwen/seahub/commit/753efdb0821e6f8c1992ebe15f8f96a215742ccc, will be included in next release. 
Thanks again!

**Comment by shoeper** [comment]
Thanks for writing a fix!
