### ISSUE TITLE
[SOVED] Incorrect time zone

### ISSUE THREAD

**Issue by rcoss** [haiwen/seahub#746]
When showing devices page in browser, and mouse hovering over the Last Access column, the pop up
shows the date of last access using time  zone  UTC +0800 always, despite having set 
TIME_ZONE = 'UTC-3' in seahub_settings.py
[EDIT] seafile server version  is 4.2.3
[EDIT] I was using the wrong name for the tz, should be America/Argentina/Buenos_Aires

**Comment by xiez** [comment]
i assume this issues is solved, close now.
