### ISSUE TITLE
Translations in seahub/seahub/settings.py

### ISSUE THREAD

**Issue by rcoss** [haiwen/seahub#748]
@xiez , @the_team:
The strings in the array LANGUAGES are partially translated. I believe that each language name should be written in that same language. Just as you wrote "Español" for Spanish language, could you please write "Español de Argentina" instead of "Argentinian Spanish", and "Español de México" instead of "Mexican Spanish"?  I'm asking this because those strings do not get into transifex and I'm very lazy to make a pull request for just two strings.
Thx.

**Comment by xiez** [comment]
okay, will update that

**Comment by xiez** [comment]
done, https://github.com/haiwen/seahub/commit/2006fe63acc297a24ad56088468ce9f47017e6bf

**Comment by rcoss** [comment]
@xiez 
Thank you.
