### ISSUE TITLE
Seahub - failed admin login 

### ISSUE THREAD

**Issue by bogprs** [haiwen/seahub#753]
Hi. 
I am unable to access to admin nor user accounts through Seahub web-portal (:8000) after upgrading from 2.1 to 4.3 (I did ran all update shell scripts).

When looking at /seafile/logs/seahub.log it seams that web-portal mixes up entered data: it displays user mail with %40 instead a regular @

N.B. Clients on mobile and PC seem to work perfectly - nevertheless, I cannot log in on a newly installed client.

Best,
Bogdan

**Comment by shoeper** [comment]
%40 mustn't be a problem it's also @.
Client and mobile use tokens which are deleted on logout or via web interface only.

**Comment by xiez** [comment]
Can u paste related log files in logs/ dir ? like ccnet.log seahub.log, seahub_django_request.log ?

**Comment by bogprs** [comment]
Sure.
Here are log excerpts since 23.07. - the moment when I updated the server...
I uploaded a zip of entire logs folder instead pasting things...
https://drive.google.com/open?id=0B3BFGmM6CduDamxvRTV0VGhncVk

Thanks for your help.

**Comment by bogprs** [comment]
Another angle on the issue:

I managed to gain access to user web-interface through Seafile app by right-clicliking on a library and selecting "View on Cloud".
Nevertheless, I still cannot change password nor access ADMIN part of the site.

**Comment by bogprs** [comment]
I finally found the solution posted in another thread:

* Somehow the structure of ccnet-db have changed between seafile versions 2 and 3.
* Access mysql: mysql --user=myUser --password=myPassword -D ccnet-db
* One should alter the ccnet-db with the following command:
ALTER TABLE EmailUser MODIFY passwd varchar(256);
* Restart Seafile and Seahub
