### ISSUE TITLE
Reset user password always uses the same random-looking password

### ISSUE THREAD

**Issue by mathieu-mp** [haiwen/seahub#755]
Reset user password via admin page always uses the same random-looking password, whatever the account you reset.

**Comment by freeplant** [comment]
As I tesing, if you reset passwords in a very short time, the generated password is the same. I mark it as not a bug.

**Comment by mathieu-mp** [comment]
So it's not a bug that randomize does not randomize?

**Comment by freeplant** [comment]
The problem should have been fixed.
