### ISSUE TITLE
Bug: Wrong time zone in history > details

### ISSUE THREAD

**Issue by mathieu-mp** [haiwen/seahub#756]
Time zone is wrong in History > Description of a ùodification > Details

**Comment by mathieu-mp** [comment]
No one to solve a bug?

**Comment by typingm0nk** [comment]
Did you set the timezone in [seahub_settings.py](http://manual.seafile.com/config/seahub_settings_py.html) correctly?

should be for you:
``` TIME_ZONE = 'Europe/Paris' ```

**Comment by xiez** [comment]
Hi, what about the time zone in other pages ?

**Comment by mathieu-mp** [comment]
I did set the timezone after Malte Schmidt message, that won't correct the
bug.
All times in other pages look OK.

Thanks for your interest.

2015-09-29 9:39 GMT+02:00 xiez <notifications@github.com>:
