### ISSUE TITLE
Documentation Installation with Pip

### ISSUE THREAD

**Issue by madflow** [haiwen/seahub#763]
The README states that a simple `pip install -r requirements.txt` should suffice to install the seahub dependencies.

However on Ubuntu 15.04 with virtualenv you I needed `pip install --allow-external Djblets --allow-unverified PIL -r requirements.txt`

Is this just missing in the documentation or is the "real" issue the outdated dependency chain?

**Comment by xiez** [comment]
hi, do u mean `pip install -r requirements.txt` on Ubuntu 15.04 will not install djblets and PIL ?

Since djblets is in requirements.txt, and PIL is replaced by Pillow, which is also in the file.

**Comment by madflow** [comment]
Basically yes: That is what I am saying. A simple ```pip install -r requirements.txt``` did not work for me.  Maybe it is OS/Version specific... Maybe it is related to #477 .
