### ISSUE TITLE
SHARE_ACCESS_PASSWD_TIMEOUT

### ISSUE THREAD

**Issue by sarevok** [haiwen/seahub#783]
Our clients sends us a possible password protected share link issue scenario:
0. You need comapny network hidden behind a geteway/proxy.
1. One user generates password-protected sharing link to a file.
2. Another user opened this link and type the password. Password is remembered by Seahub for 1 hour.
3. All users who uses company network can access the password-protected file without password for one hour if they are using the same webbrowser as first user, i.e. Firefox

The workaround is to set SHARE_ACCESS_PASSWD_TIMEOUT to 1.
But could you add a parameter to disable password remembering?

Best regards,
Staszek Jankowski

**Comment by freeplant** [comment]
This issue is obsolete.
