### ISSUE TITLE
Accession a users settings page I seahub I get Page unavailable

### ISSUE THREAD

**Issue by confile** [haiwen/seahub#790]
Accession a users settings page I seahub I get Page unavailable:

![bibliotheken_-_private_seafile](https://cloud.githubusercontent.com/assets/64265/9567284/2a523408-4f25-11e5-869c-6b1a9e2e6795.png)

![page_unavailable](https://cloud.githubusercontent.com/assets/64265/9567282/16809a50-4f25-11e5-868a-8bd491656e33.png)

This does not hold for every user but for some.

**Comment by shoeper** [comment]
This is an issue tracker, no support forum.

**Comment by confile** [comment]
@shoeper  Well this is an issue.

**Comment by shoeper** [comment]
I don't think so. Most times something looks like an issue it's a configuration or hardware fault.

**Comment by confile** [comment]
Well, with my admin user I can access the "Settings" Page on the web interface. When I create another user, login and go to settings then I get the error page. 

@shoeper I know you are an expert. Do you have any good advice for me. Thanks in advance.

**Comment by shoeper** [comment]
Yeah I have the advice to ask on the forums first, before filing an issue.

I've just tested it on multiple servers with admin and user accounts. That's why I doubt we can talk about an issue that needs a fix.
