### ISSUE TITLE
Missing "replace" in UI

### ISSUE THREAD

**Issue by NNois** [haiwen/seahub#793]
Hi Replace file is missing in the UI.
This pose problems when a user want to silently replace an already shared file ;-)

**Comment by shoeper** [comment]
Uploading a file with the same name should work. You get a dialog, if you want to replace the file or not (then the new file will be named filename (1).extension)

**Comment by NNois** [comment]
so obvious ! may i ask a similar dialogue for a multiple file drop, in this case there is no replace prompt dialog ;-)

**Comment by shoeper** [comment]
I'm not sure if there is one. Have a test and you'll find out ;)

**Comment by llj** [comment]
The dialog appears only when you upload a single file.
