### ISSUE TITLE
Fix setup-seafile-mysql.sh to correctly set user permissions on remote servers

### ISSUE THREAD

**Issue by waza-ari** [haiwen/seahub#798]
setup-seafile-mysql.sh can be used to configure MySQL Servers. The users are generated automatically. When however using a different server than localhost, the user permissions are not set correctly.

The user is created for "localhost" and not for the actual host and hence the setup script fails, as it cannot connect to the database coming from remote. Please fix this issue.

**Comment by shoeper** [comment]
I've made a fix but wasn't able to test it so far. Could you test it? 

See https://github.com/haiwen/seafile/commit/4a58fc9fd8427c731535290c801862a7469b728b

**Comment by waza-ari** [comment]
Problem is already  tracked [here](https://github.com/haiwen/seafile/issues/1323), hence I am closing this issue.

**Comment by killing** [comment]
@shoeper Have you made a PR?

**Comment by shoeper** [comment]
So far I have't because my fix is untested. I'm going to improve it later and post it in the linked issue. If it works I create a PR.
