### ISSUE TITLE
Quota exceeding possible

### ISSUE THREAD

**Issue by HenriWahl** [haiwen/seahub#80]
Hi,
whether by web upload or seafile client syncing it is possible to put files into a repo beyond quota. The quota check seems only to apply after a file is uploaded/synced. If a file leads to quota exceeding all next files will not be uploaded, but it is possible to put a 30 MB file into a repo with a quota of 1 MB. Shouldn't quota be checked before upload or at least the exceeding file being deleted after upload?
Regards

**Comment by freeplant** [comment]
It is fixed for file syncing and web uploading.

**Comment by HenriWahl** [comment]
Thank you!
