### ISSUE TITLE
no mail notification when bulk importing users via csv

### ISSUE THREAD

**Issue by fz883** [haiwen/seahub#819]
Hi,

recently I've added users one by one via the web interface. Today I wanted to import 3 new users via the bulk import tool and uploaded a csv file. The import itself worked like a charm but the just added users never received a notification. Also, I did not find a explanation for this in the manual. Did I miss something here? I'd consider this as a todo-issue / feature request...

Thanks

**Comment by astruck** [comment]
What is the use case of not sending out e-mails when bulk-importing users via csv? For my service, I want them to receive the customized e-mail notification.

**Comment by freeplant** [comment]
OK. The feature will be added. Can you submit the issue to https://github.com/haiwen/seafile? So we can track it.
