### ISSUE TITLE
[Feature] Create Sub pages in wiki

### ISSUE THREAD

**Issue by Pi3R1k** [haiwen/seahub#82]
Create Sub pages to use https://github.com/rnons/mikidown as fat app on desktop

**Comment by shoeper** [comment]
To keep the issue tracker clean this feature request has been moved to https://forum.seafile-server.org/t/create-sub-pages-in-wiki/4347

**Comment by shuhaowu** [comment]
Given the seafile.com vs seafile.de stuff back then, can this issue be re-opened? There is nowhere else that tracks this?

**Comment by moschlar** [comment]
👍
