### ISSUE TITLE
feature request: Longer tokens for share links

### ISSUE THREAD

**Issue by tgharold** [haiwen/seahub#832]
The current default for share links is only length 10, which is only 40 bits (4 bits per character due to using hexadecimal).  For security against someone guessing permanent share URLs, it should be lengthened to at least 16 characters (64 bits).
- There should be a global seahub_settings.py variable to control length of the randomized portion of the share link.
- Allow values up to 50 characters (might impact database?).
- Consider using URL-friendly MIME character set (MIME::Base64::URLSafe) of (A-Z,a-z,0-9) plus underscore and hyphen to get 6 bits of entropy per character instead of just four.

If the change is made to use URL-safe MIME values (6 bits per position) combined with a length of 25, the strength of the URL is then 6x25 or 150 bits.

Example:
https://github.com/haiwen/seahub/blob/master/seahub/share/models.py#L62
- This occurs at (3) different locations in share/models.py

**Comment by xiez** [comment]
thanks @tgharold , we will add that.

**Comment by shoeper** [comment]
This has been implemented. If I saw it correct the setting should be `SHARE_LINK_TOKEN_LENGTH`.
