### ISSUE TITLE
Browser Interface broken in IE10

### ISSUE THREAD

**Issue by andi-blafasl** [haiwen/seahub#833]
Inside a Library you cannot create a New Folder, New File, or Sharing.
If you click the buttons on top, the IE errors with

SCRIPT438: Das Objekt unterstützt die Eigenschaft oder Methode "removeExpression" nicht
Datei: main.277def0b4696.js, Zeile: 205, Spalte: 274033
Excuse the German error message, but I think the Problem should be clear. 
You can also reproduce the Problem in IE11 when setting the Emulation Dokumentmode to IE10

I found a simmilar bug here: ericmmartin/simplemodal#58
Maybe the solution there can be used in seafile as well.

**Comment by llj** [comment]
It's fixed now. Thanks for telling us the problem.
