### ISSUE TITLE
Top menu not highlighted when accessing libraries

### ISSUE THREAD

**Issue by Radapompa** [haiwen/seahub#834]
When accessing the libraries page. My Home tab in the top menu isn't highlighted. It seems that in /seahub/seahub/templates/libraries.html that there dosen't exist a block for current tab. Also the tab selection seems to be missing in /seahub/seahub/templates/base_for_backbone.html.

Seems to be the same situation for group libraries.

Tested with Seafile 4.3.2.

**Comment by freeplant** [comment]
This issue is obsolete.
