### ISSUE TITLE
[Bug] image preview doesn't read orientation from EXIF

### ISSUE THREAD

**Issue by dakira** [haiwen/seahub#835]
Images uploaded from mobile or cameras have the actual image orientation saved in the EXIF meta data which clients can read and rotate images accoringly.

The image preview in seahub doesn't rotate the images. This was recently fixed for the iOS client but is still present in the webinterface.

The Magnific Popup library that you use doesn't seem to support image rotation on EXIF data while others definately do.

**Comment by dakira** [comment]
@freeplant Hey. Just wanted to bump this a little. It would be really nice to use the webinterface to look at images I uploaded from my phone. This bug makes that pretty much useless.

**Comment by freeplant** [comment]
We will look into the issue.

**Comment by spidernik84** [comment]
Hello! I'm also interested in a fix for this. Thanks!

**Comment by freeplant** [comment]
The orientation for thumbnails is already fixed in version 6.0.4. The orientation in the popup doesn't  fixed yet.

**Comment by Hengjie** [comment]
You could potentially fix the popup in certain browsers with this CSS:
```
image-orientation: from-image;
```

Unfortunately, it's currently [only adopted by Firefox and Safari.](http://caniuse.com/#search=image-orientation)

**Comment by 4ley** [comment]
+1 please fix also in shared public image view.

**Comment by freeplant** [comment]
It will be fixed in version 6.1.

**Comment by halfsoft** [comment]
https://jsfiddle.net/halfsoft/pxf9x977/

this is a small code snippet that rotates images while also fixing the positions of the other elements around the image

the exif data is readable using https://github.com/exif-js/exif-js

if somebody feels like it , it should take no more than 30 minutes to implement the auto rotation for all browsers.
