### ISSUE TITLE
Responsive UI

### ISSUE THREAD

**Issue by comzeradd** [haiwen/seahub#895]
It shouldn't be a requirement to install an app in order to access your account on mobile (and not all people use android or ios). The web interface should adapt to mobile resolutions.

**Comment by freeplant** [comment]
Yes, we will work on responsive UI. It is a major task, we will begin to work on it when other major tasks finished.

**Comment by biodiv** [comment]
Has there already been a decision on which grid framework - if any - will be used (bootstrap, foundation etc) ?

**Comment by freeplant** [comment]
bootstrap will be used.

**Comment by freeplant** [comment]
Implemented in version 6.0
