### ISSUE TITLE
Add support for write-only share

### ISSUE THREAD

**Issue by isrc** [haiwen/seahub#908]
Hi,
Thanks for making seafile ! 
Would it possible to add a write-only option when sharing  a folder please ? 

The use case is pretty simple as this will allow the setting up of  a "drop box" like share where a user could upload their files but couldn't  allow him to download files uploaded by others (or even by them). 

Thanks.
Regards,

**Comment by shoeper** [comment]
This is already possible in the pro edition and called "Upload Link".

**Comment by levinus** [comment]
I think there is a "Upload Link" Feature in the Community Edition too?!

**Comment by shoeper** [comment]
> I think there is a "Upload Link" Feature in the Community Edition too?!

Could be that there is. I assumed that @isrc searched for the feature and wasn't able to find it. Have currently no ce server here to have a quick look at it.

**Comment by levinus** [comment]
>Have currently no ce server here to have a quick look at it.
> -- @shoeper

There is one. I tested it. (In the "Share" menu of a folder, beside the "Download Link" option)

**Comment by isrc** [comment]
Oh, my apologies ! I'm having some issues installing the FreeBSD port of seafile/seahub in a Jail right now (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203933) so my feature request was only based on reading this docs http://help.seafile.com/en/web/folder_permission.html 
Thanks guys for taking the time to answer me and again, sorry about my bogus  report :-/
