### ISSUE TITLE
plugin architecture (rtf viewer/odf viewer/ etc..)

### ISSUE THREAD

**Issue by lkwg82** [haiwen/seahub#92]
Hi 

what about a defined plugin interface to build up a plugin community.

Plugins where my first thought, when I read #91. 

What is your opinion on that?

**Comment by shoeper** [comment]
Maybe this stackoverflow can provide some general information on how to create a plugin architecture http://stackoverflow.com/questions/2768104/how-to-create-a-flexible-plug-in-architecture

**Comment by freeplant** [comment]
Currently Seafile already support lots of format. The internal code is already an extensible code for different file types.
