### ISSUE TITLE
Wrong URI when downloading files after changing host

### ISSUE THREAD

**Issue by Niolak** [haiwen/seahub#994]
In seahub, when trying to download files, the link https://example.com/seafile/lib/7bdae47f-eb21-4673-879e-6cce5a5fe22f/file/folder/IMG.jpg is redirected to https://pi/seafhttp/files/a45eb4f6-6b12-4b2c-b4f0-a155e82f17c0/IMG.jpg 

The host was pi in my local network but I updated the config for it to be example.com and I don't understand why there's still a reference to "pi".

nginx.conf:

> server {
>    listen 80;
>    server_name example.com;
>    rewrite ^ https://$http_host$request_uri? permanent;
>  }
> server {
>    listen 443;
>    ssl on;
>    ssl_certificate /etc/ssl/cacert.pem;
>    ssl_certificate_key /etc/ssl/privkey.pem;
>    server_name example.com;
> 
>    proxy_set_header X-Forwarded-For $remote_addr;
> 
>    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
>    server_tokens off;
> 
>    location /seafile/ {
>        fastcgi_pass    127.0.0.1:8000;
>        fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
>        fastcgi_param   PATH_INFO           $fastcgi_script_name;
> 
> ```
>    fastcgi_param    SERVER_PROTOCOL        $server_protocol;
>    fastcgi_param   QUERY_STRING        $query_string;
>    fastcgi_param   REQUEST_METHOD      $request_method;
>    fastcgi_param   CONTENT_TYPE        $content_type;
>    fastcgi_param   CONTENT_LENGTH      $content_length;
>    fastcgi_param    SERVER_ADDR         $server_addr;
>    fastcgi_param    SERVER_PORT         $server_port;
>    fastcgi_param    SERVER_NAME         $server_name;
>    fastcgi_param   REMOTE_ADDR         $remote_addr;
> 
>    fastcgi_param   HTTPS   on;
>    fastcgi_param   HTTP_SCHEME     https;
>    access_log      /var/log/nginx/seahub.access.log;
>    error_log       /var/log/nginx/seahub.error.log;
> ```
> 
>    }
> 
>    location /seafhttp {
>        rewrite ^/seafhttp(.*)$ $1 break;
>        proxy_pass http://127.0.0.1:8082;
>        client_max_body_size 0;
>        proxy_connect_timeout  36000s;
>        proxy_read_timeout  36000s;
>        proxy_send_timeout  36000s;
>    }
> 
>    location /seafile/media {
>        rewrite ^/seafile/media(.*)$ /media$1 break;
>        root /srv/seafile-server/seafile-server-latest/seahub;
>    }
>  }

I set `SERVICE_URL=https://example.com/seafile` in my ccnet.conf and added the following lines in my seahub_settings.py:

> SERVER_STATIC = False
> SITE_ROOT = '/seafile/'
> MEDIA_URL = '/seafile/media/'
> COMPRESS_URL = MEDIA_URL
> STATIC_URL = MEDIA_URL + 'assets/'
> FILE_SERVER_ROOT = 'https://example.com/seafhttp'

What could be wrong?

**Comment by shoeper** [comment]
https://forum.seafile-server.org
